import test from'node:test';
import assert from'node:assert/strict';
import{gatePokerRequest,handleAuthApi}from'../worker/auth.js';
import{PlayerAccount}from'../worker/player-account.js';

class MemoryStorage{constructor(){this.map=new Map()}async get(k){return this.map.get(k)}async put(k,v){this.map.set(k,v)}}

test('poker APIs require a Discord account session',async()=>{const gated=await gatePokerRequest(new Request('https://fulltilt.test/api/tables/ABC123',{method:'GET'}),{});assert.equal(gated.response.status,401);assert.match((await gated.response.json()).error,/Discord login required/i)})

test('non poker APIs pass through account gate',async()=>{const req=new Request('https://fulltilt.test/assets/foo.png'),gated=await gatePokerRequest(req,{});assert.equal(gated.response,null);assert.equal(gated.request,req)})

test('Discord login reports missing server configuration cleanly',async()=>{const res=await handleAuthApi(new Request('https://fulltilt.test/api/auth/discord'),{});assert.equal(res.status,503);assert.match((await res.json()).error,/not configured/i)})

test('Discord login preserves a safe direct invite route',async()=>{const env={DISCORD_CLIENT_ID:'client',DISCORD_CLIENT_SECRET:'secret',AUTH_SECRET:'auth'},res=await handleAuthApi(new Request('https://fulltilt.test/api/auth/discord?next=%23%2Ftable%2FABC123%3Ftoken%3Ddo-not-keep'),env);assert.equal(res.status,302);assert.match(res.headers.get('location'),/^https:\/\/discord\.com\/oauth2\/authorize\?/);const cookie=res.headers.get('set-cookie')||'';assert.match(cookie,/ftp_oauth_next/);assert.match(cookie,/%23%2Ftable%2FABC123/);assert.doesNotMatch(cookie,/do-not-keep/)})

test('player accounts persist identity, stats and starter loadout',async()=>{const storage=new MemoryStorage(),account=new PlayerAccount({storage},{}),identity={id:'discord-1',username:'sam',displayName:'Sam',avatar:null};let res=await account.fetch(new Request('https://account.internal/sync',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({identity})})),body=await res.json();assert.equal(res.status,200);assert.equal(body.account.displayName,'Sam');assert.deepEqual(body.account.inventory,['default']);assert.equal(body.account.equipped,'default');assert.equal(body.account.stats.handsPlayed,0);
 res=await account.fetch(new Request('https://account.internal/equip',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({identity,cosmetic:'constellation'})}));assert.equal(res.status,403);body=await res.json();assert.match(body.error,/not in your inventory/i)})

test('lifetime stat checkpoints and tournament results are idempotent',async()=>{const storage=new MemoryStorage(),account=new PlayerAccount({storage},{}),identity={id:'discord-2',username:'player',displayName:'Player',avatar:null};await account.fetch(new Request('https://account.internal/sync',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({identity})}));const checkpoint=stats=>account.fetch(new Request('https://account.internal/stats/checkpoint',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({source:'table:ABC123',stats})}));let res=await checkpoint({handsPlayed:4,knockouts:1,biggestPot:600,chipsWon:900}),body=await res.json();assert.equal(body.account.stats.handsPlayed,4);assert.equal(body.account.stats.knockouts,1);assert.equal(body.account.stats.biggestPot,600);assert.equal(body.account.stats.chipsWon,900);res=await checkpoint({handsPlayed:4,knockouts:1,biggestPot:600,chipsWon:900});body=await res.json();assert.equal(body.account.stats.handsPlayed,4);res=await checkpoint({handsPlayed:6,knockouts:2,biggestPot:450,chipsWon:1200});body=await res.json();assert.equal(body.account.stats.handsPlayed,6);assert.equal(body.account.stats.knockouts,2);assert.equal(body.account.stats.biggestPot,600);assert.equal(body.account.stats.chipsWon,1200);
 const result=()=>account.fetch(new Request('https://account.internal/stats/tournament',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({tournamentCode:'MTT999',finishPlace:1,fieldSize:24})}));res=await result();body=await res.json();assert.equal(body.account.stats.tournamentsPlayed,1);assert.equal(body.account.stats.tournamentWins,1);assert.equal(body.account.stats.finalTables,1);res=await result();body=await res.json();assert.equal(body.account.stats.tournamentsPlayed,1);assert.equal(body.account.stats.tournamentWins,1)})
