import test from'node:test';
import assert from'node:assert/strict';
import{gatePokerRequest,handleAuthApi}from'../worker/auth.js';
import{PlayerAccount}from'../worker/player-account.js';

class MemoryStorage{constructor(){this.map=new Map()}async get(k){return this.map.get(k)}async put(k,v){this.map.set(k,v)}}

test('poker APIs require a Discord account session',async()=>{const gated=await gatePokerRequest(new Request('https://fulltilt.test/api/tables/ABC123',{method:'GET'}),{});assert.equal(gated.response.status,401);assert.match((await gated.response.json()).error,/Discord login required/i)})

test('non poker APIs pass through account gate',async()=>{const req=new Request('https://fulltilt.test/assets/foo.png'),gated=await gatePokerRequest(req,{});assert.equal(gated.response,null);assert.equal(gated.request,req)})

test('Discord login reports missing server configuration cleanly',async()=>{const res=await handleAuthApi(new Request('https://fulltilt.test/api/auth/discord'),{});assert.equal(res.status,503);assert.match((await res.json()).error,/not configured/i)})

test('Discord login preserves a safe direct invite route',async()=>{const env={DISCORD_CLIENT_ID:'client',DISCORD_CLIENT_SECRET:'secret',AUTH_SECRET:'auth'},res=await handleAuthApi(new Request('https://fulltilt.test/api/auth/discord?next=%23%2Ftable%2FABC123%3Ftoken%3Ddo-not-keep'),env);assert.equal(res.status,302);assert.match(res.headers.get('location'),/^https:\/\/discord\.com\/oauth2\/authorize\?/);const cookie=res.headers.get('set-cookie')||'';assert.match(cookie,/ftp_oauth_next/);assert.match(cookie,/%23%2Ftable%2FABC123/);assert.doesNotMatch(cookie,/do-not-keep/)})

test('player accounts persist identity, stats and starter loadout',async()=>{const storage=new MemoryStorage(),account=new PlayerAccount({storage},{}),identity={id:'discord-1',username:'sam',displayName:'Sam',avatar:null};let res=await account.fetch(new Request('https://account.internal/sync',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({identity})})),body=await res.json();assert.equal(res.status,200);assert.equal(body.account.displayName,'Sam');assert.deepEqual(body.account.inventory,['default']);assert.equal(body.account.equipped,'default');assert.equal(body.account.stats.handsPlayed,0);assert.deepEqual(body.account.purchases,[]);
 res=await account.fetch(new Request('https://account.internal/equip',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({identity,cosmetic:'constellation'})}));assert.equal(res.status,403);body=await res.json();assert.match(body.error,/not in your inventory/i)})

test('lifetime stat checkpoints and tournament results are idempotent',async()=>{const storage=new MemoryStorage(),account=new PlayerAccount({storage},{}),identity={id:'discord-2',username:'player',displayName:'Player',avatar:null};await account.fetch(new Request('https://account.internal/sync',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({identity})}));const checkpoint=stats=>account.fetch(new Request('https://account.internal/stats/checkpoint',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({source:'table:ABC123',stats})}));let res=await checkpoint({handsPlayed:4,knockouts:1,biggestPot:600,chipsWon:900}),body=await res.json();assert.equal(body.account.stats.handsPlayed,4);assert.equal(body.account.stats.knockouts,1);assert.equal(body.account.stats.biggestPot,600);assert.equal(body.account.stats.chipsWon,900);res=await checkpoint({handsPlayed:4,knockouts:1,biggestPot:600,chipsWon:900});body=await res.json();assert.equal(body.account.stats.handsPlayed,4);res=await checkpoint({handsPlayed:6,knockouts:2,biggestPot:450,chipsWon:1200});body=await res.json();assert.equal(body.account.stats.handsPlayed,6);assert.equal(body.account.stats.knockouts,2);assert.equal(body.account.stats.biggestPot,600);assert.equal(body.account.stats.chipsWon,1200);
 const result=()=>account.fetch(new Request('https://account.internal/stats/tournament',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({tournamentCode:'MTT999',finishPlace:1,fieldSize:24})}));res=await result();body=await res.json();assert.equal(body.account.stats.tournamentsPlayed,1);assert.equal(body.account.stats.tournamentWins,1);assert.equal(body.account.stats.finalTables,1);res=await result();body=await res.json();assert.equal(body.account.stats.tournamentsPlayed,1);assert.equal(body.account.stats.tournamentWins,1)})

test('Stripe purchase grants unlock a booster exactly once',async()=>{const storage=new MemoryStorage(),account=new PlayerAccount({storage},{}),identity={id:'discord-shop',username:'buyer',displayName:'Buyer',avatar:null};await account.fetch(new Request('https://account.internal/sync',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({identity})}));const grant=()=>account.fetch(new Request('https://account.internal/purchase/grant',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({purchaseKey:'constellation',entitlements:['constellation'],checkoutSessionId:'cs_test_123',paymentIntent:'pi_test_123',amountTotal:299,currency:'usd'})}));let res=await grant(),body=await res.json();assert.equal(res.status,200);assert.deepEqual(body.account.inventory,['default','constellation']);assert.equal(body.account.purchases[0].status,'paid');assert.equal(body.account.purchases[0].purchaseId,'cs_test_123');assert.equal('paymentIntent'in body.account.purchases[0],false);res=await grant();body=await res.json();assert.equal(res.status,200);assert.deepEqual(body.account.inventory,['default','constellation']);res=await account.fetch(new Request('https://account.internal/equip',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({identity,cosmetic:'constellation'})}));body=await res.json();assert.equal(res.status,200);assert.equal(body.account.equipped,'constellation')})

test('Triple Threat purchase grants all three boosters exactly once',async()=>{const storage=new MemoryStorage(),account=new PlayerAccount({storage},{}),identity={id:'discord-bundle',username:'bundlebuyer',displayName:'Bundle Buyer',avatar:null};await account.fetch(new Request('https://account.internal/sync',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({identity})}));const grant=()=>account.fetch(new Request('https://account.internal/purchase/grant',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({purchaseKey:'tripleThreat',entitlements:['constellation','deadMansHand','regalia'],checkoutSessionId:'cs_test_bundle',paymentIntent:'pi_test_bundle',amountTotal:999,currency:'usd'})}));let res=await grant(),body=await res.json();assert.equal(res.status,200);assert.deepEqual(body.account.inventory,['default','constellation','deadMansHand','regalia']);res=await grant();body=await res.json();assert.equal(res.status,200);assert.deepEqual(body.account.inventory,['default','constellation','deadMansHand','regalia']);for(const cosmetic of['constellation','deadMansHand','regalia']){res=await account.fetch(new Request('https://account.internal/equip',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({identity,cosmetic})}));body=await res.json();assert.equal(res.status,200);assert.equal(body.account.equipped,cosmetic)}})

test('refund requests keep access until Stripe confirms and then revoke only unsupported entitlements',async()=>{const storage=new MemoryStorage(),account=new PlayerAccount({storage},{}),identity={id:'discord-refund',username:'refundbuyer',displayName:'Refund Buyer',avatar:null};await account.fetch(new Request('https://account.internal/sync',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({identity})}));const post=(path,body)=>account.fetch(new Request(`https://account.internal${path}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}));await post('/purchase/grant',{purchaseKey:'constellation',entitlements:['constellation'],checkoutSessionId:'cs_single',paymentIntent:'pi_single',amountTotal:499,currency:'usd'});await post('/purchase/grant',{purchaseKey:'tripleThreat',entitlements:['constellation','deadMansHand','regalia'],checkoutSessionId:'cs_bundle',paymentIntent:'pi_bundle',amountTotal:999,currency:'usd'});let res=await post('/purchase/refund-target',{purchaseId:'cs_bundle'}),body=await res.json();assert.equal(res.status,200);assert.equal(body.purchase.paymentIntent,'pi_bundle');assert.equal(body.purchase.amountTotal,999);res=await post('/purchase/refund-requested',{purchaseId:'cs_bundle',refundId:'re_pending'});body=await res.json();assert.equal(body.account.purchases.find(x=>x.purchaseKey==='tripleThreat').status,'refund_pending');assert.deepEqual(body.account.inventory,['default','constellation','deadMansHand','regalia']);res=await post('/equip',{identity,cosmetic:'regalia'});body=await res.json();assert.equal(body.account.equipped,'regalia');res=await post('/purchase/refund',{paymentIntent:'pi_bundle',amountRefunded:999,fullyRefunded:true,refundId:'re_full'});body=await res.json();assert.deepEqual(body.account.inventory,['default','constellation']);assert.equal(body.account.equipped,'default');const bundle=body.account.purchases.find(x=>x.purchaseKey==='tripleThreat'),single=body.account.purchases.find(x=>x.purchaseKey==='constellation');assert.equal(bundle.status,'refunded');assert.equal(bundle.amountRefunded,999);assert.equal(single.status,'paid');res=await post('/purchase/refund',{paymentIntent:'pi_bundle',amountRefunded:999,fullyRefunded:true,refundId:'re_full'});body=await res.json();assert.deepEqual(body.account.inventory,['default','constellation']);assert.equal(body.account.purchases.filter(x=>x.status==='refunded').length,1)})
