import test from'node:test';
import assert from'node:assert/strict';
import{abortActiveHand,endTournamentState}from'../worker/end-game.js';

function player(id,chips,contributed,bet=contributed){return{id,chips,contributed,bet,folded:false,cards:['A♠','K♠'],vpipThisHand:true,pfrThisHand:true}}

test('host end refunds every unresolved committed chip and clears hand state',()=>{const d={started:true,paused:false,players:[player('a',700,300),player('b',800,200)],pot:500,board:['2♠','3♦','4♣'],burned:['9♠'],deck:['T♠'],currentBet:300,openingBet:20,minRaise:100,bigBlind:20,acted:{a:true},actedAtBet:{a:300},fairness:{commitment:'x'},turnDeadline:100,phaseDeadline:null,street:'flop',message:'x'};const before=d.players.reduce((n,p)=>n+p.chips,0)+d.pot;endTournamentState(d,1234);assert.equal(d.players.reduce((n,p)=>n+p.chips,0),before);assert.deepEqual(d.players.map(p=>p.chips),[1000,1000]);assert.equal(d.pot,0);assert.equal(d.currentBet,0);assert.equal(d.openingBet,0);assert.deepEqual(d.board,[]);assert.deepEqual(d.deck,[]);assert.ok(d.players.every(p=>p.contributed===0&&p.bet===0&&p.cards.length===0));assert.equal(d.started,false);assert.equal(d.street,'finished');assert.equal(d.endedByHost,true);assert.equal(d.endedAt,1234);assert.match(d.message,/500 chips returned/) });

test('ending during an already-settled showdown never refunds contributions twice',()=>{const d={started:true,paused:false,players:[player('a',1200,300),player('b',800,200)],pot:0,board:['2♠','3♦','4♣','5♥','6♠'],burned:[],deck:[],currentBet:0,openingBet:0,minRaise:20,bigBlind:20,acted:{},actedAtBet:{},fairness:{commitment:'x'},turnDeadline:null,phaseDeadline:200,street:'showdown',message:'x'};const before=d.players.map(p=>p.chips);endTournamentState(d,1234);assert.deepEqual(d.players.map(p=>p.chips),before);assert.equal(d.pot,0);assert.ok(d.players.every(p=>p.contributed===0));assert.equal(d.phaseDeadline,null);assert.equal(d.street,'finished')});

test('host end rejects a corrupt active-hand pot instead of inventing a reconciliation',()=>{const d={players:[player('a',900,100),player('b',900,100)],pot:199,street:'turn',bigBlind:20};assert.throws(()=>abortActiveHand(d),/Hand abort invariant failed/);assert.deepEqual(d.players.map(p=>p.chips),[900,900])});

test('host end produces a normalized explicit terminal state',()=>{const d={started:true,paused:true,pausedAt:50,turnRemainingMs:9000,phaseRemainingMs:500,turnDeadline:100,phaseDeadline:200,street:'showdown',players:[],pot:0,bigBlind:20,message:'x'};endTournamentState(d,1234);assert.equal(d.started,false);assert.equal(d.paused,false);assert.equal(d.street,'finished');assert.equal(d.endedByHost,true);assert.equal(d.endedAt,1234);assert.equal(d.turnDeadline,null);assert.equal(d.phaseDeadline,null);assert.equal(d.turnRemainingMs,null);assert.equal(d.phaseRemainingMs,null);assert.equal(d.message,'Tournament ended by host.')});
