import test from'node:test';import assert from'node:assert/strict';
import{applyTournamentBlinds,reconcileTournamentRoster,tournamentTableReport}from'../worker/mtt-table-link.js';

test('table snapshots global blinds only at the new-hand boundary',()=>{const d={smallBlind:50,bigBlind:100,minRaise:100,blindLevel:0};const snapshot={clock:{blindLevel:1,smallBlind:75,bigBlind:150,remainingMs:149000},handBlinds:{blindLevel:1,smallBlind:75,bigBlind:150,ante:0}};assert.equal(d.bigBlind,100);assert.equal(applyTournamentBlinds(d,snapshot),true);assert.equal(d.smallBlind,75);assert.equal(d.bigBlind,150);assert.equal(d.minRaise,150);assert.equal(d.blindLevel,1)});

test('table report preserves identity and reports the player due the next big blind',()=>{const report=tournamentTableReport({mttReportGeneration:3,handNumber:12,dealerIndex:0,street:'showdown',lastResult:{finishedAt:123456},players:[{id:'local-a',tournamentPlayerId:'p01',ownershipGeneration:2,tournamentSeat:1,chips:8125,eliminated:false,handStartChips:6000,stats:{handsPlayed:12,handsWon:3},cosmetic:'regalia',sittingOut:true,timeBankMs:45000},{id:'local-b',tournamentPlayerId:'p02',ownershipGeneration:1,tournamentSeat:2,chips:3300,eliminated:false,handStartChips:3300,stats:{handsPlayed:12}}]});assert.equal(report.reportGeneration,3);assert.equal(report.boundarySequence,12);assert.equal(report.handNumber,12);assert.equal(report.completedAt,123456);assert.equal(report.nextBigBlindPlayerId,'p01');assert.equal(report.players[0].id,'p01');assert.equal(report.players[0].ownershipGeneration,2);assert.equal(report.players[0].chips,8125);assert.equal(report.players[0].handStartChips,6000);assert.equal(report.players[0].stats.handsPlayed,12);assert.equal(report.players[0].cosmetic,'regalia');assert.equal(report.players[0].sittingOut,true);assert.equal(report.players[0].timeBankMs,45000);assert.equal(report.players[1].id,'p02');assert.equal(report.players[1].chips,3300)});

test('boundary reconciliation adopts coordinator identity token generation stack seat and stats',()=>{const d={dealerIndex:0,mttMoveNotices:{},players:[{id:'local-b',tournamentPlayerId:'p02',ownershipGeneration:1,token:'old-b',name:'Two',chips:100,host:false,tournamentSeat:2,stats:{handsPlayed:1}},{id:'local-a',tournamentPlayerId:'p01',ownershipGeneration:1,token:'old-a',name:'One',chips:100,host:false,tournamentSeat:1,stats:{handsPlayed:1}}]},snapshot={tableNumber:3,capacity:8,reportGeneration:4,players:[{id:'p01',ownershipGeneration:2,token:'token-one',name:'One',chips:8125,seat:1,moveCount:1,stats:{handsPlayed:7,handsWon:2},cosmetic:'constellation',sittingOut:true,timeBankMs:30000},{id:'p02',ownershipGeneration:1,token:'token-two',name:'Two',chips:3300,seat:2,moveCount:0,stats:{handsPlayed:7,handsWon:1},cosmetic:'regalia'}],moves:[]};const result=reconcileTournamentRoster(d,snapshot);assert.deepEqual(result,{added:[],removed:[],acceptedMoveIds:[],acceptedMoves:[]});assert.equal(d.mttReportGeneration,4);assert.deepEqual(d.players.map(p=>p.tournamentPlayerId),['p01','p02']);assert.deepEqual(d.players.map(p=>p.token),['token-one','token-two']);assert.deepEqual(d.players.map(p=>p.ownershipGeneration),[2,1]);assert.deepEqual(d.players.map(p=>p.chips),[8125,3300]);assert.equal(d.players[0].tournamentSeat,1);assert.equal(d.players[0].stats.handsWon,2);assert.equal(d.players[0].cosmetic,'constellation');assert.equal(d.players[0].sittingOut,true);assert.equal(d.players[0].timeBankMs,30000)});

test('same-name row never reuses a player with a different canonical id',()=>{const old={id:'local-a',tournamentPlayerId:'legacy-p01',ownershipGeneration:1,token:'old',name:'One',chips:100,tournamentSeat:1,stats:{}},d={dealerIndex:0,mttMoveNotices:{},players:[old]},snapshot={tableNumber:1,capacity:8,reportGeneration:1,players:[{id:'p01',ownershipGeneration:1,token:'new',name:'One',chips:100,seat:1,moveCount:0,stats:{}}],moves:[]};const result=reconcileTournamentRoster(d,snapshot);assert.deepEqual(result.added,['p01']);assert.deepEqual(result.removed,['legacy-p01']);assert.notEqual(d.players[0],old);assert.equal(d.players[0].tournamentPlayerId,'p01')});

test('moved-out player is removed only at the boundary and keeps a redirect notice',()=>{const d={dealerIndex:0,mttMoveNotices:{},players:[{id:'a',tournamentPlayerId:'p01',ownershipGeneration:1,token:'tok1',name:'One',chips:2000,tournamentSeat:1,stats:{}},{id:'b',tournamentPlayerId:'p02',ownershipGeneration:1,token:'tok2',name:'Two',chips:3000,tournamentSeat:2,stats:{}}]},snapshot={tableNumber:1,capacity:8,reportGeneration:2,players:[{id:'p02',ownershipGeneration:1,token:'tok2',name:'Two',chips:3000,seat:1,moveCount:0,stats:{}}],moves:[{id:'move-1',kind:'balance',playerId:'p01',playerToken:'tok1',fromTable:1,toTable:2,toTableKey:'ABC-T2',toSeat:null,fromOwnershipGeneration:1,toOwnershipGeneration:2,reason:'Balance',createdAt:100}]};const result=reconcileTournamentRoster(d,snapshot);assert.deepEqual(result.removed,['p01']);assert.deepEqual(d.players.map(p=>p.tournamentPlayerId),['p02']);assert.equal(d.mttMoveNotices.tok1.toTable,2);assert.equal(d.mttMoveNotices.tok1.toSeat,null)});

test('moved-in player from a broken table keeps its preassigned random seat and returns an acknowledgement',()=>{const d={dealerIndex:0,mttMoveNotices:{},players:[{id:'b',tournamentPlayerId:'p02',ownershipGeneration:1,token:'tok2',name:'Two',chips:3000,tournamentSeat:1,stats:{}}]},snapshot={tableNumber:2,capacity:8,reportGeneration:2,players:[{id:'p02',ownershipGeneration:1,token:'tok2',name:'Two',chips:3000,seat:1,moveCount:0,stats:{}},{id:'p03',ownershipGeneration:2,token:'tok3',name:'Three',chips:9876,seat:4,moveCount:2,stats:{handsPlayed:20},cosmetic:'regalia',sittingOut:true,timeBankMs:15000}],moves:[{id:'move-2',kind:'break',playerId:'p03',playerToken:'tok3',fromTable:1,toTable:2,toTableKey:'ABC-T2',toSeat:4,fromOwnershipGeneration:1,toOwnershipGeneration:2,reason:'Break'}]};const result=reconcileTournamentRoster(d,snapshot);assert.deepEqual(result.added,['p03']);assert.deepEqual(result.acceptedMoveIds,['move-2']);assert.deepEqual(result.acceptedMoves,[{id:'move-2',seat:4}]);const moved=d.players.find(p=>p.tournamentPlayerId==='p03');assert.equal(moved.tournamentSeat,4);assert.equal(moved.chips,9876);assert.equal(moved.token,'tok3');assert.equal(moved.ownershipGeneration,2);assert.equal(moved.moveCount,2);assert.equal(moved.stats.handsPlayed,20);assert.equal(moved.cosmetic,'regalia');assert.equal(moved.sittingOut,true);assert.equal(moved.timeBankMs,15000)});

test('balancing player receives the destination worst position at the exact safe boundary',()=>{const existing=[{id:'a',tournamentPlayerId:'p01',ownershipGeneration:1,token:'t1',name:'A',chips:1000,tournamentSeat:1,stats:{}},{id:'b',tournamentPlayerId:'p02',ownershipGeneration:1,token:'t2',name:'B',chips:1000,tournamentSeat:3,stats:{}},{id:'c',tournamentPlayerId:'p03',ownershipGeneration:1,token:'t3',name:'C',chips:1000,tournamentSeat:5,stats:{}},{id:'d',tournamentPlayerId:'p04',ownershipGeneration:1,token:'t4',name:'D',chips:1000,tournamentSeat:7,stats:{}}],d={dealerIndex:0,mttMoveNotices:{},players:existing},snapshot={tableNumber:2,capacity:8,reportGeneration:2,players:[{id:'p01',ownershipGeneration:1,token:'t1',name:'A',chips:1000,seat:1,stats:{}},{id:'p02',ownershipGeneration:1,token:'t2',name:'B',chips:1000,seat:3,stats:{}},{id:'p03',ownershipGeneration:1,token:'t3',name:'C',chips:1000,seat:5,stats:{}},{id:'p04',ownershipGeneration:1,token:'t4',name:'D',chips:1000,seat:7,stats:{}},{id:'p05',ownershipGeneration:2,token:'t5',name:'Mover',chips:1000,seat:null,stats:{}}],moves:[{id:'move-b',kind:'balance',playerId:'p05',playerToken:'t5',fromTable:1,toTable:2,toTableKey:'ABC-T2',toSeat:null,fromOwnershipGeneration:1,toOwnershipGeneration:2,reason:'Balance'}]};const result=reconcileTournamentRoster(d,snapshot),moved=d.players.find(p=>p.tournamentPlayerId==='p05');assert.equal(moved.tournamentSeat,6);assert.deepEqual(result.acceptedMoves,[{id:'move-b',seat:6}]);assert.equal(d.mttMoveNotices.t5.toSeat,6)});
