import test from'node:test';import assert from'node:assert/strict';import{planBalanceMove,planTableBreak,nextTournamentMove,movePlayer}from'../worker/mtt-moves.js';
function tournament(sizes){let n=0;const players=[],tables=sizes.map((size,i)=>{const playerIds=[];for(let seat=1;seat<=size;seat++){const id=`p${++n}`;players.push({id,token:`t${n}`,name:id,chips:2500,eliminated:false,tableNumber:i+1,seat,moveCount:0,ownershipGeneration:1,reportOwnerTable:i+1,pendingMoveId:null});playerIds.push(id)}return{tableNumber:i+1,tableKey:`T-${i+1}`,capacity:8,playerIds,status:'running',nextBigBlindPlayerId:playerIds[Math.min(2,playerIds.length-1)]||null}});return{players,tables,pendingMoves:[],status:'running'}}
function zero(){return 0}

test('8/6 imbalance moves exactly the player due the next big blind and defers the destination seat',()=>{const t=tournament([8,6]),expected=t.tables[0].nextBigBlindPlayerId,move=planBalanceMove(t);assert.equal(move.playerId,expected);assert.equal(move.fromTable,1);assert.equal(move.toTable,2);assert.equal(move.toSeat,null);const applied=movePlayer(t,move),p=t.players.find(x=>x.id===move.playerId);assert.equal(applied.stack,2500);assert.equal(applied.playerToken,p.token);assert.equal(p.seat,null);assert.equal(p.reportOwnerTable,null);assert.equal(t.tables[0].playerIds.length,7);assert.equal(t.tables[1].playerIds.length,7);assert.equal(p.moveCount,1)});
test('balance planning fails closed until the source has a next-big-blind boundary snapshot',()=>{const t=tournament([8,6]);t.tables[0].nextBigBlindPlayerId=null;assert.equal(planBalanceMove(t),null)});
test('balanced tables do not schedule a move',()=>{assert.equal(nextTournamentMove(tournament([8,7,7])),null)});
test('field fitting one fewer table requests a table break',()=>{assert.deepEqual(nextTournamentMove(tournament([7,7,6,6,6,8])),{kind:'break'})});
test('balance move record preserves destination and stack while leaving seating for the destination boundary',()=>{const t=tournament([8,6]),plan=planBalanceMove(t),move=movePlayer(t,plan);assert.equal(move.kind,'balance');assert.equal(move.fromTable,1);assert.equal(move.toTable,2);assert.equal(move.toTableKey,'T-2');assert.equal(move.toSeat,null);assert.equal(move.stack,2500);assert.equal(move.acknowledged,false);assert.equal(t.pendingMoves.length,1)});
test('table break planning is pure, randomized through injected secure-choice semantics, and produces complete seated relocations',()=>{const t=tournament([2,3]),before=structuredClone(t),plan=planTableBreak(t,{randomInt:zero});assert.equal(plan.sourceTable,1);assert.equal(plan.moves.length,2);assert.deepEqual(t,before);assert.ok(plan.moves.every(move=>Number.isInteger(move.toSeat)));for(const move of plan.moves)movePlayer(t,move);assert.equal(t.tables[0].playerIds.length,0);assert.equal(t.tables[1].playerIds.length,5);assert.equal(new Set(t.players.map(p=>`${p.tableNumber}:${p.seat}`)).size,5)});
test('different table-break random draws can produce different player-seat mappings',()=>{const a=planTableBreak(tournament([2,3]),{randomInt:()=>0}),b=planTableBreak(tournament([2,3]),{randomInt:max=>Math.max(0,max-1)});assert.notDeepEqual(a.moves.map(m=>[m.playerId,m.toSeat]),b.moves.map(m=>[m.playerId,m.toSeat]))});
test('a seated move cannot target an occupied destination seat',()=>{const t=tournament([2,2]);assert.throws(()=>movePlayer(t,{playerId:'p1',fromTable:1,toTable:2,toSeat:1,kind:'break'}),/occupied/)});
