import test from'node:test';import assert from'node:assert/strict';
import{applyTournamentBlinds,reconcileTournamentRoster,tournamentTableReport}from'../worker/mtt-table-link.js';

test('table snapshots global blinds only at the new-hand boundary',()=>{const d={smallBlind:50,bigBlind:100,minRaise:100,blindLevel:0};const snapshot={clock:{blindLevel:1,smallBlind:75,bigBlind:150,remainingMs:149000},handBlinds:{blindLevel:1,smallBlind:75,bigBlind:150,ante:0}};assert.equal(d.bigBlind,100);assert.equal(applyTournamentBlinds(d,snapshot),true);assert.equal(d.smallBlind,75);assert.equal(d.bigBlind,150);assert.equal(d.minRaise,150);assert.equal(d.blindLevel,1)});

test('table report preserves tournament identity exact stacks and hand stats',()=>{const report=tournamentTableReport({handNumber:12,street:'showdown',players:[{id:'local-a',tournamentPlayerId:'p01',chips:8125,eliminated:false,handStartChips:6000,stats:{handsPlayed:12,handsWon:3},cosmetic:'regalia'},{id:'local-b',tournamentPlayerId:'p02',chips:0,eliminated:true,finishPlace:41,handStartChips:900,stats:{handsPlayed:12}}]});assert.equal(report.handNumber,12);assert.equal(report.players[0].id,'p01');assert.equal(report.players[0].chips,8125);assert.equal(report.players[0].handStartChips,6000);assert.equal(report.players[0].stats.handsPlayed,12);assert.equal(report.players[0].cosmetic,'regalia');assert.equal(report.players[1].id,'p02');assert.equal(report.players[1].chips,0);assert.equal(report.players[1].finishPlace,41)});

test('boundary reconciliation adopts coordinator identity token stack seat and stats',()=>{const d={dealerIndex:0,mttMoveNotices:{},players:[{id:'local-b',token:'old-b',name:'Two',chips:100,host:false,stats:{handsPlayed:1}},{id:'local-a',token:'old-a',name:'One',chips:100,host:false,stats:{handsPlayed:1}}]},snapshot={tableNumber:3,players:[{id:'p01',token:'token-one',name:'One',chips:8125,seat:1,moveCount:1,stats:{handsPlayed:7,handsWon:2},cosmetic:'constellation'},{id:'p02',token:'token-two',name:'Two',chips:3300,seat:2,moveCount:0,stats:{handsPlayed:7,handsWon:1},cosmetic:'regalia'}],moves:[]};const result=reconcileTournamentRoster(d,snapshot);assert.deepEqual(result,{added:[],removed:[],acceptedMoveIds:[]});assert.deepEqual(d.players.map(p=>p.tournamentPlayerId),['p01','p02']);assert.deepEqual(d.players.map(p=>p.token),['token-one','token-two']);assert.deepEqual(d.players.map(p=>p.chips),[8125,3300]);assert.equal(d.players[0].tournamentSeat,1);assert.equal(d.players[0].stats.handsWon,2);assert.equal(d.players[0].cosmetic,'constellation')});

test('moved-out player is removed only at the boundary and keeps a redirect notice',()=>{const d={dealerIndex:0,mttMoveNotices:{},players:[{id:'a',tournamentPlayerId:'p01',token:'tok1',name:'One',chips:2000,stats:{}},{id:'b',tournamentPlayerId:'p02',token:'tok2',name:'Two',chips:3000,stats:{}}]},snapshot={tableNumber:1,players:[{id:'p02',token:'tok2',name:'Two',chips:3000,seat:1,moveCount:0,stats:{}}],moves:[{id:'move-1',kind:'balance',playerId:'p01',playerToken:'tok1',fromTable:1,toTable:2,toTableKey:'ABC-T2',toSeat:7,reason:'Balance',createdAt:100}]};const result=reconcileTournamentRoster(d,snapshot);assert.deepEqual(result.removed,['p01']);assert.deepEqual(d.players.map(p=>p.tournamentPlayerId),['p02']);assert.equal(d.mttMoveNotices.tok1.toTable,2);assert.equal(d.mttMoveNotices.tok1.toSeat,7)});

test('moved-in player is created with exact stack and returns an acknowledgement id',()=>{const d={dealerIndex:0,mttMoveNotices:{},players:[{id:'b',tournamentPlayerId:'p02',token:'tok2',name:'Two',chips:3000,stats:{}}]},snapshot={tableNumber:2,players:[{id:'p02',token:'tok2',name:'Two',chips:3000,seat:1,moveCount:0,stats:{}},{id:'p03',token:'tok3',name:'Three',chips:9876,seat:2,moveCount:2,stats:{handsPlayed:20},cosmetic:'regalia'}],moves:[{id:'move-2',kind:'break',playerId:'p03',playerToken:'tok3',fromTable:1,toTable:2,toTableKey:'ABC-T2',toSeat:2,reason:'Break'}]};const result=reconcileTournamentRoster(d,snapshot);assert.deepEqual(result.added,['p03']);assert.deepEqual(result.acceptedMoveIds,['move-2']);const moved=d.players.find(p=>p.tournamentPlayerId==='p03');assert.equal(moved.chips,9876);assert.equal(moved.token,'tok3');assert.equal(moved.moveCount,2);assert.equal(moved.stats.handsPlayed,20);assert.equal(moved.cosmetic,'regalia')});
