import test from'node:test';
import assert from'node:assert/strict';
import{PokerTable}from'../worker/app.js';

class MemoryStorage{constructor(){this.map=new Map()}async get(k){return this.map.get(k)}async put(k,v){this.map.set(k,structuredClone(v))}async delete(k){this.map.delete(k)}async setAlarm(){}async deleteAlarm(){}}
function harness(){const deliveries=[],storage=new MemoryStorage(),state={storage,getWebSockets:()=>[]},env={ACCOUNTS:{idFromName:x=>String(x),get:accountId=>({fetch:async req=>{deliveries.push({accountId:String(accountId),path:new URL(req.url).pathname,body:await req.json()});return Response.json({ok:true})}})}};return{table:new PokerTable(state,env),deliveries}}
async function post(table,path,body){return table.fetch(new Request(`https://table${path}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}))}

test('second human at a quick table sends one table-ready event to the host',async()=>{const h=harness();let r=await post(h.table,'/init',{code:'ABC123',hostName:'Host',accountId:'host-account',startingChips:2500,blindMinutes:10,blindStructure:[[10,20],[20,40]]});assert.equal(r.status,200);r=await post(h.table,'/join',{name:'Guest One',accountId:'guest-1'});assert.equal(r.status,200);assert.equal(h.deliveries.length,1);assert.equal(h.deliveries[0].accountId,'host-account');assert.equal(h.deliveries[0].path,'/notifications/enqueue');assert.equal(h.deliveries[0].body.event.kind,'table-ready');assert.equal(h.deliveries[0].body.event.code,'ABC123');assert.equal(h.deliveries[0].body.event.playerCount,2)});

test('later quick-table joins send player-joined instead of another table-ready event',async()=>{const h=harness();await post(h.table,'/init',{code:'ABC123',hostName:'Host',accountId:'host-account',startingChips:2500,blindMinutes:10,blindStructure:[[10,20],[20,40]]});await post(h.table,'/join',{name:'Guest One',accountId:'guest-1'});await post(h.table,'/join',{name:'Guest Two',accountId:'guest-2'});assert.equal(h.deliveries.length,2);assert.equal(h.deliveries[0].body.event.kind,'table-ready');assert.equal(h.deliveries[1].body.event.kind,'player-joined');assert.equal(h.deliveries[1].body.event.playerName,'Guest Two');assert.equal(h.deliveries[1].body.event.playerCount,3)});


test('turn reminder fires once for the current quick-table turn and re-arms timeout',async()=>{const h=harness();const alarms=[];h.table.state.storage.setAlarm=async at=>{alarms.push(at)};await post(h.table,'/init',{code:'ABC123',hostName:'Host',accountId:'host-account',startingChips:2500,blindMinutes:10,blindStructure:[[10,20],[20,40]]});await post(h.table,'/join',{name:'Guest One',accountId:'guest-1'});const host=h.table.data.players.find(p=>p.host);await post(h.table,'/action',{token:host.token,type:'start'});const current=h.table.data.players[h.table.data.turnIndex],serial=h.table.data.turnSerial,deadline=h.table.data.turnDeadline,reminderAt=h.table.data.turnReminderAt;assert.ok(current.accountId);assert.equal(serial>0,true);assert.ok(reminderAt<deadline);assert.ok(deadline-reminderAt>=5000);const before=h.deliveries.length;assert.equal(await h.table.sendTurnReminderIfDue(reminderAt),true);assert.equal(h.deliveries.length,before+1);const event=h.deliveries.at(-1).body.event;assert.equal(event.kind,'turn-reminder');assert.equal(event.code,'ABC123');assert.equal(event.playerId,current.id);assert.equal(await h.table.sendTurnReminderIfDue(reminderAt+1),false);assert.equal(h.table.data.turnReminderSentSerial,serial);assert.ok(alarms.includes(deadline))});

test('acting before reminder advances the turn serial and prevents stale reminder delivery',async()=>{const h=harness();await post(h.table,'/init',{code:'ABC123',hostName:'Host',accountId:'host-account',startingChips:2500,blindMinutes:10,blindStructure:[[10,20],[20,40]]});await post(h.table,'/join',{name:'Guest One',accountId:'guest-1'});const host=h.table.data.players.find(p=>p.host);await post(h.table,'/action',{token:host.token,type:'start'});const oldSerial=h.table.data.turnSerial,oldReminder=h.table.data.turnReminderAt,current=h.table.data.players[h.table.data.turnIndex];await post(h.table,'/action',{token:current.token,type:h.table.toCall(current)>0?'call':'check'});assert.notEqual(h.table.data.turnSerial,oldSerial);assert.notEqual(h.table.data.turnReminderAt,oldReminder);const count=h.deliveries.filter(x=>x.body.event?.kind==='turn-reminder').length;assert.equal(count,0)});
