import test from'node:test';
import assert from'node:assert/strict';
import{reconcileSessionRoute,safeSessionHash,tournamentSessionToken}from'../src/session.js';

function storage(seed={}){const map=new Map(Object.entries(seed));return{get length(){return map.size},key:i=>[...map.keys()][i]??null,getItem:k=>map.has(k)?map.get(k):null,setItem:(k,v)=>map.set(k,String(v)),removeItem:k=>map.delete(k)}}
function withBrowser({hash,seed={}},fn){const old={location:Object.getOwnPropertyDescriptor(globalThis,'location'),history:Object.getOwnPropertyDescriptor(globalThis,'history'),localStorage:Object.getOwnPropertyDescriptor(globalThis,'localStorage')},store=storage(seed),location={hash,pathname:'/poker',search:'?theme=dark'},calls=[];Object.defineProperty(globalThis,'localStorage',{value:store,configurable:true});Object.defineProperty(globalThis,'location',{value:location,configurable:true,writable:true});Object.defineProperty(globalThis,'history',{value:{state:{route:'test'},replaceState(state,title,url){calls.push({state,title,url});const i=url.indexOf('#');location.hash=i>=0?url.slice(i):''}},configurable:true});try{return fn({store,location,calls})}finally{for(const[k,d]of Object.entries(old)){if(d)Object.defineProperty(globalThis,k,d);else delete globalThis[k]}}}

test('safe session hash removes only the token parameter',()=>{assert.equal(safeSessionHash('#/table/ABC123?token=secret&view=compact'),'#/table/ABC123?view=compact');assert.equal(safeSessionHash('#/tournament/ABC123?view=compact&token=secret'),'#/tournament/ABC123?view=compact');assert.equal(safeSessionHash('#/table/ABC123?view=compact'),'#/table/ABC123?view=compact');assert.equal(safeSessionHash('#/table/ABC123?token=secret'),'#/table/ABC123')});

test('legacy tournament token links are imported then scrubbed before the app renders',()=>withBrowser({hash:'#/tournament/ABC123?token=topsecret&view=compact'},({location,calls})=>{reconcileSessionRoute();assert.equal(tournamentSessionToken('ABC123'),'topsecret');assert.equal(location.hash,'#/tournament/ABC123?view=compact');assert.equal(calls.length,1);assert.equal(calls[0].url,'/poker?theme=dark#/tournament/ABC123?view=compact');assert.equal(calls[0].url.includes('topsecret'),false)}));

test('legacy spectator links keep spectator role while the address bar token is scrubbed',()=>withBrowser({hash:'#/table/ABC123?token=railsecret',seed:{ftp_session_role_ABC123:'spectator'}},({store,location})=>{reconcileSessionRoute();assert.equal(store.getItem('ftp_session_ABC123'),'railsecret');assert.equal(store.getItem('ftp_spectator_session_ABC123'),'railsecret');assert.equal(store.getItem('ftp_session_role_ABC123'),'spectator');assert.equal(location.hash,'#/table/ABC123')}));
