import test from'node:test';import assert from'node:assert/strict';import{settleShowdown,visibleCards}from'../worker/showdown.js';
const board=['2♠','3♦','4♣','5♥','9♠'];
function sumMap(map){return[...map.values()].reduce((a,b)=>a+b,0)}
test('showdown refuses any live-pot mismatch before awards are applied',()=>{const players=[{id:'a',name:'A',cards:['A♠','K♠'],folded:false,contributed:50},{id:'b',name:'B',cards:['Q♠','J♠'],folded:false,contributed:50}];assert.throws(()=>settleShowdown({players,board,dealerIndex:0,pot:101}),/Pot accounting invariant failed/)});
test('showdown settlement conserves exact live pot',()=>{const players=[{id:'a',name:'A',cards:['A♠','K♠'],folded:false,contributed:50},{id:'b',name:'B',cards:['Q♠','J♠'],folded:false,contributed:50}];const r=settleShowdown({players,board,dealerIndex:0,pot:100});assert.equal(r.total,100);assert.equal(sumMap(r.awards)+sumMap(r.returns),100)});
test('odd chip goes to first tied winner left of dealer',()=>{const tieBoard=['A♠','K♦','Q♣','J♥','2♠'],players=[{id:'a',name:'A',cards:['T♠','3♠'],folded:false,contributed:33},{id:'b',name:'B',cards:['T♦','4♦'],folded:false,contributed:33},{id:'c',name:'C',cards:['9♣','9♦'],folded:false,contributed:33}];const r=settleShowdown({players,board:tieBoard,dealerIndex:0,pot:99});assert.equal(r.awards.get('a'),49);assert.equal(r.awards.get('b'),50);assert.deepEqual(r.pots[0].winnerIds,['b','a']);assert.equal(sumMap(r.awards),99);assert.ok([...r.awards.values()].every(Number.isInteger))});
test('uncalled excess is returned separately from contested pot awards',()=>{const players=[{id:'a',name:'A',cards:['A♠','A♥'],folded:false,contributed:1000},{id:'b',name:'B',cards:['K♠','K♥'],folded:false,contributed:100}];const r=settleShowdown({players,board:['2♣','3♦','7♠','8♥','9♣'],dealerIndex:0,pot:1100});assert.deepEqual(r.pots.map(p=>p.amount),[200]);assert.equal(r.contestedTotal,200);assert.equal(r.returnedTotal,900);assert.equal(r.awards.get('a'),200);assert.equal(r.returns.get('a'),900);assert.equal(r.total,1100)});
test('live-pot showdown applies awards and uncalled returns exactly once',()=>{const players=[{id:'a',name:'A',chips:0,cards:['A♠','A♥'],folded:false,contributed:1000},{id:'b',name:'B',chips:0,cards:['K♠','K♥'],folded:false,contributed:100}];const r=settleShowdown({players,board:['2♣','3♦','7♠','8♥','9♣'],dealerIndex:0,livePot:1100,fairness:{verified:true}});assert.equal(players[0].chips,1100);assert.equal(players[1].chips,0);assert.equal(r.settledPot,1100);assert.equal(r.contestedPot,200);assert.equal(r.returnedTotal,900);assert.deepEqual(r.returns,[{playerId:'a',amount:900,name:'A'}])});
test('opponents expose exactly two hidden placeholders during a live hand',()=>{const p={id:'a',token:'secret',cards:['A♠','K♠']};assert.deepEqual(visibleCards({player:p,viewerToken:'other-player',street:'turn',lastResult:null}),['',''])});
test('uncontested winner stays hidden from spectators at showdown',()=>{const p={id:'a',token:'secret',cards:['A♠','K♠']};assert.deepEqual(visibleCards({player:p,viewerToken:'rail',street:'showdown',lastResult:{revealed:[]}}),['',''])});
test('explicitly revealed player is visible at showdown',()=>{const p={id:'a',token:'secret',cards:['A♠','K♠']};assert.deepEqual(visibleCards({player:p,viewerToken:'rail',street:'showdown',lastResult:{revealed:[{playerId:'a'}]}}),['A♠','K♠'])});
test('player always sees their own cards',()=>{const p={id:'a',token:'secret',cards:['A♠','K♠']};assert.deepEqual(visibleCards({player:p,viewerToken:'secret',street:'turn',lastResult:null}),['A♠','K♠'])});
