import test from'node:test';import assert from'node:assert/strict';import{settleShowdown,visibleCards}from'../worker/showdown.js';
const board=['2♠','3♦','4♣','5♥','9♠'];
test('showdown refuses any live-pot mismatch before awards are applied',()=>{const players=[{id:'a',name:'A',cards:['A♠','K♠'],folded:false,contributed:50},{id:'b',name:'B',cards:['Q♠','J♠'],folded:false,contributed:50}];assert.throws(()=>settleShowdown({players,board,dealerIndex:0,pot:101}),/Pot accounting invariant failed/)});
test('showdown settlement conserves exact live pot',()=>{const players=[{id:'a',name:'A',cards:['A♠','K♠'],folded:false,contributed:50},{id:'b',name:'B',cards:['Q♠','J♠'],folded:false,contributed:50}];const r=settleShowdown({players,board,dealerIndex:0,pot:100});assert.equal(r.total,100);assert.equal([...r.awards.values()].reduce((a,b)=>a+b,0),100)});
test('odd chip split is exact and never displayed as a fractional award',()=>{const tieBoard=['A♠','K♦','Q♣','J♥','2♠'],players=[{id:'a',name:'A',cards:['T♠','3♠'],folded:false,contributed:33},{id:'b',name:'B',cards:['T♦','4♦'],folded:false,contributed:33},{id:'c',name:'C',cards:['9♣','9♦'],folded:false,contributed:33}];const r=settleShowdown({players,board:tieBoard,dealerIndex:0,pot:99}),amounts=[...r.awards.values()].sort((a,b)=>a-b);assert.deepEqual(amounts,[49,50]);assert.equal(amounts.reduce((a,b)=>a+b,0),99);assert.ok(amounts.every(Number.isInteger))});
test('opponents expose exactly two hidden placeholders during a live hand',()=>{const p={id:'a',token:'secret',cards:['A♠','K♠']};assert.deepEqual(visibleCards({player:p,viewerToken:'other-player',street:'turn',lastResult:null}),['',''])});
test('uncontested winner stays hidden from spectators at showdown',()=>{const p={id:'a',token:'secret',cards:['A♠','K♠']};assert.deepEqual(visibleCards({player:p,viewerToken:'rail',street:'showdown',lastResult:{revealed:[]}}),['',''])});
test('explicitly revealed player is visible at showdown',()=>{const p={id:'a',token:'secret',cards:['A♠','K♠']};assert.deepEqual(visibleCards({player:p,viewerToken:'rail',street:'showdown',lastResult:{revealed:[{playerId:'a'}]}}),['A♠','K♠'])});
test('player always sees their own cards',()=>{const p={id:'a',token:'secret',cards:['A♠','K♠']};assert.deepEqual(visibleCards({player:p,viewerToken:'secret',street:'turn',lastResult:null}),['A♠','K♠'])});
