import test from'node:test';
import assert from'node:assert/strict';
import{sendTelegramTournamentNotification,sendTelegramNotificationToTarget,telegramNotificationPayload,tournamentNotificationPayload,normalizedNotificationPreferences}from'../worker/telegram-notifications.js';

function envWithTarget(notifications={}){const target={fetch:async()=>Response.json({telegram:{chatId:'99887766',username:'samtelegram',displayName:'Sam'},notifications})};return{TELEGRAM_BOT_TOKEN:'123456:test-token',TELEGRAM_BOT_USERNAME:'CrashoutPokerBot',ACCOUNTS:{idFromName:x=>x,get:()=>target}}}

test('tournament start notification uses Crashout branding and returns to the same Mini App',()=>{const p=tournamentNotificationPayload({TELEGRAM_BOT_USERNAME:'CrashoutPokerBot'},{kind:'tournament-start',code:'abc123',tableNumber:2,seat:6});assert.match(p.text,/CRASHOUT POKER TOURNAMENT/);assert.match(p.text,/ABC123/);assert.match(p.text,/Table 2 • Seat 6/);assert.equal(p.buttonText,'OPEN TOURNAMENT');assert.equal(p.url,'https://t.me/CrashoutPokerBot?startapp=tournament_ABC123')});

test('table move notification uses the final acknowledged table and seat',()=>{const p=tournamentNotificationPayload({TELEGRAM_BOT_USERNAME:'CrashoutPokerBot'},{kind:'table-move',code:'move01',toTable:4,toSeat:7});assert.match(p.text,/Table 4 • Seat 7/);assert.equal(p.buttonText,'OPEN NEW TABLE');assert.equal(p.url,'https://t.me/CrashoutPokerBot?startapp=tournament_MOVE01')});

test('result, table-ready and player-joined messages deep-link to the correct game',()=>{const env={TELEGRAM_BOT_USERNAME:'CrashoutPokerBot'},result=telegramNotificationPayload(env,{kind:'tournament-result',code:'win001',finishPlace:3,fieldSize:18}),ready=telegramNotificationPayload(env,{kind:'table-ready',code:'tab123',playerCount:2}),joined=telegramNotificationPayload(env,{kind:'player-joined',code:'tab123',playerName:'Ruby',playerCount:4});assert.match(result.text,/3rd of 18/);assert.equal(result.url,'https://t.me/CrashoutPokerBot?startapp=tournament_WIN001');assert.match(ready.text,/enough players/i);assert.equal(ready.url,'https://t.me/CrashoutPokerBot?startapp=table_TAB123');assert.match(joined.text,/Ruby joined/);assert.equal(joined.url,'https://t.me/CrashoutPokerBot?startapp=table_TAB123')});

test('sender resolves linked Telegram chat and posts an inline open button',async()=>{const env=envWithTarget(),calls=[],fetchImpl=async(url,init)=>{calls.push({url,body:JSON.parse(init.body)});return Response.json({ok:true,result:{message_id:1}})};const result=await sendTelegramTournamentNotification(env,'discord-account',{kind:'tournament-start',code:'ABC123',tableNumber:1,seat:3},fetchImpl);assert.equal(result.sent,true);assert.equal(result.chatId,'99887766');assert.equal(calls.length,1);assert.equal(calls[0].url,'https://api.telegram.org/bot123456:test-token/sendMessage');assert.equal(calls[0].body.chat_id,'99887766');assert.equal(calls[0].body.reply_markup.inline_keyboard[0][0].url,'https://t.me/CrashoutPokerBot?startapp=tournament_ABC123')});

test('disabled notification preference suppresses delivery without retry',async()=>{const env=envWithTarget({playerJoined:false}),calls=[];const result=await sendTelegramTournamentNotification(env,'acct',{kind:'player-joined',code:'ABC123',playerName:'Sam',playerCount:3},async(...args)=>{calls.push(args);return Response.json({ok:true})});assert.equal(result.sent,false);assert.equal(result.retryable,false);assert.equal(result.reason,'disabled');assert.equal(calls.length,0);assert.equal(normalizedNotificationPreferences({turnReminder:true}).turnReminder,true);assert.equal(normalizedNotificationPreferences({}).turnReminder,false)});

test('direct target sender honors preferences before Telegram fetch',async()=>{let called=false;const result=await sendTelegramNotificationToTarget(envWithTarget(),{chatId:'99887766',preferences:{tournamentResult:false}},{kind:'tournament-result',code:'ABC123',finishPlace:2,fieldSize:8},async()=>{called=true;return Response.json({ok:true})});assert.equal(result.reason,'disabled');assert.equal(called,false)});

test('Telegram rate limit is retryable while blocked bot is terminal',async()=>{const env=envWithTarget(),limited=await sendTelegramTournamentNotification(env,'acct',{kind:'table-move',code:'ABC123',toTable:2,toSeat:5},async()=>new Response(JSON.stringify({ok:false,description:'Too Many Requests'}),{status:429,headers:{'content-type':'application/json'}}));assert.equal(limited.sent,false);assert.equal(limited.retryable,true);const blocked=await sendTelegramTournamentNotification(env,'acct',{kind:'table-move',code:'ABC123',toTable:2,toSeat:5},async()=>new Response(JSON.stringify({ok:false,description:'Forbidden: bot was blocked by the user'}),{status:403,headers:{'content-type':'application/json'}}));assert.equal(blocked.sent,false);assert.equal(blocked.retryable,false)});

test('missing Telegram configuration or account target never throws into poker',async()=>{let r=await sendTelegramTournamentNotification({},'acct',{kind:'tournament-start',code:'ABC123',tableNumber:1,seat:1},async()=>{throw Error('should not fetch')});assert.equal(r.sent,false);assert.equal(r.reason,'no-telegram-target');const env={...envWithTarget(),ACCOUNTS:{idFromName:x=>x,get:()=>({fetch:async()=>Response.json({telegram:null})})}};r=await sendTelegramTournamentNotification(env,'acct',{kind:'tournament-start',code:'ABC123',tableNumber:1,seat:1},async()=>{throw Error('should not fetch')});assert.equal(r.sent,false);assert.equal(r.reason,'no-telegram-target')});


test('turn reminders deep-link quick tables and tournaments to the correct Mini App route',()=>{const env={TELEGRAM_BOT_USERNAME:'CrashoutPokerBot'},quick=telegramNotificationPayload(env,{kind:'turn-reminder',code:'ABC123'}),mtt=telegramNotificationPayload(env,{kind:'turn-reminder',code:'MTT999',tournamentCode:'MTT999',tableNumber:3});assert.equal(quick.buttonText,'OPEN TABLE');assert.equal(quick.url,'https://t.me/CrashoutPokerBot?startapp=table_ABC123');assert.equal(mtt.buttonText,'OPEN TOURNAMENT');assert.equal(mtt.url,'https://t.me/CrashoutPokerBot?startapp=tournament_MTT999');assert.match(mtt.text,/Table 3/)});
