import baseWorker,{PokerTable as BasePokerTable}from'./index.js';
import{secureInt}from'./fairness.js';
import{DEFAULT_BLINDS,normalizeBlindStructure}from'./tournament.js';
const CHAT_LIMIT=100,SPECTATOR_LIMIT=100,ACTION_LOG_LIMIT=80;
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json','cache-control':'no-store'}})}
function token(n=20){const a='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let s='';for(let i=0;i<n;i++)s+=a[secureInt(a.length)];return s}
function cleanName(v){return String(v||'').trim().replace(/\s+/g,' ').slice(0,24)}
function cleanMessage(v){return String(v||'').trim().replace(/[\u0000-\u001f\u007f]/g,'').slice(0,280)}
export default{async fetch(req,env){const u=new URL(req.url);if(u.pathname==='/api/health')return json({ok:true,name:'FULL TILT POKER',version:'0.11.0',realtime:'websocket-hibernation',engine:'custom-blinds-action-log-fair-csprng',spectators:'read-only',chat:'realtime',presentation:'animated-table-fx-web-audio'});const m=u.pathname.match(/^\/api\/tables\/([A-Z0-9]{6})\/(spectate|chat)$/);if(m){const stub=env.TABLES.get(env.TABLES.idFromName(m[1]));return stub.fetch(new Request(`https://table/${m[2]}`,{method:req.method,headers:req.headers,body:req.method==='GET'?undefined:req.body,duplex:req.body?'half':undefined}))}return baseWorker.fetch(req,env)}};
export class PokerTable extends BasePokerTable{
async load(){await super.load();if(!this.data)return;this.data.spectators??=[];this.data.chat??=[];this.data.blindStructure??=DEFAULT_BLINDS.map(x=>[...x]);this.data.actionLog??=[]}
viewer(tokenValue){const player=this.data.players.find(p=>p.token===tokenValue);if(player)return{type:'player',id:player.id,name:player.name,token:player.token};const spectator=this.data.spectators?.find(s=>s.token===tokenValue);if(spectator)return{type:'spectator',id:spectator.id,name:spectator.name,token:spectator.token};return null}
logAction(entry){if(!this.data)return;this.data.actionLog??=[];this.data.actionLog.push({id:token(10),at:Date.now(),handNumber:this.data.handNumber||0,street:this.data.street,...entry});this.data.actionLog=this.data.actionLog.slice(-ACTION_LOG_LIMIT)}
public(tokenValue){const state=super.public(tokenValue),viewer=this.viewer(tokenValue);return{...state,viewer:viewer?{type:viewer.type,id:viewer.id,name:viewer.name}:null,spectatorCount:this.data.spectators?.length||0,chat:(this.data.chat||[]).slice(-CHAT_LIMIT),blindStructure:(this.data.blindStructure||DEFAULT_BLINDS).map(x=>[...x]),actionLog:(this.data.actionLog||[]).slice(-40)}}
tickBlinds(){const d=this.data;if(!d.started||d.paused||!d.levelStartedAt)return false;const levels=d.blindStructure||DEFAULT_BLINDS,duration=d.blindMinutes*60000,passed=Date.now()-d.levelStartedAt;if(passed>=duration){const jumps=Math.floor(passed/duration),old=d.blindLevel;d.blindLevel=Math.min(levels.length-1,d.blindLevel+jumps);[d.smallBlind,d.bigBlind]=levels[d.blindLevel];d.levelStartedAt+=jumps*duration;if(d.blindLevel!==old){d.message=`Blind level advanced to ${d.smallBlind}/${d.bigBlind}. New blinds post next hand.`;this.logAction({type:'blinds',text:`Blinds advanced to ${d.smallBlind}/${d.bigBlind}`});return true}}return false}
newHand(){const oldHand=this.data?.handNumber||0;super.newHand();if(this.data?.handNumber!==oldHand){this.data.actionLog=[];this.logAction({type:'hand',text:`Hand #${this.data.handNumber} started • blinds ${this.data.smallBlind}/${this.data.bigBlind}`})}}
act(p,type,amount){const d=this.data,beforeBet=p.bet,beforeCurrent=d.currentBet,toCall=Math.max(0,d.currentBet-p.bet),street=d.street;super.act(p,type,amount);let text;if(type==='fold')text=`${p.name} folded`;else if(type==='check')text=`${p.name} checked`;else if(type==='call')text=`${p.name} called ${Math.min(toCall,beforeBet+p.chips+toCall).toLocaleString()}`;else if(type==='raise')text=`${p.name} raised to ${Math.max(beforeCurrent,p.bet).toLocaleString()}`;else if(type==='allin')text=`${p.name} went all-in${p.bet>beforeBet?` to ${p.bet.toLocaleString()}`:''}`;if(text)this.logAction({type,text,playerId:p.id,street})}
async fetch(req){await this.load();const u=new URL(req.url);if(!this.data&&u.pathname!=='/init')return json({error:'Table not found.'},404);if(u.pathname==='/init'&&req.method==='POST'){const b=await req.clone().json();let structure;try{structure=normalizeBlindStructure(b.blindStructure)}catch(e){return json({error:e.message},400)}const response=await super.fetch(req);if(response.ok&&this.data){this.data.blindStructure=structure;this.data.blindLevel=0;[this.data.smallBlind,this.data.bigBlind]=structure[0];this.data.minRaise=this.data.bigBlind;this.data.actionLog=[];await this.save()}return response}if(u.pathname==='/spectate'&&req.method==='POST'){const b=await req.json(),name=cleanName(b.name);if(!name)return json({error:'Display name required.'},400);if((this.data.spectators?.length||0)>=SPECTATOR_LIMIT)return json({error:'Spectator room is full.'},409);if(this.data.players.some(p=>p.name.toLowerCase()===name.toLowerCase())||this.data.spectators.some(s=>s.name.toLowerCase()===name.toLowerCase()))return json({error:'That display name is already in use.'},409);const s={id:token(12),token:token(20),name,joinedAt:Date.now()};this.data.spectators.push(s);this.data.chat.push({id:token(10),type:'system',name:'TABLE',message:`${name} is watching.`,at:Date.now()});this.data.chat=this.data.chat.slice(-CHAT_LIMIT);await this.save();this.broadcast();return json({code:this.data.code,token:s.token,viewer:'spectator'})}if(u.pathname==='/chat'&&req.method==='POST'){const b=await req.json(),viewer=this.viewer(String(b.token||''));if(!viewer)return json({error:'Invalid table session.'},403);const message=cleanMessage(b.message);if(!message)return json({error:'Message required.'},400);const now=Date.now(),last=(this.data.chat||[]).filter(m=>m.senderId===viewer.id).at(-1);if(last&&now-last.at<700)return json({error:'Slow down.'},429);this.data.chat.push({id:token(10),type:'message',senderId:viewer.id,viewerType:viewer.type,name:viewer.name,message,at:now});this.data.chat=this.data.chat.slice(-CHAT_LIMIT);await this.save();this.broadcast();return json({ok:true})}return super.fetch(req)}
}
