import baseWorker,{PokerTable as BasePokerTable}from'./index.js';
import{secureInt}from'./fairness.js';
import{DEFAULT_BLINDS,normalizeBlindStructure}from'./tournament.js';
import{showdownExpired}from'./lifecycle.js';
import{handAwards,knockoutCredits,cleanKnockoutCount}from'./stats.js';
import{actionLogText}from'./action-log.js';
import{settleShowdown,visibleCards}from'./showdown.js';
import{handStrengthLabel}from'./poker-eval.js';
import{livePots}from'./live-pots.js';
import{chooseTestBotAction,nextTestBotName}from'./test-bot.js';
const CHAT_LIMIT=100,SPECTATOR_LIMIT=100,ACTION_LOG_LIMIT=80,CODE_RETRIES=8;
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json','cache-control':'no-store'}})}
function token(n=20){const a='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let s='';for(let i=0;i<n;i++)s+=a[secureInt(a.length)];return s}
function tableCode(){return token(6)}
function cleanName(v){return String(v||'').trim().replace(/\s+/g,' ').slice(0,24)}
function cleanMessage(v){return String(v||'').trim().replace(/[\u0000-\u001f\u007f]/g,'').slice(0,280)}
function botStats(){return{handsPlayed:0,handsWon:0,vpipHands:0,pfrHands:0,biggestPotWon:0,knockouts:0}}
export default{async fetch(req,env){const u=new URL(req.url);if(u.pathname==='/api/health')return json({ok:true,name:'FULL TILT POKER',version:'0.35.0',realtime:'websocket-hibernation',engine:'disposable-test-bots-hardened-live-pot-accounting-server-hand-strength-componentized-table-surface-lobby-panels-extracted-table-transport-explicit-session-api-frontend-state-owned-tournament-edge-heads-up-single-lifecycle-strict-showdown-precise-action-log-stats-fair-csprng',spectators:'read-only',chat:'realtime',presentation:'animated-table-fx-web-audio'});if(u.pathname==='/api/tables'&&req.method==='POST'){let body;try{body=await req.json()}catch{return json({error:'Invalid table configuration.'},400)}for(let attempt=0;attempt<CODE_RETRIES;attempt++){const code=tableCode(),stub=env.TABLES.get(env.TABLES.idFromName(code)),response=await stub.fetch(new Request('https://table/init',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...body,code})}));if(response.status!==409)return response}return json({error:'Could not allocate a unique table code. Try again.'},503)}const m=u.pathname.match(/^\/api\/tables\/([A-Z0-9]{6})\/(spectate|chat)$/);if(m){const stub=env.TABLES.get(env.TABLES.idFromName(m[1]));return stub.fetch(new Request(`https://table/${m[2]}`,{method:req.method,headers:req.headers,body:req.method==='GET'?undefined:req.body,duplex:req.body?'half':undefined}))}return baseWorker.fetch(req,env)}};
export class PokerTable extends BasePokerTable{
async load(){await super.load();if(!this.data)return;this.data.spectators??=[];this.data.chat??=[];this.data.blindStructure??=DEFAULT_BLINDS.map(x=>[...x]);this.data.actionLog??=[]}
async alarm(){await this.load();if(!this.data)return;let changed=false;const d=this.data;if(showdownExpired(d)){d.phaseDeadline=null;this.newHand();changed=true}else if(this.handleTurnTimeout())changed=true;if(this.tickBlinds())changed=true;this.driveTestBots();await this.save();if(changed)this.broadcast()}
viewer(tokenValue){const player=this.data.players.find(p=>p.token===tokenValue);if(player)return{type:'player',id:player.id,name:player.name,token:player.token};const spectator=this.data.spectators?.find(s=>s.token===tokenValue);if(spectator)return{type:'spectator',id:spectator.id,name:spectator.name,token:spectator.token};return null}
logAction(entry){if(!this.data)return;this.data.actionLog??=[];this.data.actionLog.push({id:token(10),at:Date.now(),handNumber:this.data.handNumber||0,street:this.data.street,...entry});this.data.actionLog=this.data.actionLog.slice(-ACTION_LOG_LIMIT)}
public(tokenValue){const state=super.public(tokenValue),viewer=this.viewer(tokenValue),viewerPlayer=viewer?.type==='player'?this.data.players.find(p=>p.id===viewer.id):null;state.players=state.players.map(pub=>{const source=this.data.players.find(p=>p.id===pub.id);return source?{...pub,testBot:!!source.testBot,cards:visibleCards({player:source,viewerToken:tokenValue,street:this.data.street,lastResult:this.data.lastResult})}:pub});return{...state,viewer:viewer?{type:viewer.type,id:viewer.id,name:viewer.name}:null,handStrength:viewerPlayer?handStrengthLabel([...(viewerPlayer.cards||[]),...(this.data.board||[])]):'',livePots:livePots(this.data.players),spectatorCount:this.data.spectators?.length||0,chat:(this.data.chat||[]).slice(-CHAT_LIMIT),blindStructure:(this.data.blindStructure||DEFAULT_BLINDS).map(x=>[...x]),actionLog:(this.data.actionLog||[]).slice(-40)}}
newHand(){const oldHand=this.data?.handNumber||0;super.newHand();if(this.data?.handNumber!==oldHand){this.data.actionLog=[];this.logAction({type:'hand',text:`Hand #${this.data.handNumber} started • blinds ${this.data.smallBlind}/${this.data.bigBlind}`})}}
actOne(p,type,amount){const d=this.data,snapshot={type,name:p.name,beforeBet:p.bet,beforeChips:p.chips,currentBet:d.currentBet,amount},street=d.street;super.act(p,type,amount);const text=actionLogText(snapshot);if(text)this.logAction({type,text,playerId:p.id,street})}
act(p,type,amount){this.actOne(p,type,amount);this.driveTestBots()}
start(p){super.start(p);this.driveTestBots()}
driveTestBots(){const d=this.data;if(!d?.started||d.paused||d.street==='showdown'||d.street==='finished')return;for(let guard=0;guard<60;guard++){const p=d.players[d.turnIndex];if(!p?.testBot||p.eliminated||p.folded||p.chips<=0||d.street==='showdown'||d.street==='finished')break;const toCall=Math.max(0,d.currentBet-p.bet),raiseOpen=this.raiseIsOpen(p),canRaise=raiseOpen&&p.bet+p.chips>d.currentBet,canAllIn=p.bet+p.chips<=d.currentBet||raiseOpen,choice=chooseTestBotAction({toCall,canRaise,canAllIn,raiseTo:d.currentBet+d.minRaise,chips:p.chips});this.actOne(p,choice.type,choice.amount||0)}}
addTestBot(host){const d=this.data;if(!host?.host)throw Error('Host only.');if(d.started)throw Error('Test bots can only be added before the tournament starts.');if(d.players.length>=9)throw Error('Table is full.');const name=nextTestBotName(d.players),p={id:token(12),token:token(20),name,chips:d.startingChips,bet:0,contributed:0,host:false,testBot:true,folded:false,eliminated:false,finishPlace:null,cards:[],stats:botStats(),handStartChips:0,vpipThisHand:false,pfrThisHand:false};d.players.push(p);d.message=`${name} test bot joined the table.`;return p}
showdown(){const d=this.data;this.clearTurnClock();this.verifyDeck();const{pots,awards}=settleShowdown({players:d.players,board:d.board,dealerIndex:d.dealerIndex,pot:d.pot});for(const[id,amount]of awards){const p=d.players.find(x=>x.id===id);if(!p)throw Error('Pot winner missing from table.');p.chips+=amount}const fairness=this.fairnessSnapshot(),result={summary:pots.map((p,i)=>`${pots.length>1?`Pot ${i+1}: `:''}${p.winners.join(' & ')} won ${p.amount.toLocaleString()}`).join(' • '),board:[...d.board],revealed:d.players.filter(p=>!p.folded&&p.contributed>0).map(p=>({playerId:p.id,name:p.name,cards:[...p.cards]})),pots,fairness};d.pot=0;this.beginShowdown(result)}
finalizeStats(result){const d=this.data,{winnings,biggestPot}=handAwards(result.pots||[]);for(const p of d.players){if(p.vpipThisHand)p.stats.vpipHands++;if(p.pfrThisHand)p.stats.pfrHands++;const won=winnings.get(p.id)||0;if(won>0){p.stats.handsWon++;p.stats.biggestPotWon=Math.max(p.stats.biggestPotWon,biggestPot.get(p.id)||0)}}const busted=d.players.filter(p=>!p.eliminated&&p.chips<=0);if(busted.length){const survivors=d.players.filter(p=>!p.eliminated&&p.chips>0).length,ordered=[...busted].sort((a,b)=>(b.handStartChips||0)-(a.handStartChips||0)||d.players.indexOf(a)-d.players.indexOf(b));ordered.forEach((p,i)=>{p.finishPlace=survivors+i+1;p.eliminated=true;d.placements.push({playerId:p.id,name:p.name,place:p.finishPlace,handNumber:d.handNumber})});const credits=knockoutCredits(result.pots||[],busted.map(p=>p.id));for(const[wid,credit]of credits){const winner=d.players.find(x=>x.id===wid);if(winner)winner.stats.knockouts=cleanKnockoutCount((winner.stats.knockouts||0)+credit)}}result.knockouts=busted.map(p=>({name:p.name,place:p.finishPlace}))}
async fetch(req){await this.load();const u=new URL(req.url);if(!this.data&&u.pathname!=='/init')return json({error:'Table not found.'},404);if(u.pathname==='/init'&&req.method==='POST'){const b=await req.clone().json();let structure;try{structure=normalizeBlindStructure(b.blindStructure)}catch(e){return json({error:e.message},400)}const response=await super.fetch(req);if(response.ok&&this.data){this.data.blindStructure=structure;this.data.blindLevel=0;[this.data.smallBlind,this.data.bigBlind]=structure[0];this.data.minRaise=this.data.bigBlind;this.data.actionLog=[];await this.save()}return response}if(u.pathname==='/action'&&req.method==='POST'){const b=await req.clone().json();if(b.type==='addbot'){const host=this.data.players.find(p=>p.token===b.token);try{this.addTestBot(host);await this.save();this.broadcast();return json(this.public(b.token))}catch(e){return json({error:e.message},400)}}}if(u.pathname==='/spectate'&&req.method==='POST'){const b=await req.json(),name=cleanName(b.name);if(!name)return json({error:'Display name required.'},400);if((this.data.spectators?.length||0)>=SPECTATOR_LIMIT)return json({error:'Spectator room is full.'},409);if(this.data.players.some(p=>p.name.toLowerCase()===name.toLowerCase())||this.data.spectators.some(s=>s.name.toLowerCase()===name.toLowerCase()))return json({error:'That display name is already in use.'},409);const s={id:token(12),token:token(20),name,joinedAt:Date.now()};this.data.spectators.push(s);this.data.chat.push({id:token(10),type:'system',name:'TABLE',message:`${name} is watching.`,at:Date.now()});this.data.chat=this.data.chat.slice(-CHAT_LIMIT);await this.save();this.broadcast();return json({code:this.data.code,token:s.token,viewer:'spectator'})}if(u.pathname==='/chat'&&req.method==='POST'){const b=await req.json(),viewer=this.viewer(String(b.token||''));if(!viewer)return json({error:'Invalid table session.'},403);const message=cleanMessage(b.message);if(!message)return json({error:'Message required.'},400);const now=Date.now(),last=(this.data.chat||[]).filter(m=>m.senderId===viewer.id).at(-1);if(last&&now-last.at<700)return json({error:'Slow down.'},429);this.data.chat.push({id:token(10),type:'message',senderId:viewer.id,viewerType:viewer.type,name:viewer.name,message,at:now});this.data.chat=this.data.chat.slice(-CHAT_LIMIT);await this.save();this.broadcast();return json({ok:true})}return super.fetch(req)}
webSocketError(ws){try{ws.close(1011,'socket error')}catch{}}
}