const enc=new TextEncoder(),dec=new TextDecoder();
const SESSION_COOKIE='ftp_account',STATE_COOKIE='ftp_oauth_state',SESSION_SECONDS=60*60*24*30;
function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json','cache-control':'no-store',...headers}})}
function parseCookies(req){const out={};for(const part of String(req.headers.get('cookie')||'').split(';')){const i=part.indexOf('=');if(i>0)out[part.slice(0,i).trim()]=decodeURIComponent(part.slice(i+1).trim())}return out}
function b64url(bytes){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function fromB64url(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const raw=atob(s),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return bytes}
async function sign(secret,text){const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64url(new Uint8Array(await crypto.subtle.sign('HMAC',key,enc.encode(text))))}
async function sessionToken(identity,secret){const body=b64url(enc.encode(JSON.stringify({...identity,exp:Date.now()+SESSION_SECONDS*1000})));return`${body}.${await sign(secret,body)}`}
async function verifyToken(token,secret){if(!token||!secret)return null;const[body,sig]=String(token).split('.');if(!body||!sig||await sign(secret,body)!==sig)return null;try{const value=JSON.parse(dec.decode(fromB64url(body)));if(!value.id||Number(value.exp||0)<Date.now())return null;return value}catch{return null}}
function config(env){return{clientId:env.DISCORD_CLIENT_ID||'',clientSecret:env.DISCORD_CLIENT_SECRET||'',authSecret:env.AUTH_SECRET||''}}
function avatarUrl(user){if(!user?.id||!user?.avatar)return null;return`https://cdn.discordapp.com/avatars/${user.id}/${user.avatar}.png?size=256`}
function identityFromDiscord(user){return{id:String(user.id),username:String(user.username||'Player'),displayName:String(user.global_name||user.username||'Player'),avatar:user.avatar||null,avatarUrl:avatarUrl(user)}}
export async function authenticatedIdentity(req,env){const c=config(env);if(!c.authSecret)return null;return await verifyToken(parseCookies(req)[SESSION_COOKIE],c.authSecret)}
async function accountRequest(env,identity,path,extra={}){if(!env.ACCOUNTS)return null;const stub=env.ACCOUNTS.get(env.ACCOUNTS.idFromName(identity.id));const r=await stub.fetch(`https://account.internal${path}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({identity,...extra})});return await r.json()}
function secureCookie(name,value,maxAge){return`${name}=${encodeURIComponent(value)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`}
function clearCookie(name){return`${name}=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0`}
export async function handleAuthApi(req,env){const u=new URL(req.url),c=config(env);if(u.pathname==='/api/auth/discord'&&req.method==='GET'){if(!c.clientId||!c.clientSecret||!c.authSecret)return json({error:'Discord login is not configured yet.'},503);const state=crypto.randomUUID(),redirect=env.DISCORD_REDIRECT_URI||`${u.origin}/api/auth/callback`,q=new URLSearchParams({client_id:c.clientId,response_type:'code',redirect_uri:redirect,scope:'identify',state,prompt:'consent'});return new Response(null,{status:302,headers:{location:`https://discord.com/oauth2/authorize?${q}`,'set-cookie':secureCookie(STATE_COOKIE,state,600),'cache-control':'no-store'}})}
 if(u.pathname==='/api/auth/callback'&&req.method==='GET'){if(!c.clientId||!c.clientSecret||!c.authSecret)return json({error:'Discord login is not configured yet.'},503);const cookies=parseCookies(req),state=u.searchParams.get('state')||'',code=u.searchParams.get('code')||'';if(!code||!state||state!==cookies[STATE_COOKIE])return json({error:'Discord login state expired. Try again.'},400,{'set-cookie':clearCookie(STATE_COOKIE)});const redirect=env.DISCORD_REDIRECT_URI||`${u.origin}/api/auth/callback`,tokenRes=await fetch('https://discord.com/api/oauth2/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:c.clientId,client_secret:c.clientSecret,grant_type:'authorization_code',code,redirect_uri:redirect})});if(!tokenRes.ok)return json({error:'Discord rejected the login exchange.'},502);const token=await tokenRes.json(),userRes=await fetch('https://discord.com/api/users/@me',{headers:{authorization:`Bearer ${token.access_token}`}});if(!userRes.ok)return json({error:'Could not load your Discord profile.'},502);const identity=identityFromDiscord(await userRes.json());await accountRequest(env,identity,'/sync');const signed=await sessionToken(identity,c.authSecret),headers=new Headers({location:`${u.origin}/`,'cache-control':'no-store'});headers.append('set-cookie',secureCookie(SESSION_COOKIE,signed,SESSION_SECONDS));headers.append('set-cookie',clearCookie(STATE_COOKIE));return new Response(null,{status:302,headers})}
 if(u.pathname==='/api/auth/me'&&req.method==='GET'){const identity=await authenticatedIdentity(req,env);if(!identity)return json({error:'Not logged in.'},401);const profile=await accountRequest(env,identity,'/profile');return json({discord:{id:identity.id,username:identity.username,displayName:identity.displayName,avatar:identity.avatar,avatarUrl:identity.avatarUrl||null},account:profile?.account||null})}
 if(u.pathname==='/api/auth/logout'&&req.method==='POST')return json({ok:true},200,{'set-cookie':clearCookie(SESSION_COOKIE)});
 if(u.pathname==='/api/account/equip'&&req.method==='POST'){const identity=await authenticatedIdentity(req,env);if(!identity)return json({error:'Discord login required.'},401);let body={};try{body=await req.json()}catch{}const result=await accountRequest(env,identity,'/equip',{cosmetic:body.cosmetic});return json(result||{error:'Account storage unavailable.'},result?.error?403:200)}
 return null}
function gameApi(path){return path.startsWith('/api/tables')||path.startsWith('/api/tournaments')}
function entryRoute(path,method){if(method!=='POST')return null;if(path==='/api/tables')return'hostName';if(/^\/api\/tables\/[A-Z0-9]{6}\/(?:join|spectate)$/i.test(path))return'name';if(path==='/api/tournaments')return'hostName';if(/^\/api\/tournaments\/[A-Z0-9]{6}\/join$/i.test(path))return'name';return null}
export async function gatePokerRequest(req,env){const u=new URL(req.url);if(!gameApi(u.pathname))return{request:req,response:null,identity:null};const identity=await authenticatedIdentity(req,env);if(!identity)return{request:req,response:json({error:'Discord login required.'},401),identity:null};const field=entryRoute(u.pathname,req.method);if(!field)return{request:req,response:null,identity};let body={};try{body=await req.clone().json()}catch{}body[field]=identity.displayName||identity.username||'Player';body.accountId=identity.id;const headers=new Headers(req.headers);headers.set('content-type','application/json');return{request:new Request(req.url,{method:req.method,headers,body:JSON.stringify(body),redirect:req.redirect}),response:null,identity}}
