import{telegramIdentity,verifyTelegramInitData}from'./telegram-auth.js';
import{accountRequest,linkTelegramToDiscord,resolveAccountId}from'./account-links.js';
const enc=new TextEncoder(),dec=new TextDecoder();
const SESSION_COOKIE='ftp_account',STATE_COOKIE='ftp_oauth_state',NEXT_COOKIE='ftp_oauth_next',LINK_COOKIE='ftp_oauth_link',SESSION_SECONDS=60*60*24*30;
function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json','cache-control':'no-store',...headers}})}
function parseCookies(req){const out={};for(const part of String(req.headers.get('cookie')||'').split(';')){const i=part.indexOf('=');if(i>0)out[part.slice(0,i).trim()]=decodeURIComponent(part.slice(i+1).trim())}return out}
function b64url(bytes){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function fromB64url(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const raw=atob(s),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return bytes}
function canonicalB64url(s){s=String(s||'');if(!s||!/^[A-Za-z0-9_-]+$/.test(s)||s.length%4===1)throw Error('Invalid base64url.');const bytes=fromB64url(s);if(b64url(bytes)!==s)throw Error('Non-canonical base64url.');return bytes}
async function hmacKey(secret,usage){return await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,[usage])}
async function sign(secret,text){const key=await hmacKey(secret,'sign');return b64url(new Uint8Array(await crypto.subtle.sign('HMAC',key,enc.encode(text))))}
async function verifySignature(secret,text,signature){try{const bytes=canonicalB64url(signature);if(bytes.length!==32)return false;const key=await hmacKey(secret,'verify');return await crypto.subtle.verify('HMAC',key,bytes,enc.encode(text))}catch{return false}}
async function sessionToken(identity,secret){const body=b64url(enc.encode(JSON.stringify({...identity,exp:Date.now()+SESSION_SECONDS*1000})));return`${body}.${await sign(secret,body)}`}
async function verifyToken(token,secret){if(!token||!secret)return null;const parts=String(token).split('.');if(parts.length!==2)return null;const[body,sig]=parts;if(!body||!sig||!await verifySignature(secret,body,sig))return null;try{const value=JSON.parse(dec.decode(canonicalB64url(body)));if(!value.id||Number(value.exp||0)<Date.now())return null;return value}catch{return null}}
function config(env){return{clientId:env.DISCORD_CLIENT_ID||'',clientSecret:env.DISCORD_CLIENT_SECRET||'',authSecret:env.AUTH_SECRET||'',telegramBotToken:env.TELEGRAM_BOT_TOKEN||'',telegramBotUsername:String(env.TELEGRAM_BOT_USERNAME||'').replace(/^@/,'').trim(),telegramAppShortName:String(env.TELEGRAM_APP_SHORT_NAME||'').trim(),telegramMaxAge:Math.max(60,Math.min(3600,Number(env.TELEGRAM_INITDATA_MAX_AGE||900)||900))}}
function avatarUrl(user){if(!user?.id||!user?.avatar)return null;return`https://cdn.discordapp.com/avatars/${user.id}/${user.avatar}.png?size=256`}
function identityFromDiscord(user){const providerId=String(user.id);return{id:providerId,provider:'discord',providerId,username:String(user.username||'Player'),displayName:String(user.global_name||user.username||'Player'),avatar:user.avatar||null,avatarUrl:avatarUrl(user)}}
function publicIdentity(identity={}){return{id:String(identity.id||''),provider:String(identity.provider||'discord'),providerId:String(identity.providerId||identity.id||''),username:String(identity.username||'Player'),displayName:String(identity.displayName||identity.username||'Player'),avatar:identity.avatar||null,avatarUrl:identity.avatarUrl||null}}
function safeNext(value){const m=String(value||'').match(/^#\/(table|tournament)\/([A-Z0-9]{6})/i);return m?`#/${m[1].toLowerCase()}/${m[2].toUpperCase()}`:''}
function secureCookie(name,value,maxAge){return`${name}=${encodeURIComponent(value)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`}
function clearCookie(name){return`${name}=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0`}
function discordRedirect(u,env,c,state){const redirect=env.DISCORD_REDIRECT_URI||`${u.origin}/api/auth/callback`,q=new URLSearchParams({client_id:c.clientId,response_type:'code',redirect_uri:redirect,scope:'identify',state,prompt:'consent'});return{redirect,location:`https://discord.com/oauth2/authorize?${q}`}}
function appendClear(headers,...names){for(const name of names)headers.append('set-cookie',clearCookie(name));return headers}
export async function authenticatedIdentity(req,env){const c=config(env);if(!c.authSecret)return null;return await verifyToken(parseCookies(req)[SESSION_COOKIE],c.authSecret)}
export async function handleAuthApi(req,env){const u=new URL(req.url),c=config(env);
 if(u.pathname==='/api/auth/telegram/config'&&req.method==='GET')return json({enabled:!!c.telegramBotToken,botUsername:c.telegramBotUsername,appShortName:c.telegramAppShortName});
 if(u.pathname==='/api/auth/telegram'&&req.method==='POST'){if(!c.telegramBotToken||!c.authSecret)return json({error:'Telegram login is not configured yet.'},503);let body={};try{body=await req.json()}catch{}const verified=await verifyTelegramInitData(body.initData,c.telegramBotToken,{maxAgeSeconds:c.telegramMaxAge});if(!verified)return json({error:'Telegram session could not be verified. Reopen Full Tilt from Telegram.'},401);const identity=telegramIdentity(verified.user),profile=await accountRequest(env,identity,'/sync'),signed=await sessionToken(identity,c.authSecret);return json({ok:true,identity:publicIdentity(identity),account:profile?.account||null,startParam:verified.startParam||''},200,{'set-cookie':secureCookie(SESSION_COOKIE,signed,SESSION_SECONDS)})}
 if(u.pathname==='/api/auth/link/discord'&&req.method==='GET'){if(!c.clientId||!c.clientSecret||!c.authSecret)return json({error:'Discord login is not configured yet.'},503);const identity=await authenticatedIdentity(req,env);if(!identity)return json({error:'Full Tilt login required.'},401);if(String(identity.provider)!=='telegram')return json({error:'Discord is already your primary Full Tilt login.'},400);const state=crypto.randomUUID(),{location}=discordRedirect(u,env,c,state),headers=new Headers({location,'cache-control':'no-store'});headers.append('set-cookie',secureCookie(STATE_COOKIE,state,600));headers.append('set-cookie',secureCookie(LINK_COOKIE,'discord',600));headers.append('set-cookie',clearCookie(NEXT_COOKIE));return new Response(null,{status:302,headers})}
 if(u.pathname==='/api/auth/discord'&&req.method==='GET'){if(!c.clientId||!c.clientSecret||!c.authSecret)return json({error:'Discord login is not configured yet.'},503);const state=crypto.randomUUID(),next=safeNext(u.searchParams.get('next')),{location}=discordRedirect(u,env,c,state),headers=new Headers({location,'cache-control':'no-store'});headers.append('set-cookie',secureCookie(STATE_COOKIE,state,600));headers.append('set-cookie',clearCookie(LINK_COOKIE));if(next)headers.append('set-cookie',secureCookie(NEXT_COOKIE,next,600));else headers.append('set-cookie',clearCookie(NEXT_COOKIE));return new Response(null,{status:302,headers})}
 if(u.pathname==='/api/auth/callback'&&req.method==='GET'){if(!c.clientId||!c.clientSecret||!c.authSecret)return json({error:'Discord login is not configured yet.'},503);const cookies=parseCookies(req),state=u.searchParams.get('state')||'',code=u.searchParams.get('code')||'',linking=cookies[LINK_COOKIE]==='discord';if(!code||!state||state!==cookies[STATE_COOKIE])return json({error:'Discord login state expired. Try again.'},400,{'set-cookie':clearCookie(STATE_COOKIE)});const redirect=env.DISCORD_REDIRECT_URI||`${u.origin}/api/auth/callback`,tokenRes=await fetch('https://discord.com/api/oauth2/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:c.clientId,client_secret:c.clientSecret,grant_type:'authorization_code',code,redirect_uri:redirect})});if(!tokenRes.ok)return json({error:'Discord rejected the login exchange.'},502);const token=await tokenRes.json(),userRes=await fetch('https://discord.com/api/users/@me',{headers:{authorization:`Bearer ${token.access_token}`}});if(!userRes.ok)return json({error:'Could not load your Discord profile.'},502);const discordIdentity=identityFromDiscord(await userRes.json());if(linking){const telegramIdentity=await authenticatedIdentity(req,env),headers=new Headers({'cache-control':'no-store'});appendClear(headers,STATE_COOKIE,LINK_COOKIE,NEXT_COOKIE);if(!telegramIdentity||String(telegramIdentity.provider)!=='telegram'){headers.set('location',`${u.origin}/?link=failed`);return new Response(null,{status:302,headers})}try{await linkTelegramToDiscord(env,telegramIdentity,discordIdentity);headers.set('location',`${u.origin}/?linked=discord`);return new Response(null,{status:302,headers})}catch(error){console.error('account_link_failed',{telegramId:telegramIdentity.id,discordId:discordIdentity.id,error:error.message});headers.set('location',`${u.origin}/?link=failed`);return new Response(null,{status:302,headers})}}
 const identity=discordIdentity;await accountRequest(env,identity,'/sync');const signed=await sessionToken(identity,c.authSecret),next=safeNext(cookies[NEXT_COOKIE]),headers=new Headers({location:`${u.origin}/${next}`,'cache-control':'no-store'});headers.append('set-cookie',secureCookie(SESSION_COOKIE,signed,SESSION_SECONDS));appendClear(headers,STATE_COOKIE,NEXT_COOKIE,LINK_COOKIE);return new Response(null,{status:302,headers})}
 if(u.pathname==='/api/auth/me'&&req.method==='GET'){const identity=await authenticatedIdentity(req,env);if(!identity)return json({error:'Not logged in.'},401);const profile=await accountRequest(env,identity,'/profile'),safe=publicIdentity(identity);return json({identity:safe,discord:safe.provider==='discord'?safe:null,telegram:safe.provider==='telegram'?safe:null,account:profile?.account||null,canonicalAccountId:profile?.canonicalId||identity.id})}
 if(u.pathname==='/api/auth/logout'&&req.method==='POST')return json({ok:true},200,{'set-cookie':clearCookie(SESSION_COOKIE)});
 if(u.pathname==='/api/account/equip'&&req.method==='POST'){const identity=await authenticatedIdentity(req,env);if(!identity)return json({error:'Crashout Poker login required.'},401);let body={};try{body=await req.json()}catch{}const result=await accountRequest(env,identity,'/equip',{cosmetic:body.cosmetic});return json(result||{error:'Account storage unavailable.'},result?.error?403:200)}
 if(u.pathname==='/api/account/notifications'&&req.method==='POST'){const identity=await authenticatedIdentity(req,env);if(!identity)return json({error:'Crashout Poker login required.'},401);let body={};try{body=await req.json()}catch{}const result=await accountRequest(env,identity,'/notifications/preferences',{notifications:body.notifications||{}});return json(result||{error:'Account storage unavailable.'},result?.error?400:200)}
 return null}
function gameApi(path){return path.startsWith('/api/tables')||path.startsWith('/api/tournaments')}
function entryRoute(path,method){if(method!=='POST')return null;if(path==='/api/tables')return'hostName';if(/^\/api\/tables\/[A-Z0-9]{6}\/(?:join|spectate)$/i.test(path))return'name';if(path==='/api/tournaments')return'hostName';if(/^\/api\/tournaments\/[A-Z0-9]{6}\/join$/i.test(path))return'name';return null}
function actionRoute(path,method){return method==='POST'&&(/^\/api\/tables\/[A-Z0-9]{6}\/action$/i.test(path)||/^\/api\/tournaments\/[A-Z0-9]{6}\/table\/action$/i.test(path))}
function privateScope(path,method){if(path==='/api/tables'&&method==='POST')return{create:true,kind:'table'};if(path==='/api/tournaments'&&method==='POST')return{create:true,kind:'tournament'};let m=path.match(/^\/api\/tables\/([A-Z0-9]{6})(?:\/|$)/i);if(m)return{create:false,kind:'table',code:m[1].toUpperCase()};m=path.match(/^\/api\/tournaments\/([A-Z0-9]{6})(?:\/|$)/i);if(m)return{create:false,kind:'tournament',code:m[1].toUpperCase()};return null}
export async function gatePokerRequest(req,env){
 const u=new URL(req.url);if(!gameApi(u.pathname))return{request:req,response:null,identity:null};const identity=await authenticatedIdentity(req,env);if(!identity)return{request:req,response:json({error:'Crashout Poker login required.'},401),identity:null};
 const canonicalId=await resolveAccountId(env,identity.id),scope=privateScope(u.pathname,req.method),field=entryRoute(u.pathname,req.method),isAction=actionRoute(u.pathname,req.method);let hostReservationId=null,hostKind=null;
 if(scope?.code){let access;try{access=await accountRequest(env,identity,'/access/invite-check',{kind:scope.kind,code:scope.code})}catch(error){return{request:req,response:json({error:error.message||'Private game access could not be verified.'},error.status||503),identity,canonicalId}}if(!access?.allowed)return{request:req,response:json({error:'Invite access required for this private game.'},403),identity,canonicalId}}
 let body={},needsBody=!!field||isAction;if(needsBody)try{body=await req.clone().json()}catch{}
 let profile=null,equipped='default';if(field||isAction){try{profile=await accountRequest(env,identity,'/profile')}catch(error){return{request:req,response:json({error:error.message||'Account unavailable.'},error.status||503),identity,canonicalId}}equipped=String(profile?.account?.equipped||'default')}
 if(scope?.create){let reserved;try{reserved=await accountRequest(env,identity,'/access/host-reserve')}catch(error){return{request:req,response:json({error:error.message||'Host access required.'},error.status||403),identity,canonicalId}}if(!reserved?.allowed)return{request:req,response:json({error:'Private host access could not be verified.'},503),identity,canonicalId};hostReservationId=String(reserved?.reservationId||'');hostKind=scope.kind}
 if(field){body[field]=identity.displayName||identity.username||'Player';body.accountId=canonicalId;body.cosmetic=equipped}
 if(isAction&&String(body.type||'')==='cosmetic'){const requested=String(body.cosmetic||body.amount||'default');if(requested!==equipped)return{request:req,response:json({error:'Equip that booster from your Crashout Poker profile before using it at the table.'},403),identity,canonicalId,hostReservationId,hostKind};body.cosmetic=equipped}
 if(!needsBody)return{request:req,response:null,identity,canonicalId,hostReservationId,hostKind};
 const headers=new Headers(req.headers);headers.set('content-type','application/json');return{request:new Request(req.url,{method:req.method,headers,body:JSON.stringify(body),redirect:req.redirect}),response:null,identity,canonicalId,hostReservationId,hostKind}
}
