const RANKS='23456789TJQKA';const SUITS=['♠','♥','♦','♣'];const LEVELS=[[10,20],[15,30],[25,50],[50,100],[75,150],[100,200],[150,300],[200,400],[300,600],[500,1000],[750,1500],[1000,2000]];const TURN_SECONDS=30;
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json','cache-control':'no-store'}})}
function id(n=12){const a='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let s='';crypto.getRandomValues(new Uint8Array(n)).forEach(x=>s+=a[x%a.length]);return s}
function makeDeck(){const d=[];for(const r of RANKS)for(const s of SUITS)d.push(r+s);for(let i=d.length-1;i>0;i--){const x=new Uint32Array(1);crypto.getRandomValues(x);const j=x[0]%(i+1);[d[i],d[j]]=[d[j],d[i]]}return d}
export default{async fetch(req,env){const u=new URL(req.url);if(u.pathname==='/api/health')return json({ok:true,name:'FULL TILT POKER',version:'0.4.0',realtime:'websocket-hibernation'});if(u.pathname==='/api/tables'&&req.method==='POST'){const body=await req.json();const code=id(6);const stub=env.TABLES.get(env.TABLES.idFromName(code));return stub.fetch(new Request('https://table/init',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...body,code})}))}const m=u.pathname.match(/^\/api\/tables\/([A-Z0-9]{6})(?:\/(join|action|ws))?$/);if(m){const stub=env.TABLES.get(env.TABLES.idFromName(m[1]));const path=m[2]==='ws'?'websocket':m[2]||'state';return stub.fetch(new Request(`https://table/${path}${u.search}`,{method:req.method,headers:req.headers,body:req.method==='GET'?undefined:req.body,duplex:req.body?'half':undefined}))}return env.ASSETS.fetch(req)}};
export class PokerTable{
constructor(state,env){this.state=state;this.env=env;this.data=null}
async load(){if(!this.data)this.data=await this.state.storage.get('game')||null}
async save(){await this.state.storage.put('game',this.data)}
async alarm(){await this.load();if(!this.data)return;const changed=this.handleTurnTimeout();this.tickBlinds();await this.save();if(changed)this.broadcast()}
public(token){const d=this.data,me=d.players.find(p=>p.token===token);return{code:d.code,startingChips:d.startingChips,blindMinutes:d.blindMinutes,blindLevel:d.blindLevel,smallBlind:d.smallBlind,bigBlind:d.bigBlind,levelStartedAt:d.levelStartedAt,started:d.started,paused:d.paused,turnSeconds:d.turnSeconds||TURN_SECONDS,turnDeadline:d.turnDeadline||null,players:d.players.map(p=>({id:p.id,name:p.name,chips:p.chips,bet:p.bet,host:p.host,folded:p.folded,eliminated:p.eliminated,contributed:p.contributed,cards:p.token===token?p.cards:(p.cards?.length?['','']:[]),token:p.token===token?p.token:undefined,turn:d.started&&!d.paused&&d.players[d.turnIndex]?.id===p.id})),board:d.board,pot:d.pot,dealerIndex:d.dealerIndex,currentBet:d.currentBet,minRaise:d.minRaise,street:d.street,message:d.message,lastResult:d.lastResult||null,toCall:me?Math.max(0,d.currentBet-me.bet):0,raiseTo:d.currentBet+d.minRaise}}
broadcast(){if(!this.data)return;for(const ws of this.state.getWebSockets()){try{const a=ws.deserializeAttachment()||{};ws.send(JSON.stringify({type:'state',state:this.public(a.token||'')}))}catch{}}}
async fetch(req){await this.load();const u=new URL(req.url);if(u.pathname==='/init'&&req.method==='POST'){if(this.data)return json({error:'Table already exists.'},409);const b=await req.json(),lv=LEVELS[0],host={id:id(),token:id(20),name:String(b.hostName||'Host').trim().slice(0,24),chips:Math.max(100,Number(b.startingChips)||2500),bet:0,contributed:0,host:true,folded:false,eliminated:false,cards:[]};if(!host.name)return json({error:'Display name required.'},400);this.data={code:b.code,startingChips:host.chips,blindMinutes:Math.max(1,Number(b.blindMinutes)||10),blindLevel:0,smallBlind:lv[0],bigBlind:lv[1],levelStartedAt:null,started:false,paused:false,players:[host],board:[],pot:0,deck:[],dealerIndex:0,turnIndex:0,currentBet:0,minRaise:lv[1],street:'waiting',acted:{},message:'Waiting for players.',lastResult:null,turnSeconds:TURN_SECONDS,turnDeadline:null};await this.save();return json({code:b.code,token:host.token})}if(!this.data)return json({error:'Table not found.'},404);
if(u.pathname==='/websocket'){if(req.headers.get('Upgrade')!=='websocket')return json({error:'Expected WebSocket upgrade.'},426);const token=u.searchParams.get('token')||'';const pair=new WebSocketPair(),[client,server]=Object.values(pair);this.state.acceptWebSocket(server);server.serializeAttachment({token});server.send(JSON.stringify({type:'state',state:this.public(token)}));return new Response(null,{status:101,webSocket:client})}
const timedOut=this.handleTurnTimeout();
if(u.pathname==='/join'&&req.method==='POST'){if(this.data.started)return json({error:'Tournament already started.'},409);if(this.data.players.length>=9)return json({error:'Table is full.'},409);const b=await req.json(),name=String(b.name||'').trim().slice(0,24);if(!name)return json({error:'Display name required.'},400);if(this.data.players.some(p=>p.name.toLowerCase()===name.toLowerCase()))return json({error:'That display name is already seated.'},409);const p={id:id(),token:id(20),name,chips:this.data.startingChips,bet:0,contributed:0,host:false,folded:false,eliminated:false,cards:[]};this.data.players.push(p);this.data.message=`${name} joined the table.`;await this.save();this.broadcast();return json({code:this.data.code,token:p.token})}
if(u.pathname==='/state'&&req.method==='GET'){this.tickBlinds();const token=u.searchParams.get('token')||'';await this.save();if(timedOut)this.broadcast();return json(this.public(token))}
if(u.pathname==='/action'&&req.method==='POST'){const b=await req.json(),p=this.data.players.find(x=>x.token===b.token);if(!p)return json({error:'Invalid player session.'},403);try{if(b.type==='start')this.start(p);else if(b.type==='pause')this.pause(p);else if(b.type==='resume')this.resume(p);else if(b.type==='kick')this.kick(p,b.targetId);else if(b.type==='end'){if(!p.host)throw Error('Host only.');this.data.started=false;this.data.paused=false;this.clearTurnClock();this.data.message='Tournament ended by host.'}else this.act(p,b.type,Number(b.amount)||0);this.tickBlinds();await this.save();this.broadcast();return json(this.public(p.token))}catch(e){return json({error:e.message},400)}}return json({error:'Not found.'},404)}
webSocketMessage(ws,message){if(message==='ping'){try{ws.send('pong')}catch{}}else{try{const a=ws.deserializeAttachment()||{};ws.send(JSON.stringify({type:'state',state:this.public(a.token||'')}))}catch{}}}
webSocketClose(ws,code,reason){try{ws.close(code,reason)}catch{}}
tickBlinds(){const d=this.data;if(!d.started||d.paused||!d.levelStartedAt)return false;const duration=d.blindMinutes*60000,passed=Date.now()-d.levelStartedAt;if(passed>=duration){const jumps=Math.floor(passed/duration),old=d.blindLevel;d.blindLevel=Math.min(LEVELS.length-1,d.blindLevel+jumps);[d.smallBlind,d.bigBlind]=LEVELS[d.blindLevel];d.levelStartedAt+=jumps*duration;if(d.blindLevel!==old){d.message=`Blind level advanced to ${d.smallBlind}/${d.bigBlind}. New blinds post next hand.`;return true}}return false}
startTurnClock(){const d=this.data;if(!d.started||d.paused||d.street==='finished'){this.clearTurnClock();return}d.turnDeadline=Date.now()+(d.turnSeconds||TURN_SECONDS)*1000;this.state.storage.setAlarm(d.turnDeadline)}
clearTurnClock(){if(!this.data)return;this.data.turnDeadline=null;this.state.storage.deleteAlarm()}
handleTurnTimeout(){const d=this.data;if(!d?.started||d.paused||!d.turnDeadline||Date.now()<d.turnDeadline)return false;const p=d.players[d.turnIndex];if(!p||p.eliminated||p.folded||p.chips<=0){this.advance();return true}const toCall=Math.max(0,d.currentBet-p.bet);if(toCall===0){d.acted[p.id]=true;d.message=`${p.name} timed out and checked.`}else{p.folded=true;d.acted[p.id]=true;d.message=`${p.name} timed out and folded.`}this.advance();return true}
start(p){const d=this.data;if(!p.host)throw Error('Host only.');if(d.players.length<2)throw Error('Need at least 2 players.');if(d.started)throw Error('Tournament already started.');d.started=true;d.paused=false;d.levelStartedAt=Date.now();d.dealerIndex=Math.floor(Math.random()*d.players.length);this.newHand()}
pause(p){const d=this.data;if(!p.host)throw Error('Host only.');if(!d.started)throw Error('Game is not running.');if(d.paused)throw Error('Game is already paused.');d.paused=true;d.pausedAt=Date.now();d.turnRemainingMs=d.turnDeadline?Math.max(0,d.turnDeadline-Date.now()):null;this.clearTurnClock();d.message='Tournament paused by host.'}
resume(p){const d=this.data;if(!p.host)throw Error('Host only.');if(!d.paused)throw Error('Game is not paused.');if(d.levelStartedAt&&d.pausedAt)d.levelStartedAt+=Date.now()-d.pausedAt;d.paused=false;d.pausedAt=null;if(d.turnRemainingMs!=null){d.turnDeadline=Date.now()+Math.max(1000,d.turnRemainingMs);this.state.storage.setAlarm(d.turnDeadline);d.turnRemainingMs=null}else this.startTurnClock();d.message=`Tournament resumed. ${d.players[d.turnIndex]?.name||'Player'} to act.`}
kick(p,targetId){const d=this.data;if(!p.host)throw Error('Host only.');if(d.started)throw Error('Players can only be removed before the tournament starts.');const target=d.players.find(x=>x.id===targetId);if(!target)throw Error('Player not found.');if(target.host)throw Error('Host cannot remove themselves.');d.players=d.players.filter(x=>x.id!==targetId);d.message=`${target.name} was removed from the table.`}
active(){return this.data.players.filter(p=>!p.eliminated&&p.chips>0)}
nextIndex(i,turn=false){const d=this.data;for(let k=1;k<=d.players.length;k++){const n=(i+k)%d.players.length,p=d.players[n];if(!p.eliminated&&(!turn||(!p.folded&&p.chips>0)))return n}return i}
newHand(){const d=this.data;for(const p of d.players){if(p.chips<=0)p.eliminated=true;p.bet=0;p.contributed=0;p.folded=false;p.cards=[]}const alive=this.active();if(alive.length<=1){d.started=false;d.paused=false;d.street='finished';d.board=[];d.pot=0;this.clearTurnClock();d.message=alive.length?`${alive[0].name} wins the tournament!`:'Tournament ended.';return}d.deck=makeDeck();d.board=[];d.pot=0;d.street='preflop';d.acted={};d.dealerIndex=this.nextIndex(d.dealerIndex);for(let r=0;r<2;r++)for(let k=1;k<=d.players.length;k++){const i=(d.dealerIndex+k)%d.players.length,p=d.players[i];if(!p.eliminated)p.cards.push(d.deck.pop())}let sb,bb;if(alive.length===2){sb=d.dealerIndex;bb=this.nextIndex(sb)}else{sb=this.nextIndex(d.dealerIndex);bb=this.nextIndex(sb)}this.post(sb,d.smallBlind);this.post(bb,d.bigBlind);d.currentBet=Math.max(d.players[sb].bet,d.players[bb].bet);d.minRaise=d.bigBlind;d.turnIndex=this.nextIndex(bb,true);d.message=`New hand. ${d.players[d.turnIndex].name} to act.`;this.startTurnClock();this.autoRunoutIfNeeded()}
post(i,n){const p=this.data.players[i],x=Math.min(p.chips,n);p.chips-=x;p.bet+=x;p.contributed+=x;this.data.pot+=x}
putChips(p,n){const x=Math.max(0,Math.min(p.chips,n));p.chips-=x;p.bet+=x;p.contributed+=x;this.data.pot+=x;return x}
act(p,type,amount){const d=this.data;if(!d.started)throw Error('Game has not started.');if(d.paused)throw Error('Tournament is paused.');if(d.players[d.turnIndex]?.id!==p.id)throw Error('Not your turn.');if(p.folded||p.eliminated||p.chips<=0)throw Error('You cannot act.');const toCall=Math.max(0,d.currentBet-p.bet);if(type==='fold')p.folded=true;else if(type==='check'){if(toCall)throw Error('You cannot check facing a bet.')}else if(type==='call')this.putChips(p,toCall);else if(type==='allin'){const target=p.bet+p.chips;if(target<=d.currentBet)this.putChips(p,p.chips);else this.raiseTo(p,target)}else if(type==='raise')this.raiseTo(p,amount);else throw Error('Unknown action.');if(type!=='raise'&&type!=='allin')d.acted[p.id]=true;this.advance()}
raiseTo(p,target){const d=this.data;target=Math.min(target,p.bet+p.chips);if(target<=d.currentBet)throw Error('Raise must exceed current bet.');const old=d.currentBet,raiseSize=target-old,isAllIn=target===p.bet+p.chips;if(raiseSize<d.minRaise&&!isAllIn)throw Error(`Minimum raise is to ${d.currentBet+d.minRaise}.`);this.putChips(p,target-p.bet);d.currentBet=p.bet;if(raiseSize>=d.minRaise){d.minRaise=raiseSize;d.acted={[p.id]:true}}else d.acted[p.id]=true}
advance(){const d=this.data,live=d.players.filter(p=>!p.eliminated&&!p.folded);if(live.length===1){this.awardUncontested(live[0]);return}const canAct=live.filter(p=>p.chips>0);if(canAct.length===0){this.runout();return}const settled=canAct.every(p=>p.bet===d.currentBet),allActed=canAct.every(p=>d.acted[p.id]);if(settled&&allActed){this.nextStreet();return}if(canAct.length===1&&settled&&d.acted[canAct[0].id]){this.runout();return}d.turnIndex=this.nextIndex(d.turnIndex,true);d.message=`${d.players[d.turnIndex].name} to act.`;this.startTurnClock()}
nextStreet(){const d=this.data;for(const p of d.players)p.bet=0;d.currentBet=0;d.minRaise=d.bigBlind;d.acted={};if(d.street==='preflop'){d.deck.pop();d.board.push(d.deck.pop(),d.deck.pop(),d.deck.pop());d.street='flop'}else if(d.street==='flop'){d.deck.pop();d.board.push(d.deck.pop());d.street='turn'}else if(d.street==='turn'){d.deck.pop();d.board.push(d.deck.pop());d.street='river'}else{this.showdown();return}const can=d.players.filter(p=>!p.eliminated&&!p.folded&&p.chips>0);if(can.length<=1){this.runout();return}d.turnIndex=this.nextIndex(d.dealerIndex,true);d.message=`${d.street.toUpperCase()}. ${d.players[d.turnIndex].name} to act.`;this.startTurnClock()}
autoRunoutIfNeeded(){const d=this.data,live=d.players.filter(p=>!p.eliminated&&!p.folded),can=live.filter(p=>p.chips>0);if(can.length===0)this.runout();else if(can.length===1&&can[0].bet===d.currentBet){d.acted[can[0].id]=true;this.runout()}}
runout(){const d=this.data;this.clearTurnClock();while(d.board.length<5){d.deck.pop();if(d.board.length===0)d.board.push(d.deck.pop(),d.deck.pop(),d.deck.pop());else d.board.push(d.deck.pop())}this.showdown()}
awardUncontested(p){const d=this.data,won=d.pot;this.clearTurnClock();p.chips+=won;d.lastResult={summary:`${p.name} wins ${won.toLocaleString()} chips uncontested.`,board:[...d.board],pots:[{amount:won,winners:[p.name]}]};d.pot=0;this.newHand()}
showdown(){const d=this.data;this.clearTurnClock();const contributors=d.players.filter(p=>p.contributed>0),levels=[...new Set(contributors.map(p=>p.contributed))].sort((a,b)=>a-b),scores=new Map(),pots=[];for(const p of d.players.filter(p=>!p.folded&&p.contributed>0))scores.set(p.id,evaluate([...p.cards,...d.board]));let prev=0,total=0;for(const level of levels){const participants=contributors.filter(p=>p.contributed>=level),amount=(level-prev)*participants.length;prev=level;if(amount<=0)continue;const eligible=participants.filter(p=>!p.folded);if(!eligible.length)continue;let best=null,winners=[];for(const p of eligible){const score=scores.get(p.id);if(!best||compare(score,best)>0){best=score;winners=[p]}else if(compare(score,best)===0)winners.push(p)}const share=Math.floor(amount/winners.length),rem=amount-share*winners.length;const order=[...winners].sort((a,b)=>((d.players.indexOf(a)-d.dealerIndex+d.players.length)%d.players.length)-((d.players.indexOf(b)-d.dealerIndex+d.players.length)%d.players.length));order.forEach((p,i)=>p.chips+=share+(i<rem?1:0));total+=amount;pots.push({amount,winners:winners.map(p=>p.name)})}d.lastResult={summary:pots.map((p,i)=>`${pots.length>1?`Pot ${i+1}: `:''}${p.winners.join(' & ')} won ${p.amount.toLocaleString()}`).join(' • '),board:[...d.board],revealed:d.players.filter(p=>!p.folded&&p.contributed>0).map(p=>({name:p.name,cards:[...p.cards]})),pots};d.pot=Math.max(0,d.pot-total);if(d.pot>0){const live=d.players.filter(p=>!p.folded&&p.contributed>0);if(live[0]){live[0].chips+=d.pot;d.pot=0}}this.newHand()}}
function evaluate(cards){const rs=cards.map(c=>RANKS.indexOf(c[0])+2).sort((a,b)=>b-a),suits={};for(const c of cards)(suits[c[1]]??=[]).push(RANKS.indexOf(c[0])+2);const counts={};rs.forEach(r=>counts[r]=(counts[r]||0)+1);const uniq=[...new Set(rs)];if(uniq.includes(14))uniq.push(1);let straight=0;for(let i=0;i<=uniq.length-5;i++)if(uniq.slice(i,i+5).every((v,j,a)=>j===0||a[j-1]-v===1)){straight=uniq[i];break}let flush=[];for(const a of Object.values(suits))if(a.length>=5)flush=a.sort((a,b)=>b-a);if(flush.length){const u=[...new Set(flush)];if(u.includes(14))u.push(1);for(let i=0;i<=u.length-5;i++)if(u.slice(i,i+5).every((v,j,a)=>j===0||a[j-1]-v===1))return[8,u[i]]}const groups=Object.entries(counts).map(([r,c])=>[c,+r]).sort((a,b)=>b[0]-a[0]||b[1]-a[1]);if(groups[0][0]===4)return[7,groups[0][1],...rs.filter(r=>r!==groups[0][1]).slice(0,1)];const trips=groups.filter(g=>g[0]>=3),pairs=groups.filter(g=>g[0]>=2);if(trips.length&&pairs.some(g=>g[1]!==trips[0][1]))return[6,trips[0][1],pairs.find(g=>g[1]!==trips[0][1])[1]];if(flush.length)return[5,...flush.slice(0,5)];if(straight)return[4,straight];if(trips.length)return[3,trips[0][1],...rs.filter(r=>r!==trips[0][1]).slice(0,2)];if(pairs.length>=2){const a=pairs[0][1],b=pairs[1][1];return[2,a,b,...rs.filter(r=>r!==a&&r!==b).slice(0,1)]}if(pairs.length)return[1,pairs[0][1],...rs.filter(r=>r!==pairs[0][1]).slice(0,3)];return[0,...uniq.filter(x=>x!==1).slice(0,5)]}
function compare(a,b){for(let i=0;i<Math.max(a.length,b.length);i++){const d=(a[i]||0)-(b[i]||0);if(d)return d}return 0}