const ALLOWED_COSMETICS=new Set(['default','constellation','deadMansHand','regalia']);
const DEFAULT_STATS=()=>({handsPlayed:0,tournamentsPlayed:0,tournamentWins:0,finalTables:0,knockouts:0,biggestPot:0,chipsWon:0});
function cleanIdentity(value={}){return{id:String(value.id||''),username:String(value.username||'Player').slice(0,64),displayName:String(value.displayName||value.globalName||value.username||'Player').slice(0,64),avatar:value.avatar?String(value.avatar):null}}
function nonNegative(v){return Math.max(0,Math.trunc(Number(v)||0))}
function cleanCheckpoint(value={}){return{handsPlayed:nonNegative(value.handsPlayed),knockouts:nonNegative(value.knockouts),biggestPot:nonNegative(value.biggestPot??value.biggestPotWon),chipsWon:nonNegative(value.chipsWon)}}
function validEntitlements(values=[]){return Array.from(new Set((Array.isArray(values)?values:[]).map(x=>String(x||'')).filter(x=>ALLOWED_COSMETICS.has(x)&&x!=='default')))}
function ensureCommerce(account){account.purchases??={};if(!Array.isArray(account.legacyInventory)){const explained=new Set(Object.values(account.purchases).flatMap(p=>validEntitlements(p?.entitlements)));account.legacyInventory=validEntitlements(account.inventory||[]).filter(x=>!explained.has(x))}return account}
function rebuildInventory(account){ensureCommerce(account);const active=Object.values(account.purchases||{}).filter(p=>String(p?.status||'paid')!=='refunded').flatMap(p=>validEntitlements(p?.entitlements));account.inventory=Array.from(new Set(['default',...validEntitlements(account.legacyInventory),...active]));if(!account.inventory.includes(account.equipped))account.equipped='default';return account}
function publicPurchases(data){return Object.entries(data.purchases||{}).map(([checkoutSessionId,p])=>({purchaseId:String(checkoutSessionId),purchaseKey:String(p?.purchaseKey||''),entitlements:validEntitlements(p?.entitlements),at:nonNegative(p?.at),amountTotal:nonNegative(p?.amountTotal),currency:String(p?.currency||'usd').slice(0,12).toLowerCase(),status:String(p?.status||'paid'),amountRefunded:nonNegative(p?.amountRefunded),refundedAt:p?.refundedAt?nonNegative(p.refundedAt):null,refundRequestedAt:p?.refundRequestedAt?nonNegative(p.refundRequestedAt):null,reference:String(checkoutSessionId).slice(-10)})).sort((a,b)=>b.at-a.at)}
function publicAccount(data){return{id:data.id,username:data.username,displayName:data.displayName,avatar:data.avatar,createdAt:data.createdAt,lastSeenAt:data.lastSeenAt,stats:data.stats||DEFAULT_STATS(),inventory:Array.isArray(data.inventory)?data.inventory:['default'],equipped:ALLOWED_COSMETICS.has(data.equipped)?data.equipped:'default',purchases:publicPurchases(data)}}
export class PlayerAccount{
 constructor(ctx,env){this.ctx=ctx;this.env=env}
 async load(){return await this.ctx.storage.get('account')||null}
 async sync(identity){const clean=cleanIdentity(identity);if(!clean.id)throw new Error('Discord identity required.');const now=Date.now(),existing=await this.load(),next=existing?{...existing,...clean,lastSeenAt:now,stats:{...DEFAULT_STATS(),...(existing.stats||{})},inventory:Array.from(new Set(['default',...(existing.inventory||[])])),equipped:ALLOWED_COSMETICS.has(existing.equipped)?existing.equipped:'default',checkpoints:{...(existing.checkpoints||{})},events:{...(existing.events||{})},purchases:{...(existing.purchases||{})}}:{...clean,createdAt:now,lastSeenAt:now,stats:DEFAULT_STATS(),inventory:['default'],equipped:'default',checkpoints:{},events:{},purchases:{},legacyInventory:[]};ensureCommerce(next);rebuildInventory(next);await this.ctx.storage.put('account',next);return next}
 async checkpoint(body={}){const account=await this.load();if(!account)throw new Error('Player account has not been initialized.');const source=String(body.source||'').slice(0,128);if(!source)throw new Error('Stat source required.');account.stats={...DEFAULT_STATS(),...(account.stats||{})};account.checkpoints??={};const previous=cleanCheckpoint(account.checkpoints[source]),current=cleanCheckpoint(body.stats),hands=Math.max(previous.handsPlayed,current.handsPlayed),knockouts=Math.max(previous.knockouts,current.knockouts),chipsWon=Math.max(previous.chipsWon,current.chipsWon);account.stats.handsPlayed+=Math.max(0,hands-previous.handsPlayed);account.stats.knockouts+=Math.max(0,knockouts-previous.knockouts);account.stats.chipsWon+=Math.max(0,chipsWon-previous.chipsWon);account.stats.biggestPot=Math.max(nonNegative(account.stats.biggestPot),current.biggestPot,previous.biggestPot);account.checkpoints[source]={handsPlayed:hands,knockouts,biggestPot:Math.max(previous.biggestPot,current.biggestPot),chipsWon};account.lastSeenAt=Date.now();await this.ctx.storage.put('account',account);return account}
 async tournamentResult(body={}){const account=await this.load();if(!account)throw new Error('Player account has not been initialized.');const code=String(body.tournamentCode||'').trim().toUpperCase().slice(0,32),place=nonNegative(body.finishPlace),fieldSize=Math.max(1,nonNegative(body.fieldSize));if(!code||!place)throw new Error('Complete tournament result required.');account.stats={...DEFAULT_STATS(),...(account.stats||{})};account.events??={};const key=`tournament:${code}`;if(account.events[key])return account;account.stats.tournamentsPlayed++;if(place===1)account.stats.tournamentWins++;if(place<=Math.min(8,fieldSize))account.stats.finalTables++;account.events[key]={at:Date.now(),place,fieldSize};account.lastSeenAt=Date.now();await this.ctx.storage.put('account',account);return account}
 async grantPurchase(body={}){const account=await this.load();if(!account)throw new Error('Player account has not been initialized.');ensureCommerce(account);const checkoutSessionId=String(body.checkoutSessionId||'').slice(0,255),purchaseKey=String(body.purchaseKey||body.cosmetic||'').slice(0,64),requested=Array.isArray(body.entitlements)&&body.entitlements.length?body.entitlements:[body.cosmetic],entitlements=validEntitlements(requested);if(!checkoutSessionId)throw new Error('Stripe checkout session required.');if(!purchaseKey||!entitlements.length||entitlements.length!==requested.filter(Boolean).length)throw new Error('Unknown booster entitlement.');if(account.purchases[checkoutSessionId])return account;account.purchases[checkoutSessionId]={purchaseKey,entitlements,at:Date.now(),paymentIntent:body.paymentIntent?String(body.paymentIntent).slice(0,255):null,amountTotal:nonNegative(body.amountTotal),currency:String(body.currency||'usd').slice(0,12).toLowerCase(),customer:body.customer?String(body.customer).slice(0,255):null,status:'paid',amountRefunded:0};rebuildInventory(account);account.lastSeenAt=Date.now();await this.ctx.storage.put('account',account);return account}
 async refundTarget(body={}){const account=await this.load();if(!account)throw new Error('Player account has not been initialized.');ensureCommerce(account);const purchaseId=String(body.purchaseId||''),purchase=account.purchases[purchaseId];if(!purchase)throw new Error('Purchase was not found.');const status=String(purchase.status||'paid');if(status==='refunded')throw new Error('That purchase has already been refunded.');if(status==='refund_pending')throw new Error('That refund is already being processed.');if(!purchase.paymentIntent)throw new Error('This purchase cannot be refunded automatically. Contact billing support.');return{purchaseId,purchaseKey:String(purchase.purchaseKey||''),paymentIntent:String(purchase.paymentIntent),amountTotal:nonNegative(purchase.amountTotal),amountRefunded:nonNegative(purchase.amountRefunded),currency:String(purchase.currency||'usd').toLowerCase(),status}}
 async markRefundRequested(body={}){const account=await this.load();if(!account)throw new Error('Player account has not been initialized.');ensureCommerce(account);const purchaseId=String(body.purchaseId||''),purchase=account.purchases[purchaseId];if(!purchase)throw new Error('Purchase was not found.');if(String(purchase.status||'paid')==='refunded')return account;purchase.status='refund_pending';purchase.refundRequestedAt=Date.now();if(body.refundId)purchase.refundId=String(body.refundId).slice(0,255);account.purchases[purchaseId]=purchase;rebuildInventory(account);account.lastSeenAt=Date.now();await this.ctx.storage.put('account',account);return account}
 async applyRefund(body={}){const account=await this.load();if(!account)throw new Error('Player account has not been initialized.');ensureCommerce(account);const checkoutSessionId=String(body.checkoutSessionId||''),paymentIntent=String(body.paymentIntent||''),entry=Object.entries(account.purchases).find(([id,p])=>(checkoutSessionId&&id===checkoutSessionId)||(paymentIntent&&String(p?.paymentIntent||'')===paymentIntent));if(!entry)throw new Error('Matching Stripe purchase was not found.');const[id,purchase]=entry,fullyRefunded=body.fullyRefunded===true,amountRefunded=nonNegative(body.amountRefunded);purchase.amountRefunded=Math.max(nonNegative(purchase.amountRefunded),amountRefunded);purchase.status=fullyRefunded?'refunded':purchase.amountRefunded>0?'partially_refunded':String(purchase.status||'paid');if(fullyRefunded&&!purchase.refundedAt)purchase.refundedAt=Date.now();if(body.refundId)purchase.refundId=String(body.refundId).slice(0,255);if(body.reason)purchase.refundReason=String(body.reason).slice(0,128);account.purchases[id]=purchase;rebuildInventory(account);account.lastSeenAt=Date.now();await this.ctx.storage.put('account',account);return account}
 async fetch(req){const u=new URL(req.url);let body={};if(req.method==='POST'){try{body=await req.json()}catch{body={}}}if(u.pathname==='/sync'&&req.method==='POST'){try{return Response.json({account:publicAccount(await this.sync(body.identity))})}catch(error){return Response.json({error:error.message},{status:400})}}
 if(u.pathname==='/profile'&&req.method==='POST'){try{return Response.json({account:publicAccount(await this.sync(body.identity))})}catch(error){return Response.json({error:error.message},{status:400})}}
 if(u.pathname==='/equip'&&req.method==='POST'){try{const account=await this.sync(body.identity),cosmetic=String(body.cosmetic||'default');if(!ALLOWED_COSMETICS.has(cosmetic))return Response.json({error:'Unknown booster loadout.'},{status:400});if(!(account.inventory||[]).includes(cosmetic))return Response.json({error:'That booster is not in your inventory.'},{status:403});account.equipped=cosmetic;account.lastSeenAt=Date.now();await this.ctx.storage.put('account',account);return Response.json({account:publicAccount(account)})}catch(error){return Response.json({error:error.message},{status:400})}}
 if(u.pathname==='/purchase/grant'&&req.method==='POST'){try{return Response.json({account:publicAccount(await this.grantPurchase(body))})}catch(error){return Response.json({error:error.message},{status:400})}}
 if(u.pathname==='/purchase/refund-target'&&req.method==='POST'){try{return Response.json({purchase:await this.refundTarget(body)})}catch(error){return Response.json({error:error.message},{status:400})}}
 if(u.pathname==='/purchase/refund-requested'&&req.method==='POST'){try{return Response.json({account:publicAccount(await this.markRefundRequested(body))})}catch(error){return Response.json({error:error.message},{status:400})}}
 if(u.pathname==='/purchase/refund'&&req.method==='POST'){try{return Response.json({account:publicAccount(await this.applyRefund(body))})}catch(error){return Response.json({error:error.message},{status:400})}}
 if(u.pathname==='/stats/checkpoint'&&req.method==='POST'){try{return Response.json({account:publicAccount(await this.checkpoint(body))})}catch(error){return Response.json({error:error.message},{status:400})}}
 if(u.pathname==='/stats/tournament'&&req.method==='POST'){try{return Response.json({account:publicAccount(await this.tournamentResult(body))})}catch(error){return Response.json({error:error.message},{status:400})}}
 return Response.json({error:'Not found.'},{status:404})
 }
}
