import{authenticatedIdentity}from'./auth.js';

const enc=new TextEncoder();
const PRODUCTS={
 constellation:{label:'Constellation Booster Pack',productEnv:'STRIPE_PRODUCT_CONSTELLATION',priceEnv:'STRIPE_PRICE_CONSTELLATION',grants:['constellation']},
 deadMansHand:{label:"Dead Man's Hand Booster Pack",productEnv:'STRIPE_PRODUCT_DEAD_MANS_HAND',priceEnv:'STRIPE_PRICE_DEAD_MANS_HAND',grants:['deadMansHand']},
 regalia:{label:'Regalia Booster Pack',productEnv:'STRIPE_PRODUCT_REGALIA',priceEnv:'STRIPE_PRICE_REGALIA',grants:['regalia']},
 tripleThreat:{label:'Triple Threat Booster Pack',productEnv:'STRIPE_PRODUCT_TRIPLE_THREAT',priceEnv:'STRIPE_PRICE_TRIPLE_THREAT',grants:['constellation','deadMansHand','regalia'],bundle:true}
};
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json','cache-control':'no-store'}})}
function productFor(env,key){const base=PRODUCTS[key];if(!base)return null;return{key,label:base.label,productId:String(env[base.productEnv]||''),priceId:String(env[base.priceEnv]||''),grants:[...base.grants],bundle:!!base.bundle}}
function stripeMode(env){return String(env.STRIPE_MODE||'').toLowerCase()==='live'?'live':'test'}
async function stripeRequest(env,path,{method='GET',body}={}){if(!env.STRIPE_SECRET_KEY)throw new Error('Stripe checkout is not configured yet.');const headers=new Headers({authorization:`Bearer ${env.STRIPE_SECRET_KEY}`});if(body)headers.set('content-type','application/x-www-form-urlencoded');const res=await fetch(`https://api.stripe.com/v1${path}`,{method,headers,body});let data={};try{data=await res.json()}catch{}if(!res.ok)throw new Error(data?.error?.message||`Stripe request failed (${res.status}).`);return data}
async function loadPrice(env,product){if(!product?.priceId)return null;const price=await stripeRequest(env,`/prices/${encodeURIComponent(product.priceId)}`);if(!price?.active||price?.type!=='one_time')throw new Error(`${product.label} price is not an active one-time price.`);if(product.productId&&String(price.product)!==product.productId)throw new Error(`${product.label} price does not belong to the configured Stripe product.`);return price}
async function accountProfile(env,identity){if(!env.ACCOUNTS)return null;const stub=env.ACCOUNTS.get(env.ACCOUNTS.idFromName(identity.id));const res=await stub.fetch('https://account.internal/profile',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({identity})});return await res.json()}
function accountStub(env,accountId){if(!env.ACCOUNTS)throw new Error('Account storage unavailable.');return env.ACCOUNTS.get(env.ACCOUNTS.idFromName(accountId))}
function rawHex(bytes){return Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('')}
async function hmacHex(secret,payload){const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return rawHex(new Uint8Array(await crypto.subtle.sign('HMAC',key,enc.encode(payload))))}
function sameText(a,b){a=String(a||'');b=String(b||'');if(a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0}
export async function verifyStripeSignature(raw,header,secret,toleranceSeconds=300){if(!raw||!header||!secret)return false;const fields=String(header).split(',').map(x=>x.trim()).filter(Boolean),timestamp=fields.find(x=>x.startsWith('t='))?.slice(2),signatures=fields.filter(x=>x.startsWith('v1=')).map(x=>x.slice(3));const t=Number(timestamp);if(!Number.isFinite(t)||!signatures.length||Math.abs(Math.floor(Date.now()/1000)-t)>toleranceSeconds)return false;const expected=await hmacHex(secret,`${timestamp}.${raw}`);return signatures.some(sig=>sameText(sig,expected))}
async function grantCheckout(env,session){if(session?.mode!=='payment'||session?.payment_status!=='paid')return{ignored:true};const accountId=String(session?.metadata?.account_id||session?.client_reference_id||''),purchaseKey=String(session?.metadata?.purchase_key||session?.metadata?.cosmetic||''),checkoutSessionId=String(session?.id||''),product=PRODUCTS[purchaseKey];if(!accountId||!product||!checkoutSessionId)throw new Error('Checkout metadata is incomplete.');const stub=accountStub(env,accountId),res=await stub.fetch('https://account.internal/purchase/grant',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({purchaseKey,entitlements:product.grants,checkoutSessionId,paymentIntent:session.payment_intent||null,amountTotal:session.amount_total||0,currency:session.currency||'usd',customer:session.customer||null})}),data=await res.json();if(!res.ok||data?.error)throw new Error(data?.error||'Could not grant purchased booster.');return data}
async function applyChargeRefund(env,charge){const paymentIntentId=String(typeof charge?.payment_intent==='object'?charge.payment_intent?.id:charge?.payment_intent||'');if(!paymentIntentId)return{ignored:true,reason:'No payment intent.'};const intent=await stripeRequest(env,`/payment_intents/${encodeURIComponent(paymentIntentId)}`),accountId=String(intent?.metadata?.account_id||''),source=String(intent?.metadata?.source||'');if(source!=='full-tilt-booster-shop'||!accountId)return{ignored:true,reason:'Not a Full Tilt booster payment.'};const refunds=Array.isArray(charge?.refunds?.data)?charge.refunds.data:[],latest=refunds.length?refunds[refunds.length-1]:null,stub=accountStub(env,accountId),res=await stub.fetch('https://account.internal/purchase/refund',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({paymentIntent:paymentIntentId,amountRefunded:Number(charge?.amount_refunded||0),fullyRefunded:charge?.refunded===true,refundId:latest?.id||null,reason:latest?.reason||null})}),data=await res.json();if(!res.ok||data?.error)throw new Error(data?.error||'Could not update refunded booster purchase.');return data}
async function catalog(env){const configured=!!env.STRIPE_SECRET_KEY,products=[];for(const key of Object.keys(PRODUCTS)){const p=productFor(env,key);if(!configured||!p.priceId){products.push({...p,available:false,unitAmount:null,currency:null});continue}try{const price=await loadPrice(env,p);products.push({...p,available:true,unitAmount:Number(price.unit_amount||0),currency:String(price.currency||'usd')})}catch(error){products.push({...p,available:false,unitAmount:null,currency:null,error:error.message})}}return{mode:stripeMode(env),configured,products}}
export async function handleShopApi(req,env){const u=new URL(req.url);if(!u.pathname.startsWith('/api/shop/'))return null;
 if(u.pathname==='/api/shop/catalog'&&req.method==='GET')return json(await catalog(env));
 if(u.pathname==='/api/shop/checkout'&&req.method==='POST'){const identity=await authenticatedIdentity(req,env);if(!identity)return json({error:'Discord login required.'},401);if(!env.STRIPE_SECRET_KEY)return json({error:'Stripe checkout is not configured yet.'},503);let body={};try{body=await req.json()}catch{}const purchaseKey=String(body.item||body.cosmetic||''),product=productFor(env,purchaseKey);if(!product||!product.priceId)return json({error:'That booster is not available for purchase.'},400);const profile=await accountProfile(env,identity),inventory=profile?.account?.inventory||[];if(product.grants.every(key=>inventory.includes(key)))return json({error:product.bundle?'You already own every booster in that bundle.':'You already own that booster.'},409);try{await loadPrice(env,product);const success=`${u.origin}/?shop=success&pack=${encodeURIComponent(purchaseKey)}&session_id={CHECKOUT_SESSION_ID}`,cancel=`${u.origin}/?shop=cancelled&pack=${encodeURIComponent(purchaseKey)}`,form=new URLSearchParams();form.set('mode','payment');form.set('managed_payments[enabled]','false');form.set('success_url',success);form.set('cancel_url',cancel);form.set('client_reference_id',identity.id);form.set('line_items[0][price]',product.priceId);form.set('line_items[0][quantity]','1');form.set('metadata[account_id]',identity.id);form.set('metadata[purchase_key]',purchaseKey);form.set('metadata[source]','full-tilt-booster-shop');form.set('payment_intent_data[metadata][account_id]',identity.id);form.set('payment_intent_data[metadata][purchase_key]',purchaseKey);form.set('payment_intent_data[metadata][source]','full-tilt-booster-shop');const session=await stripeRequest(env,'/checkout/sessions',{method:'POST',body:form});if(!session?.url)return json({error:'Stripe did not return a checkout URL.'},502);return json({url:session.url,id:session.id,mode:stripeMode(env)})}catch(error){return json({error:error.message||'Could not start Stripe checkout.'},502)}}
 if(u.pathname==='/api/shop/webhook'&&req.method==='POST'){if(!env.STRIPE_WEBHOOK_SECRET)return json({error:'Stripe webhook is not configured.'},503);const raw=await req.text(),valid=await verifyStripeSignature(raw,req.headers.get('stripe-signature'),env.STRIPE_WEBHOOK_SECRET);if(!valid)return json({error:'Invalid Stripe signature.'},400);let event={};try{event=JSON.parse(raw)}catch{return json({error:'Invalid Stripe payload.'},400)}try{let result={ignored:true};if(event.type==='checkout.session.completed'||event.type==='checkout.session.async_payment_succeeded')result=await grantCheckout(env,event.data?.object);else if(event.type==='charge.refunded')result=await applyChargeRefund(env,event.data?.object);console.info('stripe_webhook_processed',{eventId:event.id,type:event.type,ignored:!!result?.ignored});return json({received:true,eventId:event.id||null})}catch(error){console.error('stripe_webhook_failed',{eventId:event.id,type:event.type,error:error.message});return json({error:error.message||'Stripe fulfillment failed.'},500)}}
 return json({error:'Not found.'},404)}
