import{authenticatedIdentity}from'./auth.js';
import{accountRequest,resolveAccountId}from'./account-links.js';

const STAR_PRODUCTS={
 constellation:{label:'Constellation Booster',description:'Constellation cosmetic booster pack for Crashout Poker.',grants:['constellation'],priceEnv:'TELEGRAM_STARS_CONSTELLATION'},
 deadMansHand:{label:"Dead Man's Hand Booster",description:"Dead Man's Hand cosmetic booster pack for Crashout Poker.",grants:['deadMansHand'],priceEnv:'TELEGRAM_STARS_DEAD_MANS_HAND'},
 regalia:{label:'Regalia Booster',description:'Regalia cosmetic booster pack for Crashout Poker.',grants:['regalia'],priceEnv:'TELEGRAM_STARS_REGALIA'},
 tripleThreat:{label:'Triple Threat Booster',description:'All three premium Crashout Poker cosmetic booster packs.',grants:['constellation','deadMansHand','regalia'],priceEnv:'TELEGRAM_STARS_TRIPLE_THREAT',bundle:true}
};
const ORDER_TTL_MS=15*60*1000;
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json','cache-control':'no-store'}})}
function positiveInt(value){const n=Number(value);return Number.isSafeInteger(n)&&n>0?n:null}
export function starProduct(env,key){const base=STAR_PRODUCTS[String(key||'')];if(!base)return null;const amount=positiveInt(env?.[base.priceEnv]);return{key:String(key),label:base.label,description:base.description,grants:[...base.grants],bundle:!!base.bundle,amount,available:!!amount}}
export function starsCatalog(env){const products=Object.keys(STAR_PRODUCTS).map(key=>starProduct(env,key)),configured=!!env?.TELEGRAM_BOT_TOKEN&&!!env?.TELEGRAM_WEBHOOK_SECRET&&products.some(p=>p.available);return{configured,currency:'XTR',products}}
function accountStub(env,accountId){if(!env?.ACCOUNTS)throw new Error('Account storage unavailable.');return env.ACCOUNTS.get(env.ACCOUNTS.idFromName(String(accountId)))}
async function accountCall(env,accountId,path,body={}){const r=await accountStub(env,accountId).fetch(new Request(`https://account.internal${path}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)})),data=await r.json().catch(()=>({}));if(!r.ok||data?.error)throw new Error(data?.error||`Account request failed (${r.status}).`);return data}
async function telegramBotRequest(env,method,body={}){const token=String(env?.TELEGRAM_BOT_TOKEN||'');if(!token)throw new Error('Telegram bot token is not configured.');const r=await fetch(`https://api.telegram.org/bot${token}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),data=await r.json().catch(()=>({}));if(!r.ok||data?.ok===false)throw new Error(String(data?.description||`Telegram ${method} failed (${r.status}).`));return data.result}
function payloadFor(accountId,orderId){const value=`co1~${encodeURIComponent(String(accountId))}~${String(orderId)}`;if(new TextEncoder().encode(value).length>128)throw new Error('Stars invoice payload is too large.');return value}
export function parseStarsPayload(value=''){const parts=String(value||'').split('~');if(parts.length!==3||parts[0]!=='co1'||!/^[0-9a-f-]{36}$/i.test(parts[2]))return null;let accountId='';try{accountId=decodeURIComponent(parts[1])}catch{return null}if(!/^[A-Za-z0-9:_-]{1,96}$/.test(accountId))return null;return{accountId,orderId:parts[2]}}
function sameSecret(a,b){a=String(a||'');b=String(b||'');if(!a||a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0}
async function createInvoice(req,env){const identity=await authenticatedIdentity(req,env);if(!identity)return json({error:'Crashout Poker login required.'},401);if(String(identity.provider)!=='telegram')return json({error:'Telegram Stars checkout is available inside the Telegram Mini App.'},403);if(!env.TELEGRAM_BOT_TOKEN||!env.TELEGRAM_WEBHOOK_SECRET)return json({error:'Telegram Stars checkout is not configured yet.'},503);let body={};try{body=await req.json()}catch{}const product=starProduct(env,String(body.item||''));if(!product?.available)return json({error:'That booster does not have a Telegram Stars price yet.'},400);const profile=await accountRequest(env,identity,'/profile'),canonicalId=String(profile?.canonicalId||identity.id),inventory=profile?.account?.inventory||[];if(product.grants.every(key=>inventory.includes(key)))return json({error:product.bundle?'You already own every booster in that bundle.':'You already own that booster.'},409);const telegramUserId=String(identity.providerId||'');if(!/^\d+$/.test(telegramUserId))return json({error:'Telegram account could not be verified for payment.'},400);const orderId=crypto.randomUUID(),expiresAt=Date.now()+ORDER_TTL_MS,payload=payloadFor(canonicalId,orderId);try{await accountCall(env,canonicalId,'/stars/order/create',{orderId,purchaseKey:product.key,entitlements:product.grants,telegramUserId,stars:product.amount,expiresAt});const url=await telegramBotRequest(env,'createInvoiceLink',{title:product.label,description:product.description,payload,currency:'XTR',prices:[{label:product.label,amount:product.amount}]});if(!url)throw new Error('Telegram did not return an invoice link.');return json({url,orderId,stars:product.amount,currency:'XTR'})}catch(error){try{await accountCall(env,canonicalId,'/stars/order/cancel',{orderId})}catch{}return json({error:error.message||'Could not create Telegram Stars invoice.'},502)}}
async function precheckout(env,query){const parsed=parseStarsPayload(query?.invoice_payload);if(!parsed){await telegramBotRequest(env,'answerPreCheckoutQuery',{pre_checkout_query_id:String(query?.id||''),ok:false,error_message:'This Crashout Poker order is invalid or expired.'});return{approved:false,reason:'invalid-payload'}}try{await accountCall(env,parsed.accountId,'/stars/order/precheckout',{orderId:parsed.orderId,telegramUserId:String(query?.from?.id||''),currency:String(query?.currency||''),totalAmount:Number(query?.total_amount)});await telegramBotRequest(env,'answerPreCheckoutQuery',{pre_checkout_query_id:String(query.id),ok:true});return{approved:true}}catch(error){const message=String(error?.message||'This Crashout Poker order cannot be completed.').slice(0,180);await telegramBotRequest(env,'answerPreCheckoutQuery',{pre_checkout_query_id:String(query?.id||''),ok:false,error_message:message});return{approved:false,reason:message}}}
async function successfulPayment(env,message){const payment=message?.successful_payment,parsed=parseStarsPayload(payment?.invoice_payload);if(!payment||!parsed)throw new Error('Successful Stars payment has an invalid Crashout order reference.');const result=await accountCall(env,parsed.accountId,'/stars/order/complete',{orderId:parsed.orderId,telegramUserId:String(message?.from?.id||''),currency:String(payment.currency||''),totalAmount:Number(payment.total_amount),telegramPaymentChargeId:String(payment.telegram_payment_charge_id||''),providerPaymentChargeId:String(payment.provider_payment_charge_id||'')});console.info('telegram_stars_purchase_completed',{accountId:parsed.accountId,orderId:parsed.orderId,purchaseKey:result.purchaseKey||null,chargeId:String(payment.telegram_payment_charge_id||'').slice(-12)});return result}
async function paysupport(req,env,message){const chatId=String(message?.chat?.id||'');if(!chatId)return{ignored:true};const origin=new URL(req.url).origin;await telegramBotRequest(env,'sendMessage',{chat_id:chatId,text:`Crashout Poker payment support\n\nFor Telegram Stars purchase or refund help, open:\n${origin}/contact.html\n\nInclude the purchase reference shown in your Crashout Poker profile.`,disable_web_page_preview:true});return{sent:true}}
async function refundStars(req,env){const identity=await authenticatedIdentity(req,env);if(!identity)return json({error:'Crashout Poker login required.'},401);let body={};try{body=await req.json()}catch{}const purchaseId=String(body.purchaseId||'');if(!purchaseId)return json({error:'Purchase reference required.'},400);const canonicalId=await resolveAccountId(env,identity.id);try{const target=(await accountCall(env,canonicalId,'/purchase/refund-target',{purchaseId})).purchase;if(String(target?.source||'')!=='telegram_stars')return json({error:'That purchase was not paid with Telegram Stars.'},400);if(!target.telegramPaymentChargeId||!/^\d+$/.test(String(target.telegramUserId||'')))return json({error:'Telegram Stars refund metadata is incomplete. Contact payment support.'},400);await telegramBotRequest(env,'refundStarPayment',{user_id:Number(target.telegramUserId),telegram_payment_charge_id:String(target.telegramPaymentChargeId)});const data=await accountCall(env,canonicalId,'/purchase/refund',{checkoutSessionId:purchaseId,amountRefunded:target.amountTotal,fullyRefunded:true,refundId:target.telegramPaymentChargeId,reason:'requested_by_customer'});return json({account:data.account,refund:{id:target.telegramPaymentChargeId,status:'succeeded',source:'telegram_stars'}})}catch(error){return json({error:error.message||'Could not process Telegram Stars refund.'},400)}}
export async function handleTelegramStarsApi(req,env){const u=new URL(req.url);
 if(u.pathname==='/api/shop/stars/catalog'&&req.method==='GET')return json(starsCatalog(env));
 if(u.pathname==='/api/shop/stars/invoice'&&req.method==='POST')return createInvoice(req,env);
 if(u.pathname==='/api/shop/stars/refund'&&req.method==='POST')return refundStars(req,env);
 if(u.pathname==='/api/telegram/webhook'&&req.method==='POST'){const configured=String(env.TELEGRAM_WEBHOOK_SECRET||'');if(!configured)return json({error:'Telegram webhook is not configured.'},503);if(!sameSecret(req.headers.get('x-telegram-bot-api-secret-token'),configured))return json({error:'Invalid Telegram webhook secret.'},401);let update={};try{update=await req.json()}catch{return json({error:'Invalid Telegram update.'},400)}try{if(update.pre_checkout_query)await precheckout(env,update.pre_checkout_query);else if(update.message?.successful_payment)await successfulPayment(env,update.message);else if(/^\/paysupport(?:@\w+)?(?:\s|$)/i.test(String(update.message?.text||'')))await paysupport(req,env,update.message);return json({ok:true,updateId:update.update_id??null})}catch(error){console.error('telegram_webhook_failed',{updateId:update.update_id??null,error:error.message});return json({error:error.message||'Telegram webhook processing failed.'},500)}}
 return null}
