import React,{useEffect,useState}from'react';
import'./private-access.css';

function cleanInvite(value=''){return String(value||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6)}

export default function AccessHome({account,authLoading,authError,telegram,name,discordLink,onRefresh,onCreate,onJoin,onShop}){
 const[choice,setChoice]=useState(''),[value,setValue]=useState(''),[pending,setPending]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[upgrade,setUpgrade]=useState(false);
 const access=account?.account?.access||{},canHost=!!access.canHost,invite=access.latestInvite||access.invites?.[0]||null,hasAccess=canHost||!!invite;

 useEffect(()=>{if(!account)return;let alive=true;(async()=>{let changed=false;try{const r=await fetch('/api/access/key/redeem',{method:'POST'}),j=await r.json();if(r.ok&&j.redeemed)changed=true;else if(!r.ok&&j.error&&alive)setError(j.error)}catch{}try{const raw=sessionStorage.getItem('crashout_pending_invite');if(raw){sessionStorage.removeItem('crashout_pending_invite');const claim=JSON.parse(raw),r=await fetch('/api/access/invite/claim',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(claim)}),j=await r.json();if(r.ok)changed=true;else if(j.error&&alive)setError(j.error)}}catch{}if(changed&&alive)await onRefresh?.()})();return()=>{alive=false}},[account?.canonicalAccountId]);

 async function submitKey(){
  if(!value.trim())return setError('Enter your host key.');setBusy(true);setError('');
  try{const r=await fetch('/api/access/key/prepare',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({key:value.trim()})}),j=await r.json();if(!r.ok)return setError(j.error||'That host key could not be verified.');setValue('');if(j.redeemed){setUpgrade(false);setChoice('');await onRefresh?.()}else setPending({type:'key'})}catch{setError('Host key verification could not reach Crashout Poker.')}finally{setBusy(false)}
 }
 async function submitInvite(){
  const code=cleanInvite(value);if(code.length!==6)return setError('Enter the six-character invite code.');setBusy(true);setError('');
  try{const vr=await fetch('/api/access/invite/validate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code})}),v=await vr.json();if(!vr.ok)return setError(v.error||'That invite code could not be found.');setValue('');if(account){const cr=await fetch('/api/access/invite/claim',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind:v.kind,code:v.code,source:'code'})}),c=await cr.json();if(!cr.ok)return setError(c.error||'That invitation could not be linked.');setChoice('');await onRefresh?.()}else{sessionStorage.setItem('crashout_pending_invite',JSON.stringify({kind:v.kind,code:v.code,source:'code'}));setPending({type:'invite',kind:v.kind,code:v.code})}}catch{setError('Invite verification could not reach Crashout Poker.')}finally{setBusy(false)}
 }
 if(authLoading)return <div className="accountLoading">Checking private access…</div>;
 if(pending)return <div className="privateLoginStep"><span className="entryEyebrow">ACCESS VERIFIED</span><h2>Now link your account.</h2><p>{pending.type==='key'?'This host key will be linked to the account you use next. Once linked, it cannot grant access to another account':'Your private invitation is ready. Log in and it will be attached to your Crashout Poker account.'}</p>{telegram?<button className="discordLogin" onClick={()=>location.reload()}><span>↻</span> Continue with Telegram</button>:<a className="discordLogin" href="/api/auth/discord"><span>☁</span> Continue with Discord</a>}<button className="accessBack" onClick={()=>{setPending(null);setChoice('');setError('')}}>Use a different code</button>{error&&<small className="authError">{error}</small>}</div>;
 if(!hasAccess||upgrade)return <div className="privateGate"><span className="entryEyebrow">PRIVATE ACCESS ONLY</span><h2>{upgrade?(choice==='invite'?'Enter an invite code.':'Enter a host key.'):'You need an invite.'}</h2><p>{upgrade?(choice==='invite'?'Link another private table or tournament to this Crashout account.':'A new one-time or permanent host key will be linked to this Crashout account.'):'Crashout Poker is private Hold’em. Enter a host key or the invite code for the game you were sent.'}</p>{!upgrade&&<div className="privateGateChoices"><button className={choice==='key'?'active':''} onClick={()=>{setChoice('key');setValue('');setError('')}}><b>ENTER KEY</b><small>Host a private table or tournament</small></button><button className={choice==='invite'?'active':''} onClick={()=>{setChoice('invite');setValue('');setError('')}}><b>ENTER INVITE CODE</b><small>Open the private game you were invited to</small></button></div>}{choice&&<div className="privateCodeEntry"><label>{choice==='key'?'HOST ACCESS KEY':'PRIVATE INVITE CODE'}</label><input value={value} onChange={e=>setValue(choice==='invite'?cleanInvite(e.target.value):e.target.value.toUpperCase())} placeholder={choice==='key'?'CRASH-XXXXX-XXXXX-XXXXX-XXXXX':'ABC123'} autoCapitalize="characters" autoCorrect="off"/><button disabled={busy} onClick={choice==='key'?submitKey:submitInvite}>{busy?'VERIFYING…':choice==='key'?'VERIFY KEY':'VERIFY INVITE'}</button></div>}{account&&<small className="privateSignedIn">Signed in as {name}. Valid access will be linked to this account.</small>}{upgrade&&<button className="accessBack" onClick={()=>{setUpgrade(false);setChoice('');setError('')}}>Back to my private game</button>}{(error||authError)&&<small className="authError">{error||authError}</small>}</div>;
 if(canHost)return <><span className="entryEyebrow">AUTHORIZED HOST</span><h2>{name}</h2><p>{access.permanentHost?'Permanent host access • Create private tables and tournaments.':Number(access.hostCredits||0)+' one-time host credit'+(Number(access.hostCredits||0)===1?'':'s')+' available.'}</p><div className="entryActions"><button onClick={onCreate}>Create Game<small>Host a table or tournament</small></button><button onClick={onJoin}>Join Game<small>Enter a private game code</small></button></div>{telegram&&(discordLink?<div className="providerLinkPrompt linked"><b>DISCORD LINKED</b><span>{discordLink.username?'@'+discordLink.username:discordLink.displayName} • one Crashout Poker record across Telegram and the website</span></div>:<div className="providerLinkPrompt"><div><b>CONNECT YOUR CRASHOUT ACCOUNT</b><span>Link Discord to combine your website cosmetics, stats and poker history with this Telegram identity.</span></div><a href="/api/auth/link/discord">Link Discord</a></div>)}<button className="shopLaunch" onClick={onShop}><span>{telegram?'⭐':'♠'}</span><b>Booster Shop</b><small>{telegram?'Pay securely with Telegram Stars':'Cosmetics, packs & Triple Threat bundle'}</small><em>›</em></button></>;
 return <><span className="entryEyebrow">PRIVATE INVITE</span><h2>{name}</h2><p>You&apos;re cleared for {invite.kind==='tournament'?'Tournament':'Table'} {invite.code}. Your invitation is linked to this account.</p><div className="entryActions privatePlayerActions"><button onClick={()=>{location.hash='#/'+invite.kind+'/'+invite.code}}>Go To My {invite.kind==='tournament'?'Tournament':'Table'}<small>{invite.code} • private access</small></button></div><button className="shopLaunch" onClick={onShop}><span>{telegram?'⭐':'♠'}</span><b>Booster Shop</b><small>{telegram?'Pay securely with Telegram Stars':'Cosmetics, packs & Triple Threat bundle'}</small><em>›</em></button><div className="accessUpgradeRow"><button className="accessUpgrade" onClick={()=>{setUpgrade(true);setChoice('invite');setValue('');setError('')}}>Enter another invite code</button><button className="accessUpgrade" onClick={()=>{setUpgrade(true);setChoice('key');setValue('');setError('')}}>Have a host key? Enter it here</button></div></>
}
