import React,{useEffect,useState}from'react';
import'./styles.css';
import'./stats.css';
import'./social.css';
import Lobby from'./Lobby.jsx';
import{StatsPanel,HistoryPanel,ChatPanel}from'./TablePanels.jsx';
import{TableTopbar,InfoStrip,PokerFelt,TableHUD}from'./TableSurface.jsx';
import{sessionToken,rememberPlayerSession,rememberSpectatorSession,rememberRouteSession}from'./session.js';
import{useTableConnection}from'./useTableConnection.js';
const RANKS='23456789TJQKA',HAND_NAMES=['HIGH CARD','ONE PAIR','TWO PAIR','THREE OF A KIND','STRAIGHT','FLUSH','FULL HOUSE','FOUR OF A KIND','STRAIGHT FLUSH'];
function handStrength(cards){const valid=(cards||[]).filter(Boolean);if(valid.length<2)return'';const rs=valid.map(c=>RANKS.indexOf(c[0])+2).sort((a,b)=>b-a),suits={};for(const c of valid)(suits[c.slice(-1)]??=[]).push(RANKS.indexOf(c[0])+2);const counts={};rs.forEach(r=>counts[r]=(counts[r]||0)+1);const uniq=[...new Set(rs)];if(uniq.includes(14))uniq.push(1);let straight=0;for(let i=0;i<=uniq.length-5;i++)if(uniq.slice(i,i+5).every((v,j,a)=>j===0||a[j-1]-v===1)){straight=uniq[i];break}let flush=[];for(const a of Object.values(suits))if(a.length>=5)flush=a.sort((a,b)=>b-a);if(flush.length){const u=[...new Set(flush)];if(u.includes(14))u.push(1);for(let i=0;i<=u.length-5;i++)if(u.slice(i,i+5).every((v,j,a)=>j===0||a[j-1]-v===1))return HAND_NAMES[8]}const groups=Object.entries(counts).map(([r,c])=>[c,+r]).sort((a,b)=>b[0]-a[0]||b[1]-a[1]),trips=groups.filter(g=>g[0]>=3),pairs=groups.filter(g=>g[0]>=2);if(groups[0]?.[0]===4)return HAND_NAMES[7];if(trips.length&&pairs.some(g=>g[1]!==trips[0][1]))return HAND_NAMES[6];if(flush.length)return HAND_NAMES[5];if(straight)return HAND_NAMES[4];if(trips.length)return HAND_NAMES[3];if(pairs.length>=2)return HAND_NAMES[2];if(pairs.length)return HAND_NAMES[1];return HAND_NAMES[0]}
function nextLive(players,i){for(let k=1;k<=players.length;k++){const n=(i+k)%players.length;if(!players[n]?.eliminated)return n}return i}
function positions(state){if(!state?.started||!state.players.length)return{};const alive=state.players.filter(p=>!p.eliminated),d=state.dealerIndex;let sb,bb;if(alive.length===2){sb=d;bb=nextLive(state.players,sb)}else{sb=nextLive(state.players,d);bb=nextLive(state.players,sb)}return{[d]:'D',[sb]:(d===sb?'D/SB':'SB'),[bb]:'BB'}}
function fmtTime(ms){const s=Math.max(0,Math.ceil(ms/1000));return`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
export default function App(){const[view,setView]=useState('home'),[code,setCode]=useState('');useEffect(()=>{const route=()=>{const m=location.hash.match(/^#\/table\/([A-Z0-9]+)/i);if(m){setView('table');setCode(m[1].toUpperCase())}else setView('home')};route();addEventListener('hashchange',route);return()=>removeEventListener('hashchange',route)},[]);if(view==='table')return <Table code={code} onExit={()=>{location.hash='';setView('home')}}/>;return <Lobby code={code} setCode={setCode}/>}
function Table({code,onExit}){const params=new URLSearchParams(location.hash.split('?')[1]||''),queryToken=params.get('token')||'',savedToken=sessionToken(code),token=queryToken||savedToken;const{state,error:err,setError:setErr,realtime,action}=useTableConnection(code,token),[raise,setRaise]=useState(''),[joinName,setJoinName]=useState(localStorage.getItem('ftp_name')||''),[joining,setJoining]=useState(false),[watching,setWatching]=useState(false),[now,setNow]=useState(Date.now()),[copied,setCopied]=useState(false),[showHistory,setShowHistory]=useState(false),[showStats,setShowStats]=useState(false),[showChat,setShowChat]=useState(true),[chatDraft,setChatDraft]=useState('');
useEffect(()=>{if(queryToken)rememberRouteSession(code,queryToken)},[code,queryToken]);useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),200);return()=>clearInterval(id)},[]);
async function joinFromInvite(){const n=joinName.trim();if(!n)return setErr('Enter a display name to take a seat.');setJoining(true);const r=await fetch(`/api/tables/${code}/join`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:n})}),j=await r.json();setJoining(false);if(!r.ok)return setErr(j.error||'Could not take a seat.');localStorage.setItem('ftp_name',n);rememberPlayerSession(code,j.token);location.hash=`#/table/${code}?token=${j.token}`;location.reload()}
async function spectateFromInvite(){const n=joinName.trim();if(!n)return setErr('Enter a display name to watch the table.');setWatching(true);const r=await fetch(`/api/tables/${code}/spectate`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:n})}),j=await r.json();setWatching(false);if(!r.ok)return setErr(j.error||'Could not watch table.');localStorage.setItem('ftp_name',n);rememberSpectatorSession(code,j.token);location.hash=`#/table/${code}?token=${j.token}`;location.reload()}
async function sendChat(){const message=chatDraft.trim();if(!message)return;const r=await fetch(`/api/tables/${code}/chat`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token,message})}),j=await r.json();if(!r.ok)return setErr(j.error||'Could not send message.');setChatDraft('')}
async function performAction(type,amount,targetId){const ok=await action(type,amount,targetId);if(ok&&type==='raise')setRaise('')}
if(!state)return <main className="tablePage"><button className="ghost top" onClick={onExit}>← Lobby</button><div className="loading">{err||'Pulling up a chair…'}</div></main>;
const me=state.players.find(p=>p.token===token),viewer=state.viewer,isSpectator=viewer?.type==='spectator',shareLink=`${location.origin}${location.pathname}#/table/${code}`;
if(!me&&!isSpectator)return <main className="tablePage"><div className="topbar"><button className="ghost" onClick={onExit}>← Lobby</button><div><b>TABLE {code}</b><span> Private Full Tilt tournament • {realtime==='live'?'LIVE':'CONNECTING…'}</span></div></div><section className="inviteJoin"><div className="mark bigMark">FT</div><span className="eyebrow">YOU'VE BEEN INVITED</span><h2>{state.started?'Watch or join the rail':'Take a seat at'} Table {code}</h2><p>{state.started?'The tournament is already running. Seats are closed, but the rail is open.':'Take a seat now, or watch from the rail without affecting the game.'}</p><input value={joinName} onChange={e=>setJoinName(e.target.value)} placeholder="Your display name" maxLength={24} autoFocus/>{!state.started&&<button className="primary" disabled={joining||watching} onClick={joinFromInvite}>{joining?'Taking seat…':'Take My Seat'}</button>}<button className="watchButton" disabled={joining||watching} onClick={spectateFromInvite}>{watching?'Joining rail…':'Watch Table'}</button>{err&&<div className="inlineError">{err}</div>}<small>{state.players.length}/9 players seated • {state.spectatorCount||0} watching</small></section></main>;
const strength=me?handStrength([...(me.cards||[]),...(state.board||[])]):'',turnLeft=state.turnDeadline&&!state.paused?Math.max(0,Math.ceil((state.turnDeadline-now)/1000)):null,showdownLeft=state.phaseDeadline&&state.street==='showdown'?Math.max(0,((state.phaseDeadline-now)/1000).toFixed(1)):null,pos=positions(state),alive=state.players.filter(p=>!p.eliminated).length,levels=Array.isArray(state.blindStructure)&&state.blindStructure.length?state.blindStructure:[[state.smallBlind,state.bigBlind]],next=levels[Math.min(levels.length-1,(state.blindLevel||0)+1)],blindLeft=state.started&&state.levelStartedAt&&!state.paused?fmtTime(state.blindMinutes*60000-(now-state.levelStartedAt)):'—',finished=state.street==='finished';
async function copyInvite(){await navigator.clipboard?.writeText(shareLink);setCopied(true);setTimeout(()=>setCopied(false),1500)}
return <main className="tablePage"><TableTopbar code={code} state={state} realtime={realtime} blindLeft={blindLeft} next={next} copied={copied} onCopy={copyInvite} onExit={onExit}/>{isSpectator&&<div className="spectatorRibbon">◉ WATCHING AS {viewer.name.toUpperCase()} • READ ONLY</div>}<InfoStrip alive={alive} state={state} blindLeft={blindLeft}/><PokerFelt state={state} finished={finished} showdownLeft={showdownLeft} pos={pos} turnLeft={turnLeft} me={me} onKick={id=>performAction('kick',0,id)}/><TableHUD state={state} me={me} isSpectator={isSpectator} strength={strength} turnLeft={turnLeft} raise={raise} setRaise={setRaise} showStats={showStats} setShowStats={setShowStats} showHistory={showHistory} setShowHistory={setShowHistory} showChat={showChat} setShowChat={setShowChat} onAction={performAction}/><div className={`belowTable ${showChat?'withChat':''}`}><div className="tablePanels">{(showStats||finished)&&<StatsPanel stats={state.tournamentStats} finished={finished}/>} {showHistory&&<HistoryPanel history={state.handHistory}/>}</div>{showChat&&<ChatPanel messages={state.chat} draft={chatDraft} setDraft={setChatDraft} onSend={sendChat} viewer={viewer}/>}</div>{err&&<div className="toast" onClick={()=>setErr('')}>{err}</div>}</main>}
