import React,{useEffect,useMemo,useState}from'react';
import'./shop.css';

const PACK_COPY={constellation:'Cold stars. Clean lines. Zero mercy.',deadMansHand:'Skulls, smoke and a seat nobody wants to face.',regalia:'Royal gold for players who intend to own the room.'};
const PACK_LABEL={constellation:'Constellation',deadMansHand:"Dead Man's Hand",regalia:'Regalia'};
function money(amount,currency='usd'){if(!Number.isFinite(Number(amount)))return'';try{return new Intl.NumberFormat(undefined,{style:'currency',currency:String(currency).toUpperCase()}).format(Number(amount)/100)}catch{return`$${(Number(amount)/100).toFixed(2)}`}}
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
export default function BoosterShop({packs,account,onAccount,onEquip,setMsg}){const[catalog,setCatalog]=useState({configured:false,mode:'test',products:[]}),[loading,setLoading]=useState(true),[busy,setBusy]=useState('');
 useEffect(()=>{let live=true;(async()=>{try{const r=await fetch('/api/shop/catalog',{cache:'no-store'}),j=await r.json();if(live&&r.ok)setCatalog(j)}catch{}finally{if(live)setLoading(false)}})();return()=>{live=false}},[]);
 const byKey=useMemo(()=>Object.fromEntries((catalog.products||[]).map(x=>[x.key,x])),[catalog]);
 useEffect(()=>{const q=new URLSearchParams(location.search),state=q.get('shop'),pack=q.get('pack');if(!state)return;if(state==='cancelled'){setMsg('Checkout cancelled. Nothing was charged.');history.replaceState(null,'',location.pathname+location.hash);return}if(state!=='success'||!pack)return;let cancelled=false;(async()=>{setMsg('Payment received. Unlocking your booster…');for(const delay of[0,500,1200,2500,5000]){if(delay)await sleep(delay);if(cancelled)return;try{const r=await fetch('/api/auth/me',{cache:'no-store'}),j=await r.json();if(r.ok){onAccount?.(j);if(j.account?.inventory?.includes(pack)){setMsg(`${PACK_LABEL[pack]||'Booster'} unlocked.`);history.replaceState(null,'',location.pathname+location.hash);return}}}catch{}}setMsg('Payment completed. Your booster is still syncing; refresh in a moment if it does not appear.');history.replaceState(null,'',location.pathname+location.hash)})();return()=>{cancelled=true}},[onAccount,setMsg]);
 async function buy(pack){setBusy(pack.key);try{const r=await fetch('/api/shop/checkout',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({cosmetic:pack.key})}),j=await r.json();if(!r.ok||!j.url){setMsg(j.error||'Could not start checkout.');return}location.assign(j.url)}catch{setMsg('Could not reach checkout.')}finally{setBusy('')}}
 return <section className="shopSection"><div className="sectionHead"><div><span>BOOSTER SHOP</span><h2>Build your table identity.</h2><p>Booster packs unlock coordinated card backs, chips, plaques and avatar frames. Cosmetics never change gameplay.</p></div><div className="shopBadge">{catalog.mode==='test'?'SANDBOX SHOP':'SHOP'}</div></div><div className="boosterGrid">{packs.map(pack=>{const price=byKey[pack.key],owned=pack.owned,label=price?.unitAmount!=null?money(price.unitAmount,price.currency):'';return <article className="boosterPack" key={pack.key}><div className="packArt"><img src={pack.art} alt=""/><span>{owned?'OWNED':'BOOSTER'}</span></div><div><h3>{pack.label}</h3><p>{PACK_COPY[pack.key]}</p>{!owned&&label&&<strong className="packPrice">{label}</strong>}</div>{owned?<button onClick={()=>onEquip(pack.key)} disabled={account.account?.equipped===pack.key}>{account.account?.equipped===pack.key?'EQUIPPED':'EQUIP'}</button>:<button disabled={loading||busy===pack.key||!catalog.configured||!price?.available} onClick={()=>buy(pack)}>{busy===pack.key?'OPENING CHECKOUT…':loading?'LOADING…':!catalog.configured?'SHOP SETUP':!price?.available?'UNAVAILABLE':`BUY ${label}`}</button>}</article>})}</div><div className="shopLegal"><span>{catalog.mode==='test'?'Sandbox checkout • no real charges':'Secure checkout powered by Stripe'}</span><nav><a href="/purchases.html">Purchases</a><a href="/refunds.html">Refunds</a><a href="/terms.html">Terms</a><a href="/privacy.html">Privacy</a><a href="/contact.html">Support</a></nav></div></section>}
