import React,{useEffect,useMemo,useState}from'react';
import'./shop.css';
import{assets}from'./assets.js';

const PACK_COPY={constellation:'Cold stars. Clean lines. Zero mercy.',deadMansHand:'Skulls, smoke and a seat nobody wants to face.',regalia:'Royal gold for players who intend to own the room.',tripleThreat:'One purchase. All three premium booster packs: Constellation, Dead Man’s Hand and Regalia.'};
const PACK_LONG_COPY={constellation:'A cosmic Full Tilt identity built from luminous gold geometry, deep violet space tones and clean celestial details.',deadMansHand:'A darker table identity built around smoke, skeletal royalty and heavy gold accents designed to make the seat feel dangerous.',regalia:'A prestige set built around royal purple, polished gold and ornate Full Tilt detailing for a high-status table presence.',tripleThreat:'The complete premium collection. Triple Threat unlocks Constellation, Dead Man’s Hand and Regalia together in one purchase.'};
const PACK_LABEL={constellation:'Constellation',deadMansHand:"Dead Man's Hand",regalia:'Regalia',tripleThreat:'Triple Threat'};
const SINGLE_KEYS=['constellation','deadMansHand','regalia'];
function money(amount,currency='usd'){if(!Number.isFinite(Number(amount)))return'';try{return new Intl.NumberFormat(undefined,{style:'currency',currency:String(currency).toUpperCase()}).format(Number(amount)/100)}catch{return`$${(Number(amount)/100).toFixed(2)}`}}
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
function PackContents({packKey,compact=false}){const skin=assets.cosmetics[packKey];if(!skin)return null;const chips=Object.entries(skin.chips||{}),plaques=Object.entries(skin.plaques||{});return <div className={`detailContents${compact?' compact':''}`}>
 <article className="detailCosmetic"><div className="detailPreview cardPreview"><img src={skin.cardBack} alt={`${PACK_LABEL[packKey]} card back`}/></div><span>CARD BACK</span><h4>{PACK_LABEL[packKey]} Card Back</h4><p>Premium card-back design used across your table.</p></article>
 <article className="detailCosmetic"><div className="detailPreview framePreview"><img src={skin.avatarFrame} alt={`${PACK_LABEL[packKey]} avatar frame`}/></div><span>AVATAR FRAME</span><h4>{PACK_LABEL[packKey]} Avatar Frame</h4><p>Your matching player avatar surround.</p></article>
 <article className="detailCosmetic"><div className="detailPreview chipPreview">{chips.map(([name,src])=><img key={name} src={src} alt={`${name} chip`}/>)}</div><span>CHIP SET • {chips.length} DESIGNS</span><h4>{PACK_LABEL[packKey]} Chips</h4><p>The complete coordinated chip set.</p></article>
 <article className="detailCosmetic"><div className="detailPreview plaquePreview">{plaques.map(([name,src])=><img key={name} src={src} alt={`${name} player plaque`}/>)}</div><span>PLAYER PLAQUES • {plaques.length} STATES</span><h4>{PACK_LABEL[packKey]} Player Plaques</h4><p>Idle, active, folded and all-in table states.</p></article>
 </div>}
function BoosterDetails({detailKey,item,packs,account,loading,busy,catalog,onClose,onBuy,onEquip}){if(!detailKey)return null;const bundle=detailKey==='tripleThreat',owned=bundle?SINGLE_KEYS.every(key=>account.account?.inventory?.includes(key)):account.account?.inventory?.includes(detailKey),equipped=!bundle&&account.account?.equipped===detailKey,label=item?.unitAmount!=null?money(item.unitAmount,item.currency):'',pack=packs.find(x=>x.key===detailKey);return <div className="detailShade" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className={`boosterDetails${bundle?' bundleDetails':''}`} role="dialog" aria-modal="true" aria-label={`${PACK_LABEL[detailKey]} details`}>
 <button className="detailClose" onClick={onClose} aria-label="Back to Booster Shop">×</button>
 <header className="detailHero"><div className={`detailHeroArt${bundle?' tripleHeroArt':''}`}>{bundle?packs.map((p,i)=><img key={p.key} src={p.art} alt="" style={{'--detail-index':i}}/>):<img src={pack?.art||assets.cosmetics[detailKey]?.cardBack} alt=""/>}<span>{bundle?'TRIPLE THREAT BUNDLE':'PREMIUM BOOSTER'}</span></div><div className="detailHeroCopy"><small>{bundle?'FULL COLLECTION':'FULL TILT COSMETICS'}</small><h2>{PACK_LABEL[detailKey]}</h2><p className="detailTagline">{PACK_COPY[detailKey]}</p><p>{PACK_LONG_COPY[detailKey]}</p>{label&&<strong className="detailPrice">{label}</strong>}<div className={`detailStatus ${owned?'owned':''}`}>{equipped?'EQUIPPED':owned?(bundle?'ALL 3 OWNED':'OWNED'):'AVAILABLE'}</div></div></header>
 {bundle?<div className="bundleContents"><div className="detailSectionHead"><span>EVERYTHING INCLUDED</span><h3>Three complete booster packs.</h3><p>Triple Threat grants every cosmetic shown below. Each pack remains independently selectable in your loadout.</p></div>{SINGLE_KEYS.map(key=><section className="bundleDetailPack" key={key}><div className="bundleDetailTitle"><img src={assets.cosmetics[key].cardBack} alt=""/><div><span>INCLUDED BOOSTER</span><h3>{PACK_LABEL[key]}</h3><p>{PACK_COPY[key]}</p></div></div><PackContents packKey={key} compact/></section>)}</div>:<><div className="detailSectionHead"><span>INCLUDED COSMETICS</span><h3>Everything in the pack.</h3><p>One purchase permanently adds this entire coordinated set to your Discord-linked Full Tilt account.</p></div><PackContents packKey={detailKey}/></>}
 <footer className="detailFooter"><button className="detailBack" onClick={onClose}>BACK TO SHOP</button>{owned?(bundle?<button className="detailPrimary" disabled>ALL 3 OWNED</button>:<button className="detailPrimary" disabled={equipped} onClick={()=>onEquip(detailKey)}>{equipped?'EQUIPPED':'EQUIP BOOSTER'}</button>):<button className="detailPrimary" disabled={loading||busy===detailKey||!catalog.configured||!item?.available} onClick={()=>onBuy(item)}>{busy===detailKey?'OPENING CHECKOUT…':!catalog.configured?'SHOP SETUP':!item?.available?'UNAVAILABLE':`BUY NOW ${label}`}</button>}</footer>
 </section></div>}
export default function BoosterShop({packs,account,onAccount,onEquip,setMsg}){const[catalog,setCatalog]=useState({configured:false,mode:'test',products:[]}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[detailKey,setDetailKey]=useState('');
 useEffect(()=>{let live=true;(async()=>{try{const r=await fetch('/api/shop/catalog',{cache:'no-store'}),j=await r.json();if(live&&r.ok)setCatalog(j)}catch{}finally{if(live)setLoading(false)}})();return()=>{live=false}},[]);
 const byKey=useMemo(()=>Object.fromEntries((catalog.products||[]).map(x=>[x.key,x])),[catalog]);
 useEffect(()=>{const q=new URLSearchParams(location.search),state=q.get('shop'),purchaseKey=q.get('pack');if(!state)return;if(state==='cancelled'){setMsg('Checkout cancelled. Nothing was charged.');history.replaceState(null,'',location.pathname+location.hash);return}if(state!=='success'||!purchaseKey)return;let cancelled=false;(async()=>{setMsg('Payment received. Unlocking your booster…');const expected=byKey[purchaseKey]?.grants?.length?byKey[purchaseKey].grants:[purchaseKey];for(const delay of[0,500,1200,2500,5000]){if(delay)await sleep(delay);if(cancelled)return;try{const r=await fetch('/api/auth/me',{cache:'no-store'}),j=await r.json();if(r.ok){onAccount?.(j);if(expected.every(key=>j.account?.inventory?.includes(key))){setMsg(`${PACK_LABEL[purchaseKey]||'Booster'} unlocked.`);history.replaceState(null,'',location.pathname+location.hash);return}}}catch{}}setMsg('Payment completed. Your booster is still syncing; refresh in a moment if it does not appear.');history.replaceState(null,'',location.pathname+location.hash)})();return()=>{cancelled=true}},[onAccount,setMsg,byKey]);
 async function buy(item){setBusy(item.key);try{const r=await fetch('/api/shop/checkout',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({item:item.key})}),j=await r.json();if(!r.ok||!j.url){setMsg(j.error||'Could not start checkout.');return}location.assign(j.url)}catch{setMsg('Could not reach checkout.')}finally{setBusy('')}}
 function buttonLabel(item,owned){const label=item?.unitAmount!=null?money(item.unitAmount,item.currency):'';if(owned)return item.bundle?'ALL 3 OWNED':'OWNED';if(busy===item.key)return'OPENING CHECKOUT…';if(loading)return'LOADING…';if(!catalog.configured)return'SHOP SETUP';if(!item?.available)return'UNAVAILABLE';return`BUY ${label}`}
 const bundle=byKey.tripleThreat,bundleOwned=!!bundle?.grants?.length&&bundle.grants.every(key=>account.account?.inventory?.includes(key)),selected=detailKey?byKey[detailKey]||{key:detailKey}:null;
 return <section className="shopSection"><div className="sectionHead"><div><span>BOOSTER SHOP</span><h2>Build your table identity.</h2><p>Booster packs unlock coordinated card backs, chips, plaques and avatar frames. Cosmetics never change gameplay.</p></div><div className="shopBadge">{catalog.mode==='test'?'SANDBOX SHOP':'SHOP'}</div></div><div className="boosterGrid">{packs.map(pack=>{const item=byKey[pack.key]||{key:pack.key},owned=pack.owned,label=item?.unitAmount!=null?money(item.unitAmount,item.currency):'';return <article className="boosterPack" key={pack.key}><div className="packArt"><img src={pack.art} alt=""/><span>{owned?'OWNED':'BOOSTER'}</span></div><div><h3>{pack.label}</h3><p>{PACK_COPY[pack.key]}</p>{!owned&&label&&<strong className="packPrice">{label}</strong>}<button className="packMore" onClick={()=>setDetailKey(pack.key)}>VIEW INCLUDED COSMETICS</button></div><div className="packActions">{owned?<button onClick={()=>onEquip(pack.key)} disabled={account.account?.equipped===pack.key}>{account.account?.equipped===pack.key?'EQUIPPED':'EQUIP'}</button>:<button disabled={loading||busy===pack.key||!catalog.configured||!item?.available} onClick={()=>buy(item)}>{buttonLabel(item,false)}</button>}</div></article>})}{bundle&&<article className="boosterPack bundlePack"><div className="packArt bundleArt">{packs.map((pack,i)=><img key={pack.key} src={pack.art} alt="" style={{'--bundle-index':i}}/>)}<span>{bundleOwned?'OWNED':'BUNDLE'}</span></div><div><h3>Triple Threat</h3><p>{PACK_COPY.tripleThreat}</p>{!bundleOwned&&bundle.unitAmount!=null&&<strong className="packPrice">{money(bundle.unitAmount,bundle.currency)}</strong>}<button className="packMore" onClick={()=>setDetailKey('tripleThreat')}>VIEW EVERYTHING INCLUDED</button></div><div className="packActions"><button disabled={bundleOwned||loading||busy==='tripleThreat'||!catalog.configured||!bundle.available} onClick={()=>buy(bundle)}>{buttonLabel(bundle,bundleOwned)}</button></div></article>}</div><div className="shopLegal"><span>{catalog.mode==='test'?'Sandbox checkout • no real charges':'Secure checkout powered by Stripe'}</span><nav><a href="/purchases.html">Purchases</a><a href="/refunds.html">Refunds</a><a href="/terms.html">Terms</a><a href="/privacy.html">Privacy</a><a href="/contact.html">Support</a></nav></div>{detailKey&&<BoosterDetails detailKey={detailKey} item={selected} packs={packs} account={account} loading={loading} busy={busy} catalog={catalog} onClose={()=>setDetailKey('')} onBuy={buy} onEquip={onEquip}/>}</section>}
