import'./fx.css';
let audioCtx=null,last={hand:null,board:0,pot:0,folded:new Set,allin:new Set,street:'',bets:new Map,stacks:new Map},muted=localStorage.getItem('ftp_sound')!=='on',frame=0;
function ctx(){const C=window.AudioContext||window.webkitAudioContext;if(!C)return null;audioCtx??=new C();return audioCtx}
function tone(freq,duration=.06,type='sine',gain=.03,delay=0){if(muted)return;const c=ctx();if(!c)return;if(c.state==='suspended')c.resume().catch(()=>{});if(c.state!=='running')return;const o=c.createOscillator(),g=c.createGain(),t=c.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(.0001,t);g.gain.linearRampToValueAtTime(gain,t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g).connect(c.destination);o.start(t);o.stop(t+duration+.03)}
function cue(name){if(name==='deal'){tone(520,.045,'triangle',.022);tone(660,.045,'triangle',.02,.05)}else if(name==='card'){tone(430,.045,'triangle',.023);tone(540,.04,'triangle',.018,.04)}else if(name==='chips'){tone(920,.025,'square',.009);tone(1180,.025,'square',.007,.022)}else if(name==='fold')tone(170,.07,'triangle',.015);else if(name==='allin'){tone(220,.11,'sawtooth',.014);tone(330,.13,'sawtooth',.012,.08)}else if(name==='showdown'){tone(392,.1,'triangle',.022);tone(523,.14,'triangle',.021,.1);tone(659,.2,'triangle',.02,.2)}else if(name==='win'){tone(523,.13,'triangle',.025);tone(659,.16,'triangle',.023,.11);tone(784,.25,'triangle',.022,.23)}}
function pulse(el,cls,ms=700,delay=0){if(!el)return;el.classList.remove(cls);void el.offsetWidth;if(delay)el.style.setProperty('--fx-delay',`${delay}ms`);el.classList.add(cls);setTimeout(()=>{el.classList.remove(cls);if(delay)el.style.removeProperty('--fx-delay')},ms+delay+80)}
function pulseAll(nodes,cls,step=65,ms=700){[...nodes].forEach((el,i)=>pulse(el,cls,ms,i*step))}
function center(r){return{x:r.left+r.width/2,y:r.top+r.height/2}}
function flyChip(from,to,kind='toPot'){if(!from||!to)return;const a=center(from),b=center(to),ghost=document.createElement('div');ghost.className=`fxFlyingChip ${kind}`;ghost.style.left=`${a.x}px`;ghost.style.top=`${a.y}px`;ghost.style.setProperty('--fx-x',`${b.x-a.x}px`);ghost.style.setProperty('--fx-y',`${b.y-a.y}px`);document.body.appendChild(ghost);requestAnimationFrame(()=>ghost.classList.add('go'));setTimeout(()=>ghost.remove(),620)}
function parseMoney(t){return Number(String(t||'').replace(/[^0-9]/g,''))||0}
function ensureToggle(){const top=document.querySelector('.topbar');if(!top||top.querySelector('.soundToggle'))return;const b=document.createElement('button');b.className='ghost soundToggle';const draw=()=>{b.textContent=muted?'🔇 Sound':'🔊 Sound'};draw();b.onclick=()=>{muted=!muted;localStorage.setItem('ftp_sound',muted?'off':'on');if(!muted){const c=ctx();c?.resume?.();cue('card')}draw()};top.appendChild(b)}
function transition(el,cls,ms=380){if(!el)return;el.classList.remove(cls);void el.offsetWidth;el.classList.add(cls);setTimeout(()=>el.classList.remove(cls),ms)}
function scan(){frame=0;ensureToggle();const felt=document.querySelector('.felt'),handText=document.querySelector('.topbar b')?.textContent||'',hand=handText.match(/HAND #(\d+)/)?.[1]||null,board=document.querySelectorAll('.board .card').length,potEl=document.querySelector('.pot'),pot=parseMoney(potEl?.textContent),street=document.querySelector('.infoStrip span:nth-child(3) b')?.textContent||'',potRect=potEl?.getBoundingClientRect();
 if(last.hand!==null&&hand&&hand!==last.hand){transition(felt,'handTransition',420);cue('deal');pulseAll(document.querySelectorAll('.hole .card'),'fxDeal',70,720)}
 if(last.street&&street&&street!==last.street&&street!=='SHOWDOWN'&&street!=='FINISHED')transition(felt,'streetTransition',390);
 if(board>last.board){cue('card');pulseAll([...document.querySelectorAll('.board .card')].slice(last.board),'fxBoardDeal',65,720)}
 if(pot>last.pot&&last.pot!==0){cue('chips');pulse(potEl,'fxPotPulse',620)}
 const bets=new Map;document.querySelectorAll('.tableBet[data-bet-seat]').forEach(b=>{const i=Number(b.dataset.betSeat),value=parseMoney(b.textContent),rect=b.getBoundingClientRect();bets.set(i,{value,rect});const prev=last.bets.get(i);if(!prev||value>prev.value){const seat=document.querySelector(`.seat[data-seat-index="${i}"]`)?.getBoundingClientRect();if(seat){cue('chips');flyChip(seat,rect,'toBet');pulse(b,'fxBetLand',420)}}});
 if(potRect&&last.bets.size){for(const[i,prev]of last.bets){if(prev.value>0&&!bets.has(i)&&(pot>=last.pot||street!==last.street)){flyChip(prev.rect,potRect,'toPot')}}}
 const folded=new Set,allin=new Set,stacks=new Map;document.querySelectorAll('.seat[data-seat-index]').forEach((s,i)=>{const key=s.querySelector('b')?.textContent||String(i),seatIndex=Number(s.dataset.seatIndex),stack=parseMoney(s.querySelector('.seatStack')?.textContent),seatRect=s.getBoundingClientRect();stacks.set(seatIndex,{value:stack,rect:seatRect});if(s.classList.contains('folded'))folded.add(key);if(s.textContent.includes('ALL IN'))allin.add(key);if(!last.folded.has(key)&&folded.has(key)){cue('fold');pulse(s,'fxFold',620);if(s.dataset.playerId&&document.querySelector('.foldedHole'))pulseAll(document.querySelectorAll('.foldedHole .card'),'fxMuck',40,520)}if(!last.allin.has(key)&&allin.has(key)){cue('allin');pulse(s,'fxAllIn',760)}const old=last.stacks.get(seatIndex);if(old&&stack>old.value&&last.pot>pot&&potRect){cue('win');flyChip(potRect,seatRect,'toWinner');pulse(s,'fxStackWin',760)}});
 if(last.street&&street==='SHOWDOWN'&&last.street!=='SHOWDOWN'){cue('showdown');pulseAll(document.querySelectorAll('.showdownFelt .seat:not(.folded)'),'fxShowdown',55,1050)}
 if(last.street&&street==='FINISHED'&&last.street!=='FINISHED')cue('win');
 last={hand:hand||last.hand,board,pot,folded,allin,street:street||last.street,bets,stacks}}
function scheduleScan(){if(frame)return;frame=requestAnimationFrame(scan)}
const observer=new MutationObserver(scheduleScan);
function start(){observer.observe(document.body,{childList:true,subtree:true,characterData:true,attributes:true,attributeFilter:['class']});scan()}
if(document.readyState==='loading')addEventListener('DOMContentLoaded',start,{once:true});else start();
