import React from'react';
import{createRoot}from'react-dom/client';
import App from'./App.jsx';
import TournamentConfig from'./TournamentConfig.jsx';
import ActionLogPanel from'./ActionLogPanel.jsx';
import TableChatDock from'./TableChatDock.jsx';
import{installSessionRouting}from'./session.js';
import'./fx-runtime.js';
import'./tournament-config.css';
import'./fixed-gameplay.css';
import'./chat-dock-override.css';
import'./fixed-gameplay-polish.css';
import'./gameplay-layout-v2.css';
installSessionRouting();
createRoot(document.getElementById('root')).render(<><App/><TournamentConfig/><ActionLogPanel/><TableChatDock/></>);
