let bootstrapState={platform:'web',ready:true,error:'',identity:null},telegramConfigPromise=null,backHandlerInstalled=false;
function webApp(){return typeof window!=='undefined'?window.Telegram?.WebApp:null}
export function isTelegramMiniApp(){const tg=webApp();return!!(tg&&String(tg.initData||''))}
export function platformState(){return bootstrapState}
export function accountIdentity(account){return account?.identity||account?.telegram||account?.discord||null}
export function parseTelegramStartParam(value=''){const m=String(value||'').trim().match(/^(table|tournament)_([A-Z0-9]{6})$/i);return m?{kind:m[1].toLowerCase(),code:m[2].toUpperCase()}:null}
function syncTelegramBackButton(){const tg=webApp(),back=tg?.BackButton;if(!back)return;const away=!!location.hash&&!/^#\/?$/.test(location.hash);if(away)back.show();else back.hide()}
function installTelegramBackButton(){const tg=webApp(),back=tg?.BackButton;if(!back||backHandlerInstalled)return;backHandlerInstalled=true;back.onClick(()=>{if(location.hash){location.hash=''}else tg.close?.()});addEventListener('hashchange',syncTelegramBackButton);syncTelegramBackButton()}
function applyTelegramInsets(){const tg=webApp(),root=document.documentElement,s=tg?.contentSafeAreaInset||tg?.safeAreaInset;if(!s)return;for(const[key,value]of Object.entries({top:s.top,right:s.right,bottom:s.bottom,left:s.left}))root.style.setProperty(`--telegram-safe-${key}`,`${Math.max(0,Number(value)||0)}px`)}
export async function bootstrapPlatform(){const tg=webApp();if(!tg){bootstrapState={platform:'web',ready:true,error:'',identity:null};return bootstrapState}document.documentElement.classList.add('telegramMiniApp');try{tg.ready?.();tg.expand?.();tg.setHeaderColor?.('#09060d');tg.setBackgroundColor?.('#09060d')}catch{}applyTelegramInsets();installTelegramBackButton();try{tg.onEvent?.('safeAreaChanged',applyTelegramInsets);tg.onEvent?.('contentSafeAreaChanged',applyTelegramInsets)}catch{}const initData=String(tg.initData||'');if(!initData){bootstrapState={platform:'telegram',ready:true,error:'Telegram did not provide signed launch data. Open Full Tilt from the bot’s Launch App button.',identity:null};return bootstrapState}try{const r=await fetch('/api/auth/telegram',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({initData})}),j=await r.json();if(!r.ok)throw Error(j.error||'Telegram login failed.');bootstrapState={platform:'telegram',ready:true,error:'',identity:j.identity||null};const route=parseTelegramStartParam(j.startParam||'');if(route&&!location.hash)location.hash=`#/${route.kind}/${route.code}`;return bootstrapState}catch(error){bootstrapState={platform:'telegram',ready:true,error:error?.message||'Telegram login failed.',identity:null};return bootstrapState}}
async function telegramConfig(){if(!telegramConfigPromise)telegramConfigPromise=fetch('/api/auth/telegram/config',{cache:'no-store'}).then(r=>r.ok?r.json():{}).catch(()=>({}));return telegramConfigPromise}
export async function telegramGameLink(kind,code){const config=await telegramConfig(),username=String(config?.botUsername||'').replace(/^@/,'').trim(),shortName=String(config?.appShortName||'').trim();if(!username)return'';const start=`${kind==='tournament'?'tournament':'table'}_${String(code||'').toUpperCase()}`;return shortName?`https://t.me/${username}/${shortName}?startapp=${encodeURIComponent(start)}`:`https://t.me/${username}?startapp=${encodeURIComponent(start)}`}
export async function shareGameInvite(kind,code,fallbackUrl){const tg=webApp();if(isTelegramMiniApp()&&tg?.openTelegramLink){const link=await telegramGameLink(kind,code);if(link){const text=kind==='tournament'?`Join my Full Tilt Poker tournament ${String(code).toUpperCase()}`:`Join my Full Tilt Poker table ${String(code).toUpperCase()}`;tg.openTelegramLink(`https://t.me/share/url?url=${encodeURIComponent(link)}&text=${encodeURIComponent(text)}`);return{shared:true,link}}}try{await navigator.clipboard?.writeText(fallbackUrl);return{shared:false,link:fallbackUrl,copied:true}}catch{return{shared:false,link:fallbackUrl,copied:false}}}
