let bootstrapState={platform:'web',ready:true,error:'',identity:null},telegramConfigPromise=null,backHandlerInstalled=false,settingsHandlerInstalled=false,hapticsInstalled=false,platformEventsInstalled=false;
function webApp(){return typeof window!=='undefined'?window.Telegram?.WebApp:null}
export function isTelegramMiniApp(){const tg=webApp();return!!(tg&&String(tg.initData||''))}
export function platformState(){return bootstrapState}
export function accountIdentity(account){return account?.identity||account?.telegram||account?.discord||null}
export function parseTelegramStartParam(value=''){const m=String(value||'').trim().match(/^(table|tournament)_([A-Z0-9]{6})$/i);return m?{kind:m[1].toLowerCase(),code:m[2].toUpperCase()}:null}
export function telegramRouteState(hash=''){const value=String(hash||'');const game=/^#\/(table|tournament)\/[A-Z0-9]{6}/i.test(value);return{game,lobby:!game,showBack:game,showSettings:!game,confirmClose:game}}
function validColor(value,fallback){const v=String(value||'').trim();return /^#[0-9a-f]{6}$/i.test(v)?v:fallback}
export function telegramThemeVariables(params={}){return{'--telegram-bg':validColor(params.bg_color,'#09060d'),'--telegram-secondary-bg':validColor(params.secondary_bg_color,'#120b18'),'--telegram-text':validColor(params.text_color,'#f6f0ff'),'--telegram-hint':validColor(params.hint_color,'#97899e'),'--telegram-link':validColor(params.link_color,'#d7b557'),'--telegram-button':validColor(params.button_color,'#6e2da2'),'--telegram-button-text':validColor(params.button_text_color,'#ffffff'),'--telegram-bottom-bar':validColor(params.bottom_bar_bg_color,validColor(params.bg_color,'#09060d'))}}
function setRootVar(name,value){document.documentElement.style.setProperty(name,value)}
function applyTelegramTheme(){const tg=webApp();if(!tg)return;const root=document.documentElement,vars=telegramThemeVariables(tg.themeParams||{});for(const[name,value]of Object.entries(vars))setRootVar(name,value);root.dataset.telegramTheme=String(tg.colorScheme||'dark');try{tg.setHeaderColor?.(vars['--telegram-bg']);tg.setBackgroundColor?.(vars['--telegram-bg']);tg.setBottomBarColor?.(vars['--telegram-bottom-bar'])}catch{}}
function insetValue(value){return Math.max(0,Number(value)||0)}
function applyTelegramInsets(){const tg=webApp();if(!tg)return;const safe=tg.safeAreaInset||{},content=tg.contentSafeAreaInset||safe||{},root=document.documentElement;for(const side of['top','right','bottom','left']){root.style.setProperty(`--telegram-system-safe-${side}`,`${insetValue(safe?.[side])}px`);root.style.setProperty(`--telegram-safe-${side}`,`${insetValue(content?.[side])}px`)}const viewport=Math.max(0,Number(tg.viewportHeight)||0),stable=Math.max(0,Number(tg.viewportStableHeight)||viewport);if(viewport)root.style.setProperty('--telegram-viewport-height',`${viewport}px`);if(stable)root.style.setProperty('--telegram-viewport-stable-height',`${stable}px`)}
export function telegramImpact(style='light'){const tg=webApp();if(!tg?.HapticFeedback)return false;try{tg.HapticFeedback.impactOccurred?.(style);return true}catch{return false}}
export function telegramNotificationHaptic(type='success'){const tg=webApp();if(!tg?.HapticFeedback)return false;try{tg.HapticFeedback.notificationOccurred?.(type);return true}catch{return false}}
function syncTelegramChrome(){const tg=webApp();if(!tg)return;const route=telegramRouteState(location.hash),back=tg.BackButton,settings=tg.SettingsButton;try{route.showBack?back?.show?.():back?.hide?.();route.showSettings?settings?.show?.():settings?.hide?.();route.confirmClose?tg.enableClosingConfirmation?.():tg.disableClosingConfirmation?.();tg.enableVerticalSwipes?.()}catch{}document.documentElement.classList.toggle('telegramGameRoute',route.game);document.documentElement.classList.toggle('telegramLobbyRoute',route.lobby)}
function installTelegramBackButton(){const tg=webApp(),back=tg?.BackButton;if(!back||backHandlerInstalled)return;backHandlerInstalled=true;back.onClick(()=>{telegramImpact('light');if(location.hash)location.hash='';else tg.close?.()})}
function installTelegramSettings(){const tg=webApp(),settings=tg?.SettingsButton;if(!settings||settingsHandlerInstalled)return;settingsHandlerInstalled=true;settings.onClick(()=>{telegramImpact('light');window.dispatchEvent(new CustomEvent('crashout:telegram-settings'))})}
function installTelegramHaptics(){if(hapticsInstalled)return;hapticsInstalled=true;addEventListener('pointerup',event=>{const el=event.target?.closest?.('button,a,[role="button"]');if(!el||el.matches?.(':disabled,[aria-disabled="true"]'))return;const style=el.matches?.('.primary,.discordLogin,.createChoice button,.entryActions button')?'medium':'light';telegramImpact(style)},{passive:true})}
function installTelegramEvents(){const tg=webApp();if(!tg||platformEventsInstalled)return;platformEventsInstalled=true;try{tg.onEvent?.('themeChanged',applyTelegramTheme);tg.onEvent?.('viewportChanged',applyTelegramInsets);tg.onEvent?.('safeAreaChanged',applyTelegramInsets);tg.onEvent?.('contentSafeAreaChanged',applyTelegramInsets)}catch{}addEventListener('hashchange',syncTelegramChrome)}
export async function bootstrapPlatform(){const tg=webApp();if(!tg){bootstrapState={platform:'web',ready:true,error:'',identity:null};return bootstrapState}document.documentElement.classList.add('telegramMiniApp');try{tg.ready?.();tg.expand?.();tg.enableVerticalSwipes?.()}catch{}applyTelegramTheme();applyTelegramInsets();installTelegramBackButton();installTelegramSettings();installTelegramHaptics();installTelegramEvents();syncTelegramChrome();const initData=String(tg.initData||'');if(!initData){bootstrapState={platform:'telegram',ready:true,error:'Telegram did not provide signed launch data. Open Crashout Poker from the bot’s Launch App button.',identity:null};return bootstrapState}try{const r=await fetch('/api/auth/telegram',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({initData})}),j=await r.json();if(!r.ok)throw Error(j.error||'Telegram login failed.');bootstrapState={platform:'telegram',ready:true,error:'',identity:j.identity||null};const route=parseTelegramStartParam(j.startParam||'');if(route&&!location.hash)location.hash=`#/${route.kind}/${route.code}`;syncTelegramChrome();return bootstrapState}catch(error){bootstrapState={platform:'telegram',ready:true,error:error?.message||'Telegram login failed.',identity:null};return bootstrapState}}
async function telegramConfig(){if(!telegramConfigPromise)telegramConfigPromise=fetch('/api/auth/telegram/config',{cache:'no-store'}).then(r=>r.ok?r.json():{}).catch(()=>({}));return telegramConfigPromise}
export async function telegramGameLink(kind,code){const config=await telegramConfig(),username=String(config?.botUsername||'').replace(/^@/,'').trim(),shortName=String(config?.appShortName||'').trim();if(!username)return'';const start=`${kind==='tournament'?'tournament':'table'}_${String(code||'').toUpperCase()}`;return shortName?`https://t.me/${username}/${shortName}?startapp=${encodeURIComponent(start)}`:`https://t.me/${username}?startapp=${encodeURIComponent(start)}`}
export async function shareGameInvite(kind,code,fallbackUrl){const tg=webApp();if(isTelegramMiniApp()&&tg?.openTelegramLink){const link=await telegramGameLink(kind,code);if(link){const text=kind==='tournament'?`Join my Crashout Poker tournament ${String(code).toUpperCase()}`:`Join my Crashout Poker table ${String(code).toUpperCase()}`;telegramImpact('medium');tg.openTelegramLink(`https://t.me/share/url?url=${encodeURIComponent(link)}&text=${encodeURIComponent(text)}`);return{shared:true,link}}}try{await navigator.clipboard?.writeText(fallbackUrl);return{shared:false,link:fallbackUrl,copied:true}}catch{return{shared:false,link:fallbackUrl,copied:false}}}
