import React,{useState}from'react';
import'./purchase-history.css';

const LABELS={constellation:'Constellation',deadMansHand:"Dead Man's Hand",regalia:'Regalia',tripleThreat:'Triple Threat'};
function money(amount,currency='usd'){try{return new Intl.NumberFormat(undefined,{style:'currency',currency:String(currency||'usd').toUpperCase()}).format(Number(amount||0)/100)}catch{return`$${(Number(amount||0)/100).toFixed(2)}`}}
function when(at){if(!at)return'';try{return new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',year:'numeric'}).format(new Date(at))}catch{return''}}
function statusLabel(status){if(status==='refunded')return'REFUNDED';if(status==='refund_pending')return'REFUND PENDING';if(status==='partially_refunded')return'PARTIAL REFUND';return'PAID'}
export default function PurchaseHistory({purchases=[],onAccount,setMsg}){const rows=Array.isArray(purchases)?purchases:[], [selected,setSelected]=useState(null),[busy,setBusy]=useState(false);
 async function requestRefund(){if(!selected?.purchaseId||busy)return;setBusy(true);try{const r=await fetch('/api/shop/refund',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({purchaseId:selected.purchaseId})}),j=await r.json();if(!r.ok){setMsg?.(j.error||'Could not process refund.');return}if(j.account)onAccount?.(j.account);setSelected(null);setMsg?.(j.refund?.status==='succeeded'?'Refund processed. The payment is being returned to the original payment method.':'Refund requested. Stripe is processing the return to the original payment method.')}catch{setMsg?.('Could not reach refund services.')}finally{setBusy(false)}}
 return <section className="purchaseHistorySection"><div className="profileSectionTitle"><b>Purchases</b><small>{rows.length?`${rows.length} transaction${rows.length===1?'':'s'}`:'Cosmetic receipts'}</small></div>{rows.length?<div className="purchaseHistoryList">{rows.map((purchase,index)=>{const refundable=(purchase.status==='paid'||purchase.status==='partially_refunded')&&purchase.purchaseId;return <article className={`purchaseHistoryRow ${purchase.status||'paid'}`} key={`${purchase.reference||purchase.purchaseKey}-${index}`}><div className="purchaseReceiptIcon">♠</div><div className="purchaseReceiptCopy"><b>{LABELS[purchase.purchaseKey]||'Full Tilt Booster'}</b><span>{when(purchase.at)} • {money(purchase.amountTotal,purchase.currency)}</span><small>REF {purchase.reference||'—'}</small></div><div className="purchaseReceiptState"><strong>{statusLabel(purchase.status)}</strong>{purchase.amountRefunded>0&&<small>{money(purchase.amountRefunded,purchase.currency)} refunded</small>}{refundable&&<button className="purchaseRefundButton" onClick={()=>setSelected(purchase)}>REQUEST REFUND</button>}</div></article>})}</div>:<div className="purchaseHistoryEmpty"><b>No cosmetic purchases yet.</b><span>Your Stripe purchase receipts will appear here.</span></div>}<div className="purchaseHistoryLinks"><a href="/purchases.html">Purchase policy</a><a href="/refunds.html">Refund policy</a><a href="/contact.html">Billing support</a></div>{selected&&<div className="refundConfirmShade" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)setSelected(null)}}><section className="refundConfirm" role="dialog" aria-modal="true" aria-label="Confirm refund"><span>REFUND PURCHASE</span><h3>{LABELS[selected.purchaseKey]||'Full Tilt Booster'}</h3><strong>{money(Math.max(0,Number(selected.amountTotal||0)-Number(selected.amountRefunded||0)),selected.currency)}</strong><p>This sends the refundable balance back through Stripe to the original payment method. Once confirmed, any cosmetics supported only by this purchase are removed from your Full Tilt account.</p><small>Refund timing after approval depends on the original payment method and its financial institution.</small><div><button disabled={busy} onClick={()=>setSelected(null)}>CANCEL</button><button className="confirmRefund" disabled={busy} onClick={requestRefund}>{busy?'PROCESSING…':'CONFIRM REFUND'}</button></div></section></div>}</section>}
