const ROLE_PREFIX='ftp_session_role_',SESSION_PREFIX='ftp_session_',SPECTATOR_PREFIX='ftp_spectator_session_';
function key(prefix,code){return`${prefix}${String(code||'').toUpperCase()}`}
export function sessionToken(code){return localStorage.getItem(key(SESSION_PREFIX,code))||''}
export function rememberPlayerSession(code,token){code=String(code||'').toUpperCase();if(!code||!token)return;localStorage.setItem(key(SESSION_PREFIX,code),token);localStorage.setItem(key(ROLE_PREFIX,code),'player');localStorage.removeItem(key(SPECTATOR_PREFIX,code))}
export function rememberSpectatorSession(code,token){code=String(code||'').toUpperCase();if(!code||!token)return;localStorage.setItem(key(SESSION_PREFIX,code),token);localStorage.setItem(key(SPECTATOR_PREFIX,code),token);localStorage.setItem(key(ROLE_PREFIX,code),'spectator')}
export function rememberRouteSession(code,token){code=String(code||'').toUpperCase();if(!code||!token)return;if(localStorage.getItem(key(ROLE_PREFIX,code))==='spectator')rememberSpectatorSession(code,token);else rememberPlayerSession(code,token)}
export function parkSpectatorSession(code){code=String(code||'').toUpperCase();if(!code||localStorage.getItem(key(ROLE_PREFIX,code))!=='spectator')return;const token=localStorage.getItem(key(SESSION_PREFIX,code));if(token)localStorage.setItem(key(SPECTATOR_PREFIX,code),token);localStorage.removeItem(key(SESSION_PREFIX,code))}
export function restoreSpectatorSession(code){code=String(code||'').toUpperCase();if(!code||localStorage.getItem(key(ROLE_PREFIX,code))!=='spectator'||localStorage.getItem(key(SESSION_PREFIX,code)))return;const token=localStorage.getItem(key(SPECTATOR_PREFIX,code));if(token)localStorage.setItem(key(SESSION_PREFIX,code),token)}
export function reconcileSessionRoute(){const m=location.hash.match(/^#\/table\/([A-Z0-9]{6})/i);if(m){restoreSpectatorSession(m[1]);return}const spectatorCodes=[];for(let i=0;i<localStorage.length;i++){const storageKey=localStorage.key(i);if(storageKey?.startsWith(ROLE_PREFIX)&&localStorage.getItem(storageKey)==='spectator')spectatorCodes.push(storageKey.slice(ROLE_PREFIX.length))}for(const code of spectatorCodes)parkSpectatorSession(code)}
export function installSessionRouting(){reconcileSessionRoute();addEventListener('hashchange',reconcileSessionRoute)}
