const ROLE_PREFIX='ftp_session_role_',SESSION_PREFIX='ftp_session_',SPECTATOR_PREFIX='ftp_spectator_session_',TOURNAMENT_PREFIX='ftp_tournament_session_';
function key(prefix,code){return`${prefix}${String(code||'').toUpperCase()}`}
function routeSession(hash=''){const value=String(hash||''),m=value.match(/^#\/(table|tournament)\/([A-Z0-9]{6})(?:\?|$)/i);if(!m)return null;const query=value.includes('?')?value.slice(value.indexOf('?')+1):'',params=new URLSearchParams(query);return{kind:m[1].toLowerCase(),code:m[2].toUpperCase(),token:params.get('token')||''}}
export function safeSessionHash(hash=''){const value=String(hash||''),q=value.indexOf('?');if(q<0)return value;const base=value.slice(0,q),params=new URLSearchParams(value.slice(q+1));if(!params.has('token'))return value;params.delete('token');const query=params.toString();return`${base}${query?`?${query}`:''}`}
export function sessionToken(code){return localStorage.getItem(key(SESSION_PREFIX,code))||''}
export function tournamentSessionToken(code){return localStorage.getItem(key(TOURNAMENT_PREFIX,code))||''}
export function rememberTournamentSession(code,token){code=String(code||'').toUpperCase();if(!code||!token)return;localStorage.setItem(key(TOURNAMENT_PREFIX,code),token)}
export function sessionTokenFor(code,kind='table'){return kind==='tournament'?tournamentSessionToken(code):sessionToken(code)}
export function rememberPlayerSession(code,token){code=String(code||'').toUpperCase();if(!code||!token)return;localStorage.setItem(key(SESSION_PREFIX,code),token);localStorage.setItem(key(ROLE_PREFIX,code),'player');localStorage.removeItem(key(SPECTATOR_PREFIX,code))}
export function rememberSpectatorSession(code,token){code=String(code||'').toUpperCase();if(!code||!token)return;localStorage.setItem(key(SESSION_PREFIX,code),token);localStorage.setItem(key(SPECTATOR_PREFIX,code),token);localStorage.setItem(key(ROLE_PREFIX,code),'spectator')}
export function rememberRouteSession(code,token){code=String(code||'').toUpperCase();if(!code||!token)return;if(localStorage.getItem(key(ROLE_PREFIX,code))==='spectator')rememberSpectatorSession(code,token);else rememberPlayerSession(code,token)}
export function parkSpectatorSession(code){code=String(code||'').toUpperCase();if(!code||localStorage.getItem(key(ROLE_PREFIX,code))!=='spectator')return;const token=localStorage.getItem(key(SESSION_PREFIX,code));if(token)localStorage.setItem(key(SPECTATOR_PREFIX,code),token);localStorage.removeItem(key(SESSION_PREFIX,code))}
export function restoreSpectatorSession(code){code=String(code||'').toUpperCase();if(!code||localStorage.getItem(key(ROLE_PREFIX,code))!=='spectator'||localStorage.getItem(key(SESSION_PREFIX,code)))return;const token=localStorage.getItem(key(SPECTATOR_PREFIX,code));if(token)localStorage.setItem(key(SESSION_PREFIX,code),token)}
function importRouteSession(){const route=routeSession(location.hash);if(!route?.token)return;if(route.kind==='tournament')rememberTournamentSession(route.code,route.token);else rememberRouteSession(route.code,route.token);const clean=safeSessionHash(location.hash);if(clean!==location.hash)history.replaceState(history.state,'',`${location.pathname}${location.search}${clean}`)}
export function reconcileSessionRoute(){importRouteSession();const m=location.hash.match(/^#\/table\/([A-Z0-9]{6})/i);if(m){restoreSpectatorSession(m[1]);return}const spectatorCodes=[];for(let i=0;i<localStorage.length;i++){const storageKey=localStorage.key(i);if(storageKey?.startsWith(ROLE_PREFIX)&&localStorage.getItem(storageKey)==='spectator')spectatorCodes.push(storageKey.slice(ROLE_PREFIX.length))}for(const code of spectatorCodes)parkSpectatorSession(code)}
export function installSessionRouting(){reconcileSessionRoute();addEventListener('hashchange',reconcileSessionRoute)}
