import React from'react';
import'./mobile-table.css';
import'./desktop-table.css';
import'./showdown.css';
import'./action-feedback.css';
import'./table-stability.css';
import'./pot-accounting.css';
import'./cosmetics.css';
import'./table-seat-layout.css';
import{Card}from'./TablePanels.jsx';
import SeatSlot from'./SeatSlot.jsx';
import ApprovedCashFelt from'./ApprovedCashFelt.jsx';
import{assets,cardBackFor}from'./assets.js';

function showdownWinners(state){if(state.street!=='showdown')return new Map();const wins=new Map();for(const award of state.lastResult?.awards||[])wins.set(award.playerId,(wins.get(award.playerId)||0)+Number(award.amount||0));return wins}

function PotDisplay({state,isShowdown}){const live=state.livePots||[],showSide=!isShowdown&&live.length>1,displayPot=isShowdown?Number(state.lastResult?.settledPot||0):Number(state.pot||0);return <div className={`potCluster v2PotCluster ${showSide?'hasSidePots':''}`}><img className="productionPotArt" src={assets.default.pot} alt=""/><div className="pot"><small>{isShowdown?'AWARDED':'POT'}</small><b>{displayPot.toLocaleString()}</b></div>{showSide&&<div className="sidePots">{live.map((p,i)=><div className={`potSlice ${i===0?'mainPotSlice':'sidePotSlice'}`} key={i}><small>{i===0?'MAIN POT':`SIDE POT ${i}`}</small><b>{Number(p.amount||0).toLocaleString()}</b></div>)}</div>}</div>}

export function TableTopbar({code,state,realtime,blindLeft,next,copied,onCopy,onExit,onChat,onHistory,showChat,showHistory}){const style={'--topbar-art':`url(${assets.default.ui.topBar})`},alive=state.players.filter(p=>!p.eliminated).length;return <header className="topbar productionTopbar gameplayV2Topbar" style={style}>
  <button className="ghost v2LobbyButton" onClick={onExit}>‹ <span>Lobby</span></button>
  <div className="v2TableIdentity"><img className="v2TopLogo" src={assets.default.logoMobile} alt="FULL TILT POKER"/><strong>TABLE {code} • HAND #{state.handNumber||0}</strong><div className="v2TableMeta"><span>{state.smallBlind}/{state.bigBlind} NLH</span><i/> <span>LV {state.blindLevel+1}</span><i/> <span>{blindLeft}</span><i/> <span>{alive}/{state.players.length}</span><i/> <span className={realtime==='live'?'liveMeta':'reconnectMeta'}>{realtime==='live'?'LIVE':'RECONNECTING'}</span></div></div>
  <div className="v2TopActions"><button className="ghost v2InviteButton" onClick={onCopy}>{copied?'Copied ✓':'Copy Invite'}</button><div className="v2UtilityRow"><button className={showChat?'active':''} onClick={onChat} aria-label="Chat">◌<span>Chat</span></button><button className={showHistory?'active':''} onClick={onHistory} aria-label="Hand log">▤<span>Hand Log</span></button></div></div>
</header>}

export function InfoStrip({alive,state,blindLeft}){const style={'--info-art':`url(${assets.default.ui.infoStrip})`};return <div className="infoStrip productionInfoStrip" style={style}><span><b>{alive}</b> left</span><span><b>{state.pot.toLocaleString()}</b> pot</span><span><b>{state.street?.toUpperCase()}</b> street</span><span><b>{state.paused?'PAUSED':blindLeft}</b> blinds</span></div>}

export function PokerFelt(props){const{state,finished,showdownLeft,pos,turnLeft,me,onKick}=props,cash=typeof location!=='undefined'&&/^#\/table\//i.test(location.hash);if(cash&&state.players.length<=8)return <ApprovedCashFelt {...props}/>;const winners=showdownWinners(state),isShowdown=state.street==='showdown',winnerIds=[...winners.keys()],feltStyle={'--felt-desktop':`url(${assets.default.feltDesktop})`,'--felt-mobile':`url(${assets.default.feltMobile})`,'--felt-cash-v2':`url("${assets.default.feltCashV2}")`,'--showdown-art':`url(${assets.default.ui.showdown})`,'--winner-art':`url(${assets.default.ui.tournamentWinner})`};return <section data-street={state.street} data-hand={state.handNumber||0} data-player-count={state.players.length} style={feltStyle} className={`felt productionFelt gameplayV2Felt ${isShowdown?'showdownFelt':''}`}>
  {isShowdown&&<div className="showdownArt"/>}
  {finished&&!state.endedByHost&&<div className="winnerArt"/>}
  <div className="v2FeltBrand"><b>FULL TILT</b><span>DEGENS PLAY HERE</span></div>
  <div className={`board ${isShowdown?'showdownBoard':''}`}>{state.board.map((c,i)=><Card key={`${state.handNumber}-${i}`} c={c}/>)}{state.board.length===0&&<span className="waiting">{state.started?(state.paused?'Game paused':'Pre-flop'):finished?(state.endedByHost?'Game ended':'Game complete'):'Waiting for host to start'}</span>}</div>
  <PotDisplay state={state} isShowdown={isShowdown}/>
  {isShowdown&&state.lastResult&&<div className="showdownBanner"><small>SHOWDOWN • NEXT HAND IN {showdownLeft}s</small><strong>{state.lastResult.summary}</strong>{winnerIds.length>0&&<div className="winnerLine">{winnerIds.map(id=>{const player=state.players.find(p=>p.id===id),name=player?.name||state.lastResult.awards?.find(a=>a.playerId===id)?.name||'Winner';return <span key={id}>{name} <b>+{Number(winners.get(id)||0).toLocaleString()}</b></span>})}</div>}</div>}
  {finished&&<div className="showdownBanner finalBanner"><small>{state.endedByHost?'GAME ENDED':'GAME COMPLETE'}</small><strong>{state.message}</strong></div>}
  {state.players.map((player,index)=><SeatSlot key={player.id} player={player} index={index} players={state.players} me={me} pos={pos} turnLeft={turnLeft} isShowdown={isShowdown} winners={winners} finished={finished} onKick={onKick} state={state}/>) }
</section>}

export function TableHUD({state,me,isSpectator,strength,turnLeft,raise,setRaise,showStats,setShowStats,showHistory,setShowHistory,showChat,setShowChat,onAction}){const canAct=me&&state.started&&!state.paused&&state.street!=='showdown'&&me.turn&&!me.folded&&!me.eliminated&&me.chips>0,callCost=Math.min(Number(me?.chips||0),Math.max(0,Number(state.toCall||0))),minRaiseTarget=Math.max(0,Number(state.raiseTo||0)),maxRaiseTarget=Math.max(minRaiseTarget,Number(me?.bet||0)+Number(me?.chips||0)),customRaiseTarget=Math.min(maxRaiseTarget,Math.max(minRaiseTarget,Number(raise||minRaiseTarget))),customRaiseCost=Math.min(Number(me?.chips||0),Math.max(0,customRaiseTarget-Number(me?.bet||0))),isShowdown=state.street==='showdown';const quickRaise=(fraction)=>{if(!state.canRaise)return;const call=Math.max(0,state.toCall||0),pot=Math.max(0,state.pot||0),min=minRaiseTarget;setRaise(String(Math.min(maxRaiseTarget,Math.max(min,Math.round((state.currentBet||0)+call+pot*fraction)))))};return <section className={`hud gameplayV2Hud ${canAct?'actingHud':''} ${isShowdown?'showdownHud':''}`}>
  <div className={`holeWrap ${me?.folded?'foldedHole':''}`}>{me?<><div className="hole">{me.cards?.map((c,i)=><Card key={i} c={c} backAsset={cardBackFor(me)}/>)||<span>Cards hidden</span>}</div><div className="v2HeroIdentity"><span className="v2HeroCrown">♠</span><div><small>YOU</small><b>{Number(me.chips||0).toLocaleString()}</b></div></div>{strength&&state.started&&!me.folded&&!isShowdown&&<div className="handStrength">{strength}</div>}</>:<div className="railBadge">SPECTATOR<br/><small>NO HOLE CARDS</small></div>}</div>
  <div className="status"><strong>{canAct?'YOUR TURN':state.paused?'PAUSED':state.street?.toUpperCase()}</strong><span>{canAct?(state.toCall>0?`${state.toCall.toLocaleString()} to call • pot ${state.pot.toLocaleString()}`:`Check is free • pot ${state.pot.toLocaleString()}`):state.message}</span>{state.started&&!state.paused&&turnLeft!=null&&<div className={`hudClock ${turnLeft<=10?'dangerClock':''}`}>{turnLeft}s</div>}<div className="hudToggles">{state.tournamentStats?.length>0&&<button className="lastHandToggle" onClick={()=>setShowStats(v=>!v)}>Stats {showStats?'▲':'▼'}</button>}</div></div>
  <div className="actions">{me?.host&&!state.started&&state.street!=='finished'&&<div className="hostControls"><button className="primary" onClick={()=>onAction('start')}>Start Game ({state.players.length})</button>{state.players.length<9&&<button onClick={()=>onAction('addbot')}>+ Add Test Bot</button>}</div>}{canAct&&<div className="actionDock v2ActionDock"><div className="actionRow"><button className="foldAction" onClick={()=>onAction('fold')}>Fold</button><button className="checkCallAction" onClick={()=>onAction(state.toCall===0?'check':'call')}>{state.toCall===0?'Check':<>Call<span className="actionCost">{callCost.toLocaleString()}</span></>}</button>{state.canRaise?<button className="primary raiseAction" onClick={()=>onAction('raise',customRaiseTarget)}>Raise<span className="actionCost">to {customRaiseTarget.toLocaleString()}</span></button>:<button disabled className="raiseAction">Raise</button>}{state.canAllIn&&<button className="allin" onClick={()=>onAction('allin')}>All In<span className="actionCost">{Number(me.chips||0).toLocaleString()}</span></button>}</div>{state.canRaise&&<div className="v2RaiseControls"><div className="v2SliderRow"><span>Bet Size: <b>{customRaiseTarget.toLocaleString()}</b></span><input type="range" min={minRaiseTarget} max={maxRaiseTarget} step="1" value={customRaiseTarget} onChange={e=>setRaise(e.target.value)}/></div><div className="v2QuickBets"><button onClick={()=>quickRaise(.25)}>25%</button><button onClick={()=>quickRaise(.5)}>50%</button><button onClick={()=>quickRaise(.75)}>75%</button><button onClick={()=>setRaise(String(maxRaiseTarget))}>Max</button></div></div>}{!state.canRaise&&state.toCall>0&&<small className="raiseClosed">Short all-in: call or fold only.</small>}</div>}{me?.host&&state.started&&<div className="hostControls v2HostControls">{state.street!=='showdown'&&<button onClick={()=>onAction(state.paused?'resume':'pause')}>{state.paused?'Resume':'Pause'}</button>}<button className="danger" onClick={()=>onAction('end')}>End Game</button></div>}{isSpectator&&<span className="readOnlyNote">Watching only</span>}</div>
</section>}
