import React,{useEffect,useMemo,useRef,useState}from'react';
import{subscribeTableState}from'./table-state-bus.js';
import{sessionToken,tournamentSessionToken}from'./session.js';

function currentRoute(){let m=location.hash.match(/^#\/tournament\/([A-Z0-9]{6})/i);if(m)return{kind:'tournament',code:m[1].toUpperCase()};m=location.hash.match(/^#\/table\/([A-Z0-9]{6})/i);if(m)return{kind:'table',code:m[1].toUpperCase()};return null}
function messagesForScope(scope,state,globalMessages){return scope==='global'?globalMessages:(state?.chat||[])}
function viewerLabel(viewer){return viewer?.type==='spectator'?`Watching as ${viewer.name||'Guest'}`:`Chatting as ${viewer?.name||'Guest'}`}

export default function TableChatDock(){
 const[route,setRoute]=useState(()=>currentRoute()),[state,setState]=useState(null),[open,setOpen]=useState(false),[scope,setScope]=useState('table'),[draft,setDraft]=useState(''),[globalMessages,setGlobalMessages]=useState([]),[error,setError]=useState(''),[sending,setSending]=useState(false),logRef=useRef(null);
 useEffect(()=>{const off=subscribeTableState(next=>setState(next)),onHash=()=>{const next=currentRoute();setRoute(next);setOpen(false);setError('');setScope(next?.kind==='tournament'?'global':'table')};addEventListener('hashchange',onHash);onHash();return()=>{off();removeEventListener('hashchange',onHash)}},[]);
 const token=useMemo(()=>route?(route.kind==='tournament'?tournamentSessionToken(route.code):sessionToken(route.code)):'',[route]),isTournament=route?.kind==='tournament',viewer=state?.viewer,messages=messagesForScope(scope,state,globalMessages),visible=!!(route&&viewer&&token);
 async function loadGlobal(){if(!isTournament||!token)return;try{const r=await fetch(`/api/tournaments/${route.code}/chat?token=${encodeURIComponent(token)}`,{cache:'no-store'}),j=await r.json();if(r.ok){setGlobalMessages(Array.isArray(j.messages)?j.messages:[]);setError('')}else setError(j.error||'Could not load global chat.')}catch{setError('Global chat reconnecting…')}}
 useEffect(()=>{if(!visible||!open||!isTournament||scope!=='global')return;loadGlobal();const id=setInterval(loadGlobal,1500);return()=>clearInterval(id)},[visible,open,isTournament,scope,token,route?.code]);
 useEffect(()=>{if(!open)return;requestAnimationFrame(()=>{if(logRef.current)logRef.current.scrollTop=logRef.current.scrollHeight})},[open,scope,messages.length]);
 async function send(){const message=draft.trim();if(!message||sending||!route||!token)return;setSending(true);setError('');try{const url=scope==='global'?`/api/tournaments/${route.code}/chat`:route.kind==='tournament'?`/api/tournaments/${route.code}/table/chat`:`/api/tables/${route.code}/chat`,r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token,message})}),j=await r.json();if(!r.ok){setError(j.error||'Could not send message.');return}setDraft('');if(scope==='global')setGlobalMessages(Array.isArray(j.messages)?j.messages:globalMessages)}catch{setError('Message could not be sent.')}finally{setSending(false)}}
 if(!visible)return null;
 return <><button className={`tableChatDockButton ${open?'open':''}`} onClick={()=>setOpen(v=>!v)} aria-expanded={open} aria-controls="table-chat-overlay"><span className="chatBubbleIcon">•••</span><b>CHAT</b></button>{open&&<aside id="table-chat-overlay" className="tableChatOverlay" role="dialog" aria-label="Poker chat"><header className="tableChatOverlayHead"><div><strong>CHAT</strong><span>{viewerLabel(viewer)}</span></div><button onClick={()=>setOpen(false)} aria-label="Close chat">×</button></header>{isTournament&&<nav className="tableChatTabs" aria-label="Chat scope"><button className={scope==='global'?'active':''} onClick={()=>setScope('global')}>Global<small>All players</small></button><button className={scope==='table'?'active':''} onClick={()=>setScope('table')}>Table<small>Table {state?.tournamentTableNumber||'—'}</small></button></nav>}<div className="tableChatLog" ref={logRef}>{!messages.length&&<div className="tableChatEmpty">Nobody has said shit yet.</div>}{messages.map(m=><div className={`tableChatMessage ${m.type==='system'?'system':''}`} key={m.id}><div><b>{m.name}</b>{m.tableNumber&&scope==='global'&&<i>T{m.tableNumber}</i>}{m.viewerType==='spectator'&&<i>WATCHING</i>}<time>{new Date(m.at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</time></div><p>{m.message}</p></div>)}</div>{error&&<div className="tableChatError">{error}</div>}<form className="tableChatForm" onSubmit={e=>{e.preventDefault();send()}}><input value={draft} onChange={e=>setDraft(e.target.value)} maxLength={280} placeholder={scope==='global'?'Talk to the whole tournament…':'Talk to your table…'}/><button disabled={!draft.trim()||sending}>{sending?'…':'Send'}</button></form></aside>}</>}
