import React,{useCallback,useEffect,useRef,useState}from'react';
import'./mtt-lobby.css';
import{assets}from'./assets.js';
import{StatsPanel,ordinal}from'./TablePanels.jsx';
import{globalTournamentStats,tournamentScreen,tournamentWinner}from'./mtt-view.js';
import{rememberTournamentSession,tournamentSessionToken}from'./session.js';

function TournamentResult({code,tournament,session,onExit}){const mode=tournamentScreen(tournament,session),stats=globalTournamentStats(tournament),winner=tournamentWinner(tournament),mine=stats.find(p=>p.id===session.playerId),field=Number(tournament.fieldRemaining)||0,won=Number(session.finishPlace)===1,finished=mode==='finished',ended=mode==='ended';return <main className="tablePage mttLobbyPage"><div className="mttLobbyShell mttResultShell"><header className="mttLobbyHeader"><button className="ghost" onClick={onExit}>← Lobby</button><div><span>MULTI-TABLE TOURNAMENT</span><strong>{code}</strong></div><div/></header><section className={`mttResultHero ${won?'winner':''} ${ended?'ended':''}`}><span className="eyebrow">{won?'FULL TILT CHAMPION':ended?'TOURNAMENT CLOSED':'TOURNAMENT RESULT'}</span><h1>{won?'You won.':ended?'Tournament ended.':finished?'Tournament complete.':`You finished ${ordinal(session.finishPlace)}.`}</h1><p>{won?`${Number(mine?.chips||0).toLocaleString()} chips. Last player standing.`:ended?'The tournament director ended the event before a natural winner was decided.':finished?`${winner?.name||'The winner'} took it down. You finished ${ordinal(session.finishPlace)}.`:`Your run is over. ${field} player${field===1?'':'s'} still fighting for it.`}</p><div className="mttResultMeta"><span>{stats.length} ENTRIES</span><span>{finished&&winner?`WINNER • ${winner.name}`:`${field} LEFT`}</span>{mine&&<span>{mine.stats.knockouts} KO</span>}</div></section><div className="mttResultStandings"><StatsPanel stats={stats} finished={finished} title={finished?'FINAL STANDINGS':'GLOBAL STANDINGS'} subtitle={finished?'Tournament complete':ended?'Stacks when the event was ended':`${field} players remaining`}/></div><button className="primary mttReturnButton" onClick={onExit}>Return to Lobby</button></div></main>}
function TournamentMove({code,move}){return <main className="tablePage mttLobbyPage"><div className="mttMoveScreen"><span className="eyebrow">TABLE CHANGE</span><div className="mttMoveRoute"><b>TABLE {move.from}</b><i>→</i><b>TABLE {move.to}</b></div><h2>Pack your chips.</h2><p>You’re moving to Seat {move.seat}. Your stack and tournament session are coming with you.</p><small>{code} • reconnecting automatically</small></div></main>}

export default function TournamentRoute({code,onExit,renderTable}){
 const params=new URLSearchParams(location.hash.split('?')[1]||''),queryToken=params.get('token')||'',saved=tournamentSessionToken(code),[token,setToken]=useState(queryToken||saved),[view,setView]=useState(null),[publicState,setPublicState]=useState(null),[name,setName]=useState(localStorage.getItem('ftp_name')||''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[copied,setCopied]=useState(false),[move,setMove]=useState(null),lastTable=useRef(null);
 const pageStyle={'--desktop-bg':`url(${assets.default.lobbyDesktop})`,'--mobile-bg':`url(${assets.default.lobbyMobile})`};
 const load=useCallback(async()=>{try{if(token){const r=await fetch(`/api/tournaments/${code}/session?token=${encodeURIComponent(token)}`,{cache:'no-store'}),j=await r.json();if(r.ok){setView(j);setPublicState(j.tournament);setError('');return j}if(r.status!==403)setError(j.error||'Could not load tournament.')}const r=await fetch(`/api/tournaments/${code}`,{cache:'no-store'}),j=await r.json();if(r.ok){setPublicState(j);if(!token)setView(null);return j}setError(j.error||'Tournament not found.')}catch{setError('Connection interrupted. Reconnecting…')}return null},[code,token]);
 useEffect(()=>{if(queryToken){rememberTournamentSession(code,queryToken);setToken(queryToken)}},[code,queryToken]);
 useEffect(()=>{load();const id=setInterval(load,1500);return()=>clearInterval(id)},[load]);
 const tournament=view?.tournament||publicState,session=view?.session;
 useEffect(()=>{const table=Number(session?.tableNumber)||null;if(!session?.provisioned||!table)return;const previous=lastTable.current;lastTable.current=table;if(previous&&previous!==table&&!session.eliminated&&tournament?.status==='running'){setMove({from:previous,to:table,seat:session.seat});const id=setTimeout(()=>setMove(null),1350);return()=>clearTimeout(id)}},[session?.tableNumber,session?.seat,session?.provisioned,session?.eliminated,tournament?.status]);
 async function join(){const clean=name.trim();if(!clean)return setError('Enter a display name.');setBusy(true);try{const r=await fetch(`/api/tournaments/${code}/join`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:clean})}),j=await r.json();if(!r.ok){setError(j.error||'Could not join tournament.');return}localStorage.setItem('ftp_name',clean);rememberTournamentSession(code,j.token);setToken(j.token);location.hash=`#/tournament/${code}?token=${j.token}`}finally{setBusy(false)}}
 async function start(){setBusy(true);try{const r=await fetch(`/api/tournaments/${code}/start`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token})}),j=await r.json();if(!r.ok){setError(j.error||'Could not start tournament.');return}await load()}finally{setBusy(false)}}
 async function copyInvite(){const link=`${location.origin}${location.pathname}#/tournament/${code}`;await navigator.clipboard?.writeText(link);setCopied(true);setTimeout(()=>setCopied(false),1500)}
 const screen=tournamentScreen(tournament,session);
 if(view&&tournament&&session?.provisioned&&screen!=='play')return <TournamentResult code={code} tournament={tournament} session={session} onExit={onExit}/>;
 if(view&&tournament&&session?.provisioned&&move)return <TournamentMove code={code} move={move}/>;
 if(view&&tournament&&tournament.status!=='lobby'&&session?.provisioned)return renderTable({token,session:view});
 const players=tournament?.players||[],tables=tournament?.tables||[],canJoin=tournament?.status==='lobby',isHost=!!session?.host;
 return <main className="tablePage mttLobbyPage" style={pageStyle}><div className="mttLobbyShell"><header className="mttLobbyHeader"><button className="ghost" onClick={onExit}>← Lobby</button><div><span>MULTI-TABLE TOURNAMENT</span><strong>{code}</strong></div><button className="ghost" onClick={copyInvite}>{copied?'Copied ✓':'Copy Invite'}</button></header>{!tournament?<section className="mttLobbyCard"><h2>Finding tournament…</h2><p>{error||'Pulling up the registration desk.'}</p></section>:!session?<section className="mttLobbyCard mttJoinCard"><span className="eyebrow">FULL TILT MTT</span><h2>{canJoin?'Take your seat.':'Registration is closed.'}</h2><p>{canJoin?`Join ${players.length} registered player${players.length===1?'':'s'}. Seats are assigned automatically when the field changes.`:'This tournament has already started.'}</p>{canJoin&&<><input value={name} onChange={e=>setName(e.target.value)} maxLength={24} placeholder="Display name"/><button className="primary" disabled={busy} onClick={join}>{busy?'Registering…':'Join Tournament'}</button></>}{error&&<div className="inlineError">{error}</div>}</section>:<><section className="mttLobbyCard mttStatusCard"><div><span className="eyebrow">REGISTRATION OPEN</span><h2>{players.length} / 50 players</h2><p>{isHost?'Start whenever the field is ready. Starting provisions every child table and locks registration.':'You’re registered. The host controls the start.'}</p></div><div className="mttSeatStamp"><small>YOUR SEAT</small><b>TABLE {session.tableNumber}</b><span>SEAT {session.seat}</span></div></section><section className="mttLobbyCard"><div className="mttRosterHead"><div><span className="eyebrow">LIVE SEATING MAP</span><h3>{tables.length} table{tables.length===1?'':'s'} allocated</h3></div>{isHost&&<button className="primary mttStart" disabled={busy||players.length<2} onClick={start}>{busy?'Building tables…':players.length<2?'Need 2 Players':'Start Tournament'}</button>}</div><div className="mttTables">{tables.map(t=><div className="mttTableCard" key={t.tableNumber}><b>TABLE {t.tableNumber}</b><span>{t.playerIds.length}/8</span><div>{t.playerIds.map(id=>{const p=players.find(x=>x.id===id);return <p className={p?.id===session.playerId?'me':''} key={id}><i>{p?.seat}</i><span>{p?.name}{p?.host?' ★':''}</span></p>})}</div></div>)}</div>{error&&<div className="inlineError">{error}</div>}</section></>}</div></main>
}
